VodovozOrganization/Vodovoz

- VodovozBusiness/Domain/Orders/Order.cs
Убран каст к инту, сейчас с обоих сторон decimal, поэтому количество отгруженных товаров считалось не верно
> Убран каст к инту

- VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
Выборка для проверки наличия автомобиля в МЛ ограничена 1 записью
> Исправление для задачи 3257

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
Возвращён виджет "Контактные лица контрагента" на вкладке "Контакты" карточки Контрагента
> Задача 3202

- VodovozBusiness/Domain/Orders/Order.cs
Добавлена проверка на null входящего значения в set для Свойства Client заказа для установки IsForRetail
Установка значения при обновлении контрагента происходит только после установки контрагента.
> NullReferenceException в случае передачи null в Client в Order

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
I-3332 При открытии сохранённого заказа поле "Подписанные документы" было пустым.
> Исправление "Пропадают данные о подписи документов из заказа"

- Vodovoz/Representations/RouteListsVM.cs
Дополнение к задаче I-3299. Помимо вывода в предупреждении тех тмц, отстатки на складе по которым меньше, чем в заказе (запрос к базе по складу), в предупреждение добавлены тмц, которые совсем отсутствуют на складе (не возвращаются запросом  к базе)
> При отправке МЛ на погрузку в предупреждение добавлены тмц, которые отсутствуют в перечне остатков склада

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
В базу не записываются операции Create для TimeDelivered, только операции Change. Поэтому добавлен поиск по операции Change. Операция Create также оставлена (если будет использоваться в будущем). Берётся самое первое ненулевое значение. Для DeliveryDate всё сделано аналогично.
> Хотфикс 3361 отображение времени в отчёте по изменениям

- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentView.cs
- Vodovoz/Reports/Store/CarLoadDocument.rdl
- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
- VodovozBusiness/Domain/Documents/CarLoadDocumentItem.cs
- VodovozBusiness/Domain/Orders/OrderEquipment.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- VodovozBusiness/HibernateMapping/Documents/CarLoadDocumentItemMap.cs
Теперь тип принадлежности оборудования хранится в документах погрузки.
Исправлено отображение принадлежности в печатной форме талона погрузки.
> Задача 3305 тип принадлежности оборудования при погрузке

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrderItem.cs
При указании в заказе для номенклатуры с целочисленной единицей измерения (н-р, штуки) нецелого количества (н-р, =1,2 как в МЛ 117993) в колонке отображалось целое число, а в бд записывалось введённое (с дробной частью). Далее при отгрузке МЛ такая номенклатура отображалась в списке не отгруженных. Добавлено отсечение дробной части для целочисленных единиц измерения (для единиц измерения с точностью=0).
> 3288 - отсечение дробной части в номенклатурах заказа (для целочисленных единиц измерения)

- Vodovoz/Commons/HotkeyHandler.cs
- Vodovoz/JournalViewModels/DeliveryPointJournalViewModel.cs
- Vodovoz/MainWindow.cs
- Vodovoz/Vodovoz.csproj
- VodovozViewModels/Journals/JournalViewModels/Cash/CashRequestJournalViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Proposal/ApplicationDevelopmentProposalsJournalViewModel.cs
Добавлено сочетание клавиш Ctrl+A для текстовых полей. Возвращены сочетания клавиш Ctrl+C, Ctrl+V, Ctrl+X для текстовых полей (исправлена двойная вставка при запуске ДВ на Windows с русской раскладкой клавиатуры).  Добавлены горячие клавиши Insert и Delete для действий JournalAction.
> 3083-Горячие клавиши

- Vodovoz/Reports/Logistic/DriversToDistrictsAssignmentReport.rdl
Исправлена выборка (учитывает особенности версий районов водителей)
Исправлено отсутсвие статуса "Доставлен"
Исправлено не расширение ячейки, если не влезает статус МЛ
> Фикс 3407-1 исправление отчета по распределению водителей на районы

- Services/Application/VodovozSmsPaymentService/Program.cs
- Services/Application/VodovozSmsPaymentService/VodovozSmsPaymentService.csproj
- Services/Library/SmsPaymentService/SmsPaymentDTOFactory.cs
- VodovozBusinessTests/SmsPaymentService/SmsPaymentItemDTOCalculateTests.cs
- VodovozBusinessTests/VodovozBusinessTests.csproj
Такие проблемы возникают из-за того что в кассу нельзя отправить скидку. Подробное описание проблемы:
Допустим у нас в программе в заказе 3 бутыля по 150 рублей и скидка 50 рублей. Сумма: 3 * 150 - 50 = 400 рублей.
Когда мы посылаем данные в кассу мы должны послать итоговую сумму (400р) а также сумму каждой номенклатуры без скидок. Используемая сейчас формула для каждой номенклатуры: 400 / 3 = 133.33 и 3 в периоде
3 в периоде никуда не записать и она отпадает, из-за этого когда касса сама пытается посчитать итоговую сумму (она это делает) она получает: 133 * 3 = 399.99.
Исправление заключается в следующем:
Сначала проверяем, есть ли у нас проблемная позиция, для этого итоговая сумма по номенклатуре делится на количество и округляется до копеек, затем обратно умножается на количество. Если …
> 3338 Исправление суммы, отправляемой в ЮКассу (распределение цен номенклатур)

- VodovozBusiness/Domain/Orders/Order.cs
При создании заказа из диалога отмены заказа (подтвердить заказ -> отменить заказ -> создать новый заказ из диалога отмены заказа) в заказ не переносилась скидка на доставку (доставка пересчитывается в CalculateDeliveryPrice() при любом изменении в ObservableOrderItems, и когда мы добавляем какую-либо номенклатуру, добавляется/пересчитывается/удаляется доставка, с-но скидка пропадает). Менять что-либо внутри логики пересчёта стоимости доставки специально для случая формирования заказа из недовоза не стал, просто переношу скидку на доставку из недовоза в конце метода копирования номенклатур.
> 3508 - Перенос скидки на доставку при создании заказа из недовоза

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
Для изменения параметров:
- Грузоподъёмность
- Объём груза
- Расход топлива
У раскатных автомобилей теперь требуется наличие права "Изменение в автомобиле расхода топлива, объема груза, грузоподъемности"
> Задача 3576: Ограничение возможности изменения параметров автомобиля

- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
- VodovozViewModels/ViewModels/FilesViewModel.cs
Добавил проверку на длину имени файла при добавлении комментария в ответственном подразделении. Возможно уйдет и вторая ошибка Session.IsClosed
> Еще одна проверка на длину имени файла в рекламациях

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/HibernateMapping/Order/OrderMap.cs
Переделал маппинг некоторых свойств заказа таким образом, что при создании сущности NHibernate'ом не вызываются их сеттеры. Раньше они вызывались, далее вызывался NHibernateUtil.Initialize(Client), который почему-то отключает загрузку всех коллекций заказа, если запускается во время создания сущности.
Переформатировал код в OrderMap
> Фикс пустых OrderItems в заказе

- Vodovoz/Reports/Logistic/GeneralSalaryInfoReport.rdl
Отчет Основная информация по зп берет данные только из закрытых МЛ, т.е. тех, у кого есть подтвержденная зп.
Сделать так, чтобы в отчет попадали все МЛ, кроме Новых. Для незакрытых брать планируемую зп.
Добавить адреса со статусом "В пути".
> 3588 - В отчёт "Основная информация по зп" добавлена планируемая зп для незакрытых МЛ.

- VodovozViewModels/Journals/JournalViewModels/HistoryTrace/HistoryTraceObjectJournalViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/HistoryTrace/HistoryTracePropertyJournalViewModel.cs
Судя по всему, касается только NodeViewModelEntry, которые есть только в журнале изменений, объект изменений и реквизит объекта.
Проверил некоторые другие entityVMentry:
- журнал перемещения ДС, выбор авто
- готовые к погрузке/разгрузке, выбор склада
- сотрудник, выбор подразделения
- отчет по километражу, выбор сотрудника и авто
> 3489 Поиск в виджетах журнала изменений без учета регистра

- Vodovoz/Views/Reports/CarsExploitationReportView.cs
- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Добавлен перенос текста в ячейках с днями. "Событие ТС" в фильтре и таблице перемещено выше и теперь следует сразу за строкой "Рейсы".
> 3585 - Доработки отчёта Аналитика ТС

- Vodovoz/Dialogs/DocumentDialogs/CarUnloadDocumentDlg.cs
- Vodovoz/Dialogs/DocumentDialogs/SelfDeliveryDocumentDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- Vodovoz/Dialogs/SubdivisionDlg.cs
- VodovozBusiness/Domain/Documents/SelfDeliveryDocument.cs
Убран вопрос "Сохранить изменения перед закрытием" при редактировании в диалогах при нажатии на кнопку "Отмена", когда пользователем не производились изменения.
Найдены все места в диалогах где в HasChanges выставляется True, либо с переопределённой логикой HasChanges и убраны, либо поправлены такие места.
Проверено, что связанные документы нормально сохраняются и что при выходе из диалога через кнопку отмена, диалоги не зависают.
Список найденных диалогов:
Убран HasChanges = true и проверена работа:
RouteListClosingDlg - Закрытие МЛ
RouteListMileageCheck - Проверка километража
HasChanges = true доработан:
SubDivisionDlg - Справочник подразделений
CarUnloadDocumentDlg - Талон разгрузки
SelfDeliveryDocumentDlg - Отпуск самовывоза
Найдены, но не требуют исправлений:
RouteListOnDayViewmodel, …
> 3436 - В диалогах при отмене убран вопрос "Сохранить изменения перед закрытием", если изменения не производились

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/DefaultRouteListWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListItemWageCalculationDetails.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListManualWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListOldRatesWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListPercentWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/WageCalculationServiceForOldRouteLists.cs
1.  Добавлено право для просмотра вкладки детализация и информации о зп в футере диалога закрытия. Используется та же логика и то же право, по которой скрываются/отображаются колонки с зарплатой водителя и экспедитора. МЛ должен быть в статусах: Доставлен, Сдаётся, Проверка километража. У пользователя должно быть право: "Управление деньгами. Касса."
2. Все данные по водителю и экспедитору выводятся и считаются отдельно.
3. В детализацию добавлена новая проверка IsValidForWageCalculation из расчёта зп.
> 2995 - Доработки детализации зп в закрытии МЛ

- VodovozViewModels/ViewModels/Complaints/GuiltyItemsViewModel.cs
Кнопка "Добавить виновника" теперь скрывается в зависимости от CanAddGuilty, это свойство вычисляется на основании права на добавление виновника и наличия VM для guiltyItem
> 3444 Исправил создание виджета виновника

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Смотреть комменты к задаче
С одной стороны, при загрузке диалога заказа не будет каждый раз вызываться запрос на получение оснований
С другой стороны - пользователь может кликать туда сюда на вызов выпадающего списка и генерить лишние запросы ¯\_(ツ)_/¯
Плюс думал перед и после выполнения запроса менять Sensitivity, но работает как то криво
Ну а SpecialState считаю нужным добавить в любом случае. Сломать всякие if (Selected == null) не должно
> 2342 Подгрузка актуальных оснований

- Vodovoz/MainWindow.cs
Всё меню Зарплата вместе с подменю засеривается при отсутствии права "Установка заработной платы". В подменю зарплаты есть пункт Планы продаж, который должен быть доступен пользователю с правом "Управление зп своего подразделения" (даже при отсутствии права "Установка заработной платы"). Проверка наличия данных прав перенесена с меню Зарплата на его подменю.
> 3677 - Исправлены права для доступа в Планы продаж из меню Зарплата

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
При активации чекбокса "Самовывоз" точка доставки зануляется, а _addedFlyersNomenclaturesIds заполняется в методе TryAddFlyers только, если точка доставки не нулл. Поэтому _addedFlyersNomenclaturesIds был нуловым и проверка _addedFlyersNomenclaturesIds.Any() вызывала ошибку. Добавил проверку на null.
> Фикс проверки добавленных листовок в заказе

- Vodovoz/Dialogs/UndeliveredOrderDlg.cs
- VodovozBusiness/Domain/Service/BaseParametersServices/BaseParametersProvider.cs
- VodovozBusiness/Domain/Sms/SmsNotificationType.cs
- VodovozBusiness/Domain/Sms/SmsNotifier.cs
- VodovozBusiness/Domain/Sms/UndeliveryNotApprovedSmsNotification.cs
- VodovozBusiness/HibernateMapping/Sms/SmsNotificationMap.cs
- VodovozBusiness/Services/ISmsNotifierParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
Необходимые изменения БД в комментарии к задаче.
Функционал формирования смс для клиента, если в недовозе при переносе заказа клиент не ответил на звонок и не подтвердил перенос. Заказ всё равно переносят и присылают смс-уведомление.
Добавлен новый класс смс-уведомлений с Counterparty и UndeliveredOrder.
Добавлен новый геттер шаблона сообщения из параметров базы.
Добавлен новый тип уведомлений - UndeliveryNotApproved.
Новый метод формирования смс-уведомления в SmsNotifier. В методе присутствуют все необходимые проверки и занесение уведомления в базу со статусом "New".
Метод вызывается при соблюдении необходимых условий при сохранении недовоза.
Добавлен новый формирователь номера телефона для недовоза.
> 3673 СМС при переносе заказа без аппрува

- Services/Application/VodovozSmsInformerService/Program.cs
- Services/Application/VodovozSmsInformerService/UndeliveryNotApprovedSmsInformer.cs
- Services/Application/VodovozSmsInformerService/VodovozSmsInformerService.csproj
- VodovozBusiness/Domain/Sms/SmsNotifier.cs
- VodovozBusiness/EntityRepositories/SmsNotifications/ISmsNotificationRepository.cs
- VodovozBusiness/EntityRepositories/SmsNotifications/SmsNotificationRepository.cs
Сервис уведомлений о недовозе, сделанный по аналогии с сервисом уведомлений новых клиентов.
Получает уведомления со статусом "New" и типом "UndeliveryNotApprover", удаляет истёкшие уведомления (если такие каким-то образом появились) и отправляет новые, переводя статус в "Отправлено"
> 3673 Добавление смс-сервиса по недовозам

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- VodovozBusiness/EntityRepositories/Orders/OrderSingletonRepository.cs
Функционал на изменение даты контракта при изменении даты доставки (при ещё не сохраненном заказе уже сделано)
Если заказ уже был сохранен, но меняется дата доставки, дата контракта также будет изменена
Добавлена проверка на то, будет ли заказ с новой датой доставки первым в очереди
Выводится окно с предупреждением о изменении даты контракта
> 3366 Изменение даты контракта в первом заказе клиента, если заказ уже в базе

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- VodovozBusiness/EntityRepositories/Orders/OrderSingletonRepository.cs
В репозитории создан метод проверки уже существующего заказа. 
Метод использует новый UoW, который создается на месте для предотвращения транзакции. 
UoW создается фабрикой, которая резолвится автофаком перед валидацией и передается в контекст.
Из контекста фабрика отправляется уже в новый метод.
Новый метод используется в валидации, сравнивается ID текущего заказа с найденными, если не равен - найден уже созданный заказ и валидация не проходит.
> 3684 Валидация на дублирующийся заказ вне текущей сессии

- Vodovoz/Infrastructure/Mango/MangoManager.cs
- Vodovoz/ViewModels/Mango/Talks/UnknowTalkViewModel.cs
- Vodovoz/Views/Mango/Talks/UnknowTalkView.cs
- Vodovoz/Vodovoz.csproj
Чтобы быстро исправить ошибку - вернул старое имя вью модели.
Чуть позже исправлю нормально, с переименованием вьюхи
> Переименовал вьюмодель, чтобы быстро поправить ошибку

- VodovozBusiness/Domain/Orders/UndeliveryTransferAbsenceReason.cs
Если не заполнить поле «Название» при создании причины выскакивала ошибка.
> 3532 Фикс ошибки при создании "Причины отсутствия переноса"

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
При самовывозе кнопки и лейбл не будут отображаться, чтобы не путать пользователя
> 3694 Фикс отображения кнопок изменения типа адреса при самовывозе

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Payments/Payment.cs
- VodovozBusiness/EntityRepositories/Payments/IPaymentsRepository.cs
- VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
- VodovozBusiness/HibernateMapping/Accounting/PaymentMap.cs
- VodovozBusiness/HibernateMapping/Payments/PaymentItemMap.cs
При переводе адреса МЛ в статусы В пути и Выполнен из Недовоз или Доставка отменена, если ассоциированный с адресом заказ - заказ с оплатой по безналу, проверяется наличие возврата, который удаляется и заказ меняет статус оплаты
> 3642 Удаление возвратного платежа при восстановлении заказа в работу

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListControlDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/JournalViewModels/RouteListWorkingJournalViewModel.cs
- Vodovoz/Reports/Store/CarUnloadDoc.rdl
- Vodovoz/Representations/RouteListsVM.cs
- VodovozBusiness/Domain/Documents/DriverTerminalTransfer/AnotherDriverTerminalTransferDocument.cs
- VodovozBusiness/Domain/Documents/DriverTerminalTransfer/DriverTerminalTransferDocumentBase.cs
- VodovozBusiness/Domain/Documents/DriverTerminalTransfer/DriverTerminalTransferDocumentType.cs
- VodovozBusiness/Domain/Documents/DriverTerminalTransfer/SelfDriverTerminalTransferDocument.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- VodovozBusiness/HibernateMapping/Documents/DriverTerminalTransferDocumentBaseMap.cs
- VodovozBusiness/VodovozBusiness.csproj
Доработка позволяет грузить терминал водителю с его старого МЛ на его новый, когда один и тот же водитель делает 2 ходки утром и вечером, и вечером он попросит тот же терминал.
В "Журнале МЛ" и в "Работа кассы с МЛ" добавлен пункт "Перенести терминал на 2-ю ходку". По нажатии происходит поиск второго МЛ на ту же дату, с тем же водителем и только со статусом "На погрузке". Если не нашел или нашел больше одного, то выдаётся сообщение с причиной и просьбой перенести вручную. Также добавлены в проверку ситуации, когда терминал может быть привязанным к водителю в карточке или терминала может не быть в первом МЛ.
Если нашли, то переносим терминал через новый документ.
Выделен базовый класс из DriverTerminalTransferDocument. Одна реализация текущая, другая только для переноса терминалов из …
> 3749 Приём-передача терминала с 1 ходки на 2

- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListItemRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListItemRepository.cs
Каким-то образом возможно сформировать дубль адреса. И эту ситуацию не получается исправить в диалоге создания. 
Чтобы такую ситуацию можно было исправить в диалоге создания МЛ была исправлена проверка на нахождение адреса в **другом** МЛ (в методе исключён **текущий** МЛ из проверки).
В репозиторий добавлена проверка дубликатов в текущем МЛ. В метод передаётся актуальный список адресов (т.к. его, возможно, ещё не успели сохранить после удаления дубликата).
> 2664 Исключение из валидации проверки текущего МЛ в других МЛ

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Logistic/RouteListItem.cs
Исправил ошибку с некорректным возвратом адреса при переносе в исходный МЛ
- сделал колонку Нужна загрузка нередактируемой в правой панели;
- удалил неиспользуемый параметр из метода FirstFillClosing;
> 3795 Исправление переноса адресов в МЛ

- Vodovoz/Reports/Logistic/AnalyticsForUndelivery.rdl
В отчете по аналитике недовозов в запросам по количеству опозданий на адреса и минуты сделал Timestampdiff через секунды, раньше секунды отбрасывались и итоговые значение расходились
> Фикс расчета минут опозданий 

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- VodovozBusiness/EntityRepositories/Cash/CashRepository.cs
- VodovozBusiness/EntityRepositories/Cash/ICashRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- VodovozBusiness/Models/NewDriverAdvanceModel.cs
- VodovozBusiness/Parameters/NewDriverAdvanceParametersProvider.cs
- VodovozBusiness/Services/INewDriverAdvanceParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
Добавлен функционал при закрытии МЛ: новые водители на своём авто на время испытательного срока (с 6-го по 60-й рабочий день) получают аванс  (дни и сумма аванса задаются в параметрах). 
- Рабочими днями считаются те дни, в которых был хотя бы один МЛ.
- Первым рабочим днем считается день, в котором был первый МЛ у этого водителя.
- Если ЗП водителя за МЛ меньше суммы аванса в параметрах, то выдаётся аванс в 50% от суммы ЗП за МЛ.
- Если есть незакрытые МЛ прошлых дней, то аванс не выдаётся и выводится вопрос: "У водителя есть незакрытые МЛ с №№ на даты. Текущий МЛ будет закрыт без выдачи аванса. Продолжить или отменить?". При отмене МЛ не закрывается, при подтверждении закрывается без аванса.
- При подтверждении закрытия МЛ добавлен вывод суммарной информации по суммам приходных ордеров, …
> Хотфикс 3805: Аванс для новых водителей на своем авто в определённый диапазон дней

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Исправление неправильной работы, когда numericRenderer не закрывался при выборе другого виджета вне три вьюхи, например энтри
> Исправление косяка с numericRenderer в колонке количество у заказа

- Services/Library/SmsPaymentService/SmsPaymentDTOFactory.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Models/IOrganizationProvider.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
- VodovozBusiness/Parameters/IParametersProvider.cs
- VodovozBusiness/Parameters/OrganizationParametersProvider.cs
- VodovozBusiness/Parameters/ParametersProvider.cs
- VodovozBusiness/Services/IOrganizationParametersProvider.cs
Заказы с временем создания менее чем указано в параметрах, оплаченные по смс и принадлежащие к Северной части города теперь встают на Южную организацию
Добавил в ParametersProvider возможность получать параметр любого значащего типа через дженерик параметр
> Выпилил устаревшие проверки на дату доставки заказа и подбор организации по этой дате

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Некорректно работало скрытие комбо с типами распечатываемых доков и замена его на надпись Торг-12 2шт
> Дополнил условие скрытия надписи печатаемых документов

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Orders/Order.cs
Запрещаем удаление арендных строк заказа, если есть связанное с ними оборудование
При удалении последнего связанного оборудования, удаляем и строки заказа по аренде
> Запрет на удаление арендных строк заказа

- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Для признака "авто без движений" добавил учёт фильтра по принадлежности ТС из версии автомобилей.
> Хотфикс аналитики эксплуатации ТС

- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
- VodovozBusiness/Domain/Logistic/Discrepancy.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
1. В закрытии МЛ исправлено неверное значение в колонке Недопогрузка для заказов с доставкой за час.
2. Фикс отгружаемого количества в талоне погрузки при заполнении для склада для МЛ с доставкой за час.
3. Учёт оборудования в ожидаемом количестве талона разгрузки и в возвратах/недовозах диалога закрытия МЛ.
> 3968 Дополнения в талоны разгрузки/погрузки (доп.вопросы)

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Goods/OrderItemComparerForCopyingFromUndelivery.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/EntityRepositories/Undeliveries/IUndeliveredOrdersRepository.cs
- VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrdersRepository.cs
- VodovozBusiness/VodovozBusiness.csproj
Проверяем цены в перенесенном заказе через недовоз
Позиции, что перенесены из старого заказа, не должны быть меньше по ценам
Новые позиции, которые были добавлены после переноса, валидируются по старой схеме: цена должна быть не меньше фиксы или номенклатурного прайса
> 3949 добавил в валидацию проверку цен в перенесенном заказе

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Payments/Payment.cs
- VodovozBusiness/Domain/Payments/PaymentItem.cs
- VodovozBusiness/EntityRepositories/Payments/IPaymentsRepository.cs
- VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
- VodovozBusiness/HibernateMapping/Accounting/PaymentMap.cs
- VodovozViewModels/Journals/JournalViewModels/Payments/PaymentsJournalViewModel.cs
- VodovozViewModels/ViewModels/Payments/AutoPaymentMatching.cs
- VodovozViewModels/ViewModels/Payments/ManualPaymentMatchingViewModel.cs
добавил функционал по задаче:
- блокируем открытие диалога распределения конкретного платежа, если кто-то уже с ним работает;
- обновляем список заказов при запуске;
- сделана доработка по авто сопоставлению платежа(дублирующиеся платежи из одной выписки уходят в ручное распределение);
> 4031 Обновление диалога ручного распределения

- Vodovoz/Filters/ViewModels/CounterpartyJournalFilterViewModel.cs
- Vodovoz/JournalViewModels/RetailCounterpartyJournalViewModel.cs
Т.к. Dispose uow вызывается либо из вьюхи, либо из скоупа, то если журнал контрагентов не открывался, а создавался без автофака, то и освобождения ресурсов uow фильтра не произойдет
> Убираем инициализацию salesChannel из конструктора

- Vodovoz/JournalViewModels/SelfDeliveriesJournalViewModel.cs
меняем вызов First на FirstOrDefault, чтобы не летела ошибка при клике правой кнопки в пустом журнале самовывозов
> Исправление NullRefExc

- VodovozReports/Reports/Payments/PaymentsFromAvangardReport.rdl
убрал поиск в диапазоне даты создания заказа, т.к. при оплатах через СБП все номера уникальные
> Исправление отчета оплат из Авангарда

- VodovozBusiness/Domain/Orders/Order.cs
Добавляем в исключения Терминал при стоп-отгрузках, чтобы с этим типом оплаты можно было выставлять заказы
> Обновление валидации заказа

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
Когда клавишей контрол выбирали несколько адресов и нажимали перенести, запись в базу происходила только после переноса всех адресов, поэтому в цикле остатки после переноса первого заказа через метод репозитория _routeListItemRepository.HasEnoughQuantityForFastDelivery подсчитывались неверно. Это позволяло перенести все выделенные адреса (если хватало остатков на перенос первого адреса), даже если после переноса первого уже нет остатков.
> 4112 Фикс переноса нескольких заказов с быстрой доставкой

- Services/Application/VodovozDeliveryRulesService/DeliveryRulesService.cs
Пока убираем геокодирование адреса с сайта, т.к. не хватает лимитов по ключам яндекс api
> Убираем геокодирование адреса с сайта

- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
CanGenerate отвечает за доступность кнопки генерации отчёта. На неё влияет в том числе выбор показателей. Убрал сообщение, возможность генерации сделал через биндинг.
> Правка св-ва CanGenerate в Аналитике эксплуатации ТС

- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Logistic/RouteListItem.cs
Если адрес был возвращен в исходный МЛ, то при удалении его из МЛ в котором он был не меняем статус заказа;
> 4136 Обновление логики удаления адреса из МЛ

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Если при выборе ТД из заказа в ТД поменять комментарий, то диалог заказа не знал об изменениях в ТД и подставлял старый комментарий.
> Фикс вставки комментария в заказ из ТД

- Source/Applications/Desktop/Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
По задаче 4122 "При целенаправленном поиске по номеру телефона или входящем звонке пользователь должен получить полную информацию в каких контрагентах этот номер есть."
> Не скрывать контрагентов в журнале при поиске по архивному номеру

- Source/Applications/Desktop/VodovozViewModels/Dialogs/Counterparty/DeliveryPointViewModel.cs
Яндекс стал возвращать помимо координат с точкой координаты с запятой
> Фикс координат яндекс геокодера

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListTrackDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/TrackRepository.cs
Когда у МЛ менялся водитель, а в треках сохранён старый водитель, то в мониторинге на таком водителе возникало исключение, и остальные авто не прорисовывались на карте.
> Фикс отображения водителей на карте в мониторинге

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
При переносе оплаты по карте из недовоза, теперь отображается откуда оплата, если пункт по умолчанию скрыт.
> 4179 - Разблокировать скрытый источник оплаты при переносе

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
При вызове UoW.Session.Refresh(Entity) теряется связь у дочерних для Entity observable list-ах с изначальными списками. Если после вызова UoW.Session.Refresh(Entity) изменить содержимое в дочернем observable list-е, то изменения в изначальном присоединённом списке не будут отслеживаться NHibernat-ом и не запишутся в базу.
> Reconnect observable list to objects

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
При переносе оплаченного по безналу заказа окно подтверждения переноса оплаты не появляется. Оплата переносится автоматически.
> 4335 Убрать предупреждение о форме оплаты

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/Orders/CopyingOrder.cs
1. В диалоге резюмирования заказа теперь появляется предупреждающее сообщение в случаях когда в карточке контрагента установлена форма оплаты по умолчанию и в заказе она отличная
Текст предупреждения: "Вы выбрали форму оплаты <...>. У клиента по умолчанию установлено <...>. Вы уверены, что хотите продолжить?"
2. Если у клиента установлена форма оплаты по умолчанию, то при копировании заказа подставляется форма оплаты, как в карточке контрагента
> 4329 - Предупреждение о неверной форме оплаты

- Source/Applications/Desktop/Vodovoz/ViewWidgets/GuiltyInUndeliveryView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/UndeliveredOrderView.cs
при изменении цвета/стиля/размерности шрифта и выставлении sensitive в false, надписи пропадают из treeview, поэтому я сделал ее доступной но заблочил остальные элементы
> переделал доступность виновных в недовозах

- Source/Applications/Desktop/Vodovoz/JournalViewModels/OrderForRouteListJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrderJournalViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Goods/INomenclatureRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Goods/NomenclatureRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/INomenclatureParametersProvider.cs
В данный момент в таблице параметров БД номер номенклатуры выезда мастера для санобработки указан одним числом.
Изменения позволяют ввести несколько id номенклатур выезда мастера в таблице параметров БД через запятую. 
В журналах заказов, присутствующие в заказе номенклатуры выездов мастера будут суммироваться и отображаться в столбце "Кол-во с/о"
> 4363 Санобработка в журнале заказов

- Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/DeliveryPointPanelView.cs
Т.к. при копировании тмц из панели ТД не копируются промонаборы для каждой тмц, то и для заказа они не нужны.
> Фикс копирования строк заказа из панели ТД заказа

- Source/Libraries/Core/Business/VodovozBusiness/Domain/FastPayments/FastPayment.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/SmsPayment.cs
Исправлены методы отвечающие за изменение статуса заказа с самовывозом
Проблема с изменением статуса заказа с самовывозом с оплатой после отгрузки
Если оплата заказа  была произведена до отпуска самовывоза, заказ после отпуска самовывоза оставался в "Ожидание платежа"
Если оплата была выполнена для заказа в статусе "Ожидание платежа", то он не переходит в статус "Закрыт"
> Хотфикс. Изменение статуса заказа после оплаты по SMS QR

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
считаем все 19л бутыли заказа, не смотря на тип тары, т.к. появились 19л в одноразовой таре
> правка расчета операции перемещения бутылей

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Окно с индикацией недружественной ошибки скрывается, т.к при эксепшене при подтверждении заказа уже было показано сообщение с комментарием
> Хотфикс. Отключение появления окна с ошибкой после падения при подтверждении заказа

- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/CounterpartyFilterView.cs
При поиске по ИНН в журнале КА , если пользователь вставляет ИНН с переносом строки в конце, то контрагент не находится.
> Хотфикс. Ввод только цифр в поле ИНН фильтра

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteList.cs
В валидации МЛ при поиске дубля онлайн оплат не учитываются отмененные заказы
> Хотфикс. Отмененные заказы не учитываются при проверке дубля онлайн оплаты

- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListJournalViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
если журнал не обновлялся, то данные по МЛ подтянутся из сессии, а не из базы и МЛ будет без документа по топливу
> грузим отдельно операции, а не смотрим в самом МЛ

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
разделил запрос на два, сначала получаем все нужные заказы, по которым не было отправки, затем берем те, по которым нужна переотправка и объединяем две полученные коллекции, беря уникальные значения
> оптимизация получения заказов для отправки УПД по ЭДО

- Source/Applications/Desktop/VodovozViewModels/Logistic/Reports/CarIsNotAtLineReport.cs
Исправление даты в выборке
Теперь события, где окончание события >= даты (первого времени дня), указанной как параметр отчета будут попадать в выборку событий
> Хотфикс - изменение в отчете по простою

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Orders/UndeliveryViewModel.cs
если это внешний uow, то передаем его отдельным параметром, чтобы при сохранении уведомления недовоз был сохранен
> исправление падения при сохранении уведомления

- Source/Libraries/Core/Backend/CustomerAppsApi.Library/Models/OrderModel.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/FreeLoaderChecker.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderFromOnlineOrderValidator.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IFreeLoaderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/Orders/IFreeLoaderChecker.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/FreeLoaderRepository.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/OrderRepository.cs
- исключаем возможность автоматического заказа промиков для новых клиентов в самовывозе из онлайна;
- в первую очередь проверяем халявщика по Guid ФИАСа, если он есть, только потом по обычному адресу
> 5066 дополнил проверку на халявщиков

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrderItem.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/CashReceipts/FiscalDocumentPreparer.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/OrderReceiptCreator.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/ReceiptPreparer.cs
- при формировании чека не обрабатываем позиции с нулевой суммой, исключая тем самым работу с кодами, если это маркированный товар;
- при формировании фискального документа также пропускаем товары нулевые по сумме;
> 5096 не берем в чек позиции с нулевой суммой

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
если таска пришла без необходимости отправки, возможно контейнер ушел раньше. Поэтому ищем такой и соединяем их с проставлением нужного статуса
> добавил поиск контейнера

- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Source/Libraries/Core/Backend/CustomerAppsApi.Library/Models/CounterpartyModel.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Clients/CounterpartyEdoAccountController.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/ICounterpartyEdoAccountController.cs
для случаев, когда не создались ЭДО аккаунты по умолчанию прикрепляем их к клиенту перед инициализацией вьюхи
> поменял логику добавления дефолтных ЭДО аккаунтов

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
т.к. в moneyMovementOperation учитывается приход только налички, а все остальные оплаты остаются по нулям, то чтобы считать актуальный долг, приняли решение считать только безнал, соответственно физики будут всегда с нулевым долгом, а юрики с нужной цифрой
> по другому проверяем долг при архивации
