VodovozOrganization/Vodovoz

- Vodovoz/Dialogs/Fuel/FuelWriteoffDocumentView.cs
- Vodovoz/Dialogs/Fuel/FuelWriteoffDocumentViewModel.cs
- Vodovoz/Dialogs/Goods/EquipmentGenerator.cs
- Vodovoz/Infrastructure/Services/EntityRepresentationSelectorAdapter.cs
- Vodovoz/JournalViewModels/ClientCameFromJournalViewModel.cs
- Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
- Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
- Vodovoz/JournalViewModels/NomenclaturesJournalViewModel.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/JournalViewModels/ResidueJournalViewModel.cs
- Vodovoz/JournalViewModels/SelfDeliveriesJournalViewModel.cs
- Vodovoz/JournalViewModels/Suppliers/RequestsToSuppliersJournalViewModel.cs
- Vodovoz/MainWindow.cs
- Vodovoz/Representations/DebtorsJournalViewModel.cs
- Vodovoz/ViewModels/Client/SupplierPricesWidgetViewModel.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- Vodovoz/ViewModels/Suppliers/RequestToSupplierViewModel.cs
- Vodovoz/Views/Complaints/ComplaintView.cs
- Vodovoz/Views/Complaints/CreateComplaintView.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozViewModels/JournalViewModels/ComplaintsJournalViewModel.cs
- VodovozViewModels/JournalViewModels/Employees/FinesJournalViewModel.cs
- VodovozViewModels/JournalViewModels/Organization/SubdivisionsJournalViewModel.cs
- VodovozViewModels/JournalViewModels/WageCalculation/SalesPlanJournalViewModel.cs
- VodovozViewModels/JournalViewModels/WageCalculation/WageDistrictLevelRatesJournalViewModel.cs
- VodovozViewModels/JournalViewModels/WageCalculation/WageDistrictsJournalViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionsViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
- VodovozViewModels/ViewModels/Employees/FineViewModel.cs
- VodovozViewModels/ViewModels/WageCalculation/CarsWageParametersViewModel.cs
- Чтобы установить задержку при вводе в поиске, аналогичную той которая была необходимо глобально в проекте установить переменную. https://github.com/QualitySolution/QSProjects/blob/feature/Refactor_JournalSearch/QS.Project.Gtk/Project.Search.GtkUI/SearchView.cs#L19
- Проверти применение прав на чтения сущьностей. Добавлены через хак, чтобы не переделывать журналы.
-Надо искать поломанные вызовы журналов... Так как список параметров изменился.
- Проверяйте использование CloseTab у ITdiTab. Само событие при закрытии вкладки еще вызывается, сделано для совместимости с клинским кодом который на него подписывался чтобы узнать о закрытии. Но вызов этого события из внутренностей вкладки, теперь ее не закроет. Переводите на новый механизм. В идеале CloseTab вообще удалить в ближайшее время.
> Подстройка по изменения журналов в библиотеке.

- Vodovoz/Reports/ServiceCenter/MastersReport.rdl
Добавлено изменение нейминга в поле формирование отчета.
fines_advance => total_fines
> Фикс исправления нейминга

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
Установлены метки измерения производительности на закрытие Маршрутного Листа
> Метки производительности закрытия МЛ

- Services/Application/VodovozMangoService/Calling/CallInfo.cs
- Services/Application/VodovozMangoService/HostedServices/CallsHostedService.cs
- Services/Application/VodovozMangoService/HostedServices/NotificationHostedService.cs
- Services/Application/VodovozMangoService/HostedServices/PhonebookHostedService.cs
- Services/Application/VodovozMangoService/Protobuf/PhonebookService.proto
- Services/Application/VodovozMangoService/Startup.cs
- Services/Application/VodovozMangoService/VodovozMangoService.csproj
- Services/Library/ClientMangoService/ClientMangoService.csproj
- Services/Library/ClientMangoService/MangoServiceClient.cs
- Services/Library/MangoController/MangoController.cs
- Vodovoz/Infrastructure/Mango/MangoManager.cs
- Vodovoz/ViewModels/Mango/SubscriberSelectionViewModel.cs
- Vodovoz/Views/Mango/SubscriberSelectionView.cs
- Vodovoz/Vodovoz.csproj
Не знаю как мне даше на тест передавать, мержить в девелоп или нет. 
Поэтом пул рекветс.
> Задача по доработке сервиса для отображения текущего статуса абонента

- Vodovoz/Representations/UndeliveredOrdersVM.cs
Добавлен поиск по идентификатору
> Добавлено отображение идентификатора

- Vodovoz/gtk-gui/MainWindow.cs
- VodovozInfrastructure/VodovozInfrastructure.csproj
> Вернул дефолтную высоту для MainWindow

- Vodovoz/gtk-gui/Vodovoz.EmployeeDlg.cs
> Исправлен баг допущеный при слиянии веток в генерации стетика

- Vodovoz/Dialogs/Cash/CashRequestView.cs
- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Добавлено условие для сохранения - в случае если пользвоатель фининсист статья расхода должна быть заполнена
Исправлено сообщение об ошибке при добавлении суммы и не заполненной статье расхода
> Изменена проверка видимости поля сиатьи расхода

- Vodovoz/Reports/Store/CarLoadDocument.rdl
Исправление выборки оборудования в печатной форме погрузочного талона
> Выборка оборудования ограничена оборудованием

- Vodovoz/Dialogs/Cash/CashRequestView.cs
> Исправлена видимость label для статьи расхода

- Vodovoz/Representations/RouteListsVM.cs
Добавлен статус "В Пути" в список статусов из которых возможно открытие разбора МЛ
> Удалён не используемый список статусов

- Vodovoz/MainWindow.cs
- Vodovoz/ReportsParameters/SalesReport.cs
Для видимости отчетов в меню отчеты добавлена проверка на право user_is_sales_representative
Для отчета по продажам добавлено ограничение по автору если у пользователя установлено право user_is_sales_representative
> Добавлено изменение видимости и изменен отчет продаж

- Vodovoz/MainWindow.cs
- Vodovoz/ReportsParameters/SalesReport.cs
Изменена проверка на админа
Изменено получение текущего сотрудника в отчете
> Рефакторинг хотфикса

- Vodovoz/Reports/Complaints.rdl
Добавил столбец "Время создания" в отчет по рекламациям
> I-3271 Добавил столбец "Время создания" в отчет по рекламациям

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
- VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/ICarRepository.cs
Если у пользователя есть право на установку галочки раскат в карточке автомобиля и автомобиля нет ни в одном МЛ - возможно изменить состояние галочки раскат.
> Добавлено право на редактирование чекбокса раскат в карточке автомобиля

- VodovozBusiness/Domain/Orders/Order.cs
Исправлен баг - в случае валидации заказа без точки доставки происходит NullReferenceException
> Исправление для задачи 3209

- VodovozViewModels/Journals/JournalViewModels/ComplaintsJournalViewModel.cs
- VodovozViewModels/ViewModels/Complaints/GuiltyItemsViewModel.cs
Добавлена обработка прав на закрытие рекламации
Добавлена обработка прав для добавления виновного в рекламацию
> Задача 3111

- Vodovoz/Filters/GtkViews/ComplaintFilterView.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.ComplaintFilterView.cs
- VodovozViewModels/Journals/FilterViewModels/ComplaintFilterViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/ComplaintsJournalViewModel.cs
Добавлен фильтр по статусу обсуждения для текущего подразделения пользователя.
> Задача 3203

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/ViewWidgets/CounterpartyDocumentsView.cs
Ускорено сохранение в карточке контрагента.
> Задача 3117

- Vodovoz/Dialogs/DocumentDialogs/RegradingOfGoodsDocumentItemsView.cs
- Vodovoz/JournalViewModels/NomenclatureStockBalanceJournalViewModel.cs
Заменен старый журнал в Добавить строку на новый
> Исправление для задачи 3180

- Vodovoz/Dialogs/Employees/EmployeeDlg.cs
- Vodovoz/gtk-gui/Vodovoz.EmployeeDlg.cs
- VodovozBusiness/Domain/Employees/Employee.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverDistrictPriority.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverDistrictPrioritySet.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverWorkSchedule.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverWorkScheduleSet.cs
- VodovozViewModels/ViewModels/Logistic/DistrictsSetActivationViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DriverDistrictPrioritySetViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DriverWorkScheduleSetViewModel.cs
> Исправил задвоение в запросе

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/MainWindow.cs
- Vodovoz/toolbars/ToolbarActions.cs
Внесены правки в диалог создания заказа.
Теперь диалог создания заказа будет отображать только контрагента розницы/не розницы в зависимости от того, какие настройки установлены в фильтре журнала заказов.
> Задача 3294

- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePayment.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForDebt.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForPayment.cs
- VodovozBusiness/HibernateMapping/Order/OrderMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForDebtMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForPaymentMap.cs
Добавлен маппинг для полей
Добавлена логика обновления поля для розницы
Изменен журнал для работы с полями сущностей журнала заказов
> Оптимизация запроса для задачи 3294

- Vodovoz/Reports/Orders/EShopSalesReport.rdl
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Orders.EShopSalesReport.cs
Исправлен формат столбцов количества в отчете
Убраны разрывы страниц между таблицами
Увеличена высота заголовка
Увеличена высота элемента интерфейса для выбора статусов
> Исправления для задачи 3276

- Vodovoz/Reports/Payments/PaymentsFromBankClientAllSubdivisionsReport.rdl
- Vodovoz/Reports/Payments/PaymentsFromBankClientBySubdivisionReport.rdl
Reverts VodovozOrganization/Vodovoz#184
> Revert "Добавление комментария к заказу к отчетам по оплате и замена сортировки"

- Vodovoz/Views/Logistic/DeliveryPointResponsiblePersonsView.cs
Исправлена ошибка при сохранении точки доставки
> Исправление для точки доставки

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/toolbars/ToolbarActions.cs
Убран параметр из конструктора
Добавлено свойство
Добавлена инициализация свойства
Изменены использования поля на использования свойства
Убран модификатор только для чтения для поля
> Фикс проблемы с открытием диалога заказа из манго

- Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
Добавлен диалог настроек принтера для печати Путевых листов
> Задача 3284 Добавлен диалог настроек принтера для печати Путевых листов

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/ViewWidgets/Logistics/RouteListDiscrepancyView.cs
- Vodovoz/gtk-gui/Vodovoz.RouteListDiscrepancyView.cs
Исправлена интерактивность контейнера таблицы для боковой панели недовозов
> Задача 3144 Исправлена невозможность прокручивать недовозы в боковой панели диалога закрытия МЛ

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/ViewWidgets/DepositRefundItemsView.cs
- Vodovoz/ViewWidgets/OrderEquipmentItemsView.cs
- Vodovoz/gtk-gui/Vodovoz.ViewWidgets.OrderEquipmentItemsView.cs
Изменен механизм применения доступности к элементам интерфейса на вкладке "Товары"
> Задача 3165 Исправление скроллбаров для карточки заказа, вкладки "Товары"

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- VodovozBusiness/Services/INomenclatureParametersProvider.cs
Исправлено копирование номенклатур доставки
> Задача 3188 Исправлено копирование номенклатур доставки

- VodovozBusiness/Domain/Orders/Order.cs
Исправлено перемещение последнего заказа контрагента в розницу в карточке Контрагента.
> Хотфикс 3308 Исправление проблемы при переводе Контрагента в розницу

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Добавлен вызов окна предупреждения о закрытых поставках при копировании заказа.
Добавлен вызов окна предупреждения о закрытых поставках при создании/копировании из окна звонка.
> Задача 3254: добавление окна предупреждения о закрытых поставках при копировании заказа

- Vodovoz/CreateProjectParam.cs
- Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
- Vodovoz/JournalNodes/CounterpartyJournalNode.cs
- Vodovoz/JournalNodes/RetailCounterpartyJournalNode.cs
- Vodovoz/JournalNodes/RetailOrderJournalNode.cs
- Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/JournalViewModels/RetailCounterpartyJournalViewModel.cs
- Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Vodovoz/MainWindow.cs
- Vodovoz/Vodovoz.csproj
Теперь в заказах и контрагентах отображаются заказы и контрагенты розницы.
Заказы и контрагенты розницы отображаются серым цветом и действия с ними не доступны, если у пользователя нет прав на доступ ко вкладке розница.
> Задача 3316 Изменено поведение журналов контрагентов и заказов

- Vodovoz/Views/Logistic/DistrictsSetView.cs
В версиях районов при выборе района изменён способ выделения на цветовую обводку границ на карте красным цветом
> В версиях районов при выборе района изменён способ выделения

- Vodovoz/Reports/Payments/PaymentsFromBankClientAllSubdivisionsReport.rdl
- Vodovoz/Reports/Payments/PaymentsFromBankClientBySubdivisionReport.rdl
(cherry picked from commit ab05d159b409a009f79681e7266431c6c84ac711)
> Перенос коммитов задач 3242, 3267 по исправлению отчетов в мастер

- Vodovoz/Dialogs/DocumentDialogs/CarUnloadDocumentDlg.cs
Добавлено обновление видимости тары для возврата после выбора маршрутного листа
> Видимость тары для возврата (I-3293)

- Vodovoz/Dialogs/Cash/CashRequestView.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.Cash.CashRequestView.cs
- VodovozBusiness/ConfigureDeletion.cs
- VodovozBusiness/Domain/Cash/CashRequest.cs
- VodovozBusiness/Domain/Cash/CashRequestSumItem.cs
- VodovozBusiness/Domain/Cash/Expense.cs
- VodovozBusiness/HibernateMapping/Cash/CashRequestMap.cs
- VodovozBusiness/HibernateMapping/Cash/CashRequestSumItemMap.cs
- VodovozBusiness/HibernateMapping/Cash/ExpenseMap.cs
- VodovozViewModels/ViewModels/Cash/CashRequestItemViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Добавлена кнопка Выдать частично и поле для ввода частичной суммы
Добавлена логика для выдачи сумм в зависимости от чекбокса дающего выдавать средства без пересогласования
> Задача 3210.2 Изменения в работе заявки на выдачу ДС

- VodovozViewModels/Journals/JournalViewModels/Cash/CashRequestJournalViewModel.cs
Создано право на то чтобы видеть все заявки на выдачу Д/C внутри своего подразделение:
"Заявки на выдачу Д/C.Доступ.Просмотр заявок своего подразделения"
Изменено поведение фильтра - всем у кого стоит это право установлено ограничение для выборки заявок на ДС из собственного подразделения
> Задача 3210.3 Право на просмотр заявок на выдачу ДС

- Vodovoz/ViewModels/Mango/Talks/CounterpartyTalkViewModel.cs
Добавлен диалог с предупреждением о клиенте розницы при создании заказа из диалога звонка
> Задача 3318 Сообщение о клиенте розницы при создании заказа из диалога звонка

- Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
Исправление даты создания путевого листа
> Задача 3310 Исправления даты создания ПЛ

- Vodovoz/ReportsParameters/Production/ProducedProductionReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Production.ProducedProductionReport.cs
В отчете по производству добавлена возможность выбрать год, добавлен выпадающий список с годами +- 10 лет. По умолчанию выбирается предыдущий месяц.
> В отчете по производству добавлен выпадающий список с годами

- Vodovoz/MainWindow.cs
https://github.com/QualitySolution/QSProjects/pull/260
После принятия этого ПР
> Принимать после того, как примут на qsproject

- Vodovoz/Representations/RouteListsVM.cs
- VodovozBusiness/Parameters/RouteListParametersProvider.cs
- VodovozBusiness/Services/IRouteListParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
I-3299 При переводе МЛ из статуса Подтвержден в статус На погрузке добавлена проверка:
1. Есть ли в МЛ товары ИМ
2. Есть ли данные ТМЦ на остатках Склада, с которого будут грузиться данные МЛ (если выбрана Касса Софийская - Склад Софийская, если Парнас - склад Парнас)
3.1. Если в наличии все есть, отправляем На погрузку
3.2. Если каких-либо ТМЦ не хватает, выдаем сообщение пользователю:
"В наличии на складе Склад Софийская нет следующих товаров:
Заказ 111222 Морковка 1 шт.
Заказ 111222 Яблоко 2 шт. (нужное количество есть на других складах: Склад ИМ Обуховская 5 шт.)
Заказ 111222 Груша 3 шт. 
Все-равно отправить МЛ на погрузку?"
-Да- -Нет-"
4.1. Если Да - меняем статус МЛ на На погрузку
4.2. Если Нет - не меняем статус
> Проверка наличия товаров ИМ на складе при переводе МЛ из статуса Подтвержден в статус На погрузке

- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Возврат на пересогласование при дозакрытии частичной выдачи ДС
> Хотфикс выдачи ДС

- Vodovoz/Dialogs/Client/DeliveryPointDlg.cs
I-3240 Сброс дома / координат при изменении улицы в точке доставки. Сброс координат, когда не найден дом.
> Сброс дома / координат при изменении улицы в точке доставки. Сброс координат, когда не найден дом

- Vodovoz/Dialogs/DocumentDialogs/IncomingWaterDlg.cs
- Vodovoz/gtk-gui/Vodovoz.IncomingWaterDlg.cs
I-3349 Изменён способ выбора номенклатур на EntityViewModel - SelectorFactory (раньше грузились сразу все >40k записей)
> Уменьшение времени открытия "номенклатур" через "продукт производства"

- Vodovoz/ViewModels/Goods/NomenclatureViewModel.cs
I-3307 Неправильное отображение поля "Кем создана" карточки ТМЦ
> Правка отображения поля "Кем создана" в карточкие ТМЦ

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
Reverts VodovozOrganization/Vodovoz#290
Ошибся, не увидел ветку, откатываю
> Revert "Хотфикс 3361 отображение времени в отчёте по изменениям"

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
Изменена отображаемая дата доставки на дату смены статуса заказа, когда заказ первый раз перешел в статус "Доставлен".
> Хотфикс 3375 - Исправлены дата/время доставки в отчете по изменениям заказов

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
Reverts VodovozOrganization/Vodovoz#297
> Revert "Хотфикс 3375 - Исправлены дата/время доставки в отчете по изменениям заказов"

- Vodovoz/Reports/Bottles/BottlesMovementReport.rdl
Правка Разницы между факт. и кассовыми в отёте по движению бутылей МЛ
> Хотфикс - Правка Разницы между факт. и кассовыми в отчёте по движению бутылей МЛ

- Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- VodovozBusiness/Domain/Service/BaseParametersServices/BaseParametersProvider.cs
- VodovozBusiness/Services/IDefaultDeliveryDayScheduleSettings.cs
- VodovozBusiness/VodovozBusiness.csproj
- VodovozViewModels/ViewModels/Logistic/DriverDistrictPrioritySetViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DriverWorkScheduleSetViewModel.cs
+переименовал класс с настройками
> Фикс ошибки с LazyLoading в автоформировании

- Vodovoz/Dialogs/Cash/CashRequestItemView.cs
- Vodovoz/Dialogs/Cash/CashRequestView.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.Cash.CashRequestItemView.cs
- VodovozViewModels/ViewModels/Cash/CashRequestItemViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Заменена логика сохранения строки суммы заявки на выдачу ДС на логику возврата в диалог заявки на выдачу ДС.
Изменено название и иконка кнопки сохранения строки суммы заявки на выдачу ДС.
Исправлен баг недоступности кнопки редактирования строки суммы заявки на выдачу ДС
> Задача 3239 исправление удаления суммы из новой заявки на выдачу ДС

- Vodovoz/Additions/AuthorizationService.cs
- Vodovoz/ErrorHandlers.cs
- VodovozBusiness/Domain/Employees/Employee.cs
Исправлен метод создания пользователя: заменена отправка смс на отправку почты
Добавлена валидация поля Электронной почты для сотрудника
Изменен текст сообщения об ошибке, сообщавший об отправки смс, вместо отправки почты
> Исправляет отправку СМС вместо Email при создании пользователя

- Vodovoz/Additions/AuthorizationService.cs
- Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
При попытке сброса пароля пользователю у которого нет Email больше не сбрасывается пароль
> Фикс попытки сброса пароля при незаполненном поле Email сотрудника

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Revert не стоило конечно делать, когда решил поправить ошибку.
> Добавлена проверка прав на чекбокс "оплата после отгрузки"

- Vodovoz/Reports/Logistic/CarsExploitationReport.rdl
Сначала по типу использования авто,
потом если есть по id вида наёмного авто
> Изменил сортировку

- Vodovoz/Reports/Store/StockProductionMovements.rdl
- Vodovoz/Reports/Store/StockShipmentMovements.rdl
- Vodovoz/Reports/Store/StockWaterMovements.rdl
- Vodovoz/ReportsParameters/Store/StockMovements.cs
- Vodovoz/gtk-gui/Vodovoz.Reports.StockMovements.cs
Добавлено поле, позволяющее выбрать способ сортировки данных в отчете (можно перетаскивать местами меняя способ сортировки)
> Задача 3324 фильтр сортировки результатов выборки отчета

- VodovozBusiness/Domain/Service/BaseParametersServices/SubdivisionParametersProvider.cs
- VodovozBusiness/Services/ISubdivisionService.cs
- VodovozViewModels/ViewModels/Users/UserSettingsViewModel.cs
Для сотрудников дистрибуции в "Настройка пользователя" блок - "Настройки для розницы", будет отображаться только тем у кого есть право на модуль "Розница".
> Adding rules to retail for usersettings

- Vodovoz/Reports/Orders/OrdersByAllDistrict.rdl
- Vodovoz/Reports/Orders/OrdersByDistrict.rdl
Удалось сократить время выполнение полугодового отчета до 21 секунды
> Задача 3309 - оптимизация запроса в отчете по районам

- Vodovoz/Reports/Orders/OrdersByAllDistrict.rdl
Увеличено время выполнения запроса
> Задача 3309 фикс таймаута

- Services/Library/OnlineStoreImportService/CategoryImporter.cs
- Vodovoz/Dialogs/Goods/NomenclatureDlg.cs
- Vodovoz/Dialogs/Goods/ProductGroupDlg.cs
- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/Reports/Documents/AssemblyList.rdl
- Vodovoz/Reports/Documents/SeparateAssemblyList.rdl
- Vodovoz/Reports/Logistic/ClosedRouteList.rdl
- Vodovoz/Reports/Logistic/RouteList.rdl
- Vodovoz/Reports/RouteList/CarLoadDocument.rdl
- Vodovoz/Reports/Store/CarLoadDocument.rdl
- Vodovoz/ViewModels/Goods/NomenclatureViewModel.cs
- Vodovoz/ViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentViewModel.cs
- Vodovoz/Views/Goods/NomenclatureView.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.Goods.ProductGroupDlg.cs
- VodovozBusiness/Domain/Goods/ProductGroup.cs
- VodovozBusiness/EntityRepositories/Orders/OrderSingletonRepository.cs
- VodovozBusiness/HibernateMapping/Goods/ProductGroupMap.cs
- VodovozViewModels/ViewModels/ExportImportNomenclatureCatalogViewModel.cs
3301-Переделан устаревший функционал, убран признак Интернет-магазин из групп товаров, проверки по нему заменены на проверку наличия ссылки на справочник интернет магазина.
> 3301-проверка по признаку Интернет-магазин из групп товаров заменена на ссылку справочника ИМ

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Добавлена колонка в таблицу с Товарами - порядковый номер товара в таблице
> Задача 3354

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
- Vodovoz/Reports/Logistic/CarsExploitationReport.rdl
- Vodovoz/ReportsParameters/Logistic/CarsExploitationReport.cs
- Vodovoz/gtk-gui/Vodovoz.CarsDlg.cs
Добавил возможность редактировать привязанного водителя в карточке авто + добавил столбик с этим водителем и обслуж. частью города автомобилем в отчёт
> Переименовал Ходки в Рейсы, сделал скрытые ненужных колонок, добавил выделение выходных в столбиках жирным шрифтом

- Vodovoz/Reports/Sales/SalesByDiscountReport.rdl
Теперь отчет правильно принимает конечную дату интервала выборки
Добавлена колонка дата доставки
> Хотфикс 3404 Исправлен баг с датой передаваемой в отчет по скидкам

- Vodovoz/Reports/Logistic/RouteList.rdl
Также добавлено округление тоннажа.
Ненужный перенос был добавлен в этом коммите https://github.com/VodovozOrganization/Vodovoz/commit/aa82d37d277f0d60f26d78b61a00830bd5449b1d#
> Убрана ошибка в печатной форме МЛ

- Vodovoz/MainWindow.cs
- Vodovoz/Program.cs
- VodovozBusiness/Tools/Validation/PasswordValidationSettingsFactory.cs
- VodovozBusiness/VodovozBusiness.csproj
Создал фабрику настроек для этого валидатора
> Добавил проброс валидатора паролей в ChangePassword

- Vodovoz/Dialogs/Cash/CashRequestView.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.Cash.CashRequestView.cs
- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Добавлен комбобокс выбора текущей роли, убраны виджеты для запоминания роли в статических полях VM
Во вью не гаммовские виджеты, видимость которых зависит от текущей роли, заменены на аналоги из гаммы для добавления биндов.
> Работа с заявками ДС при наличии нескольких ролей

- VodovozBusiness/Domain/Logistic/Car.cs
Установить "раскат" можно только если выбран автомобиль водителя
> Ограничение установки чекбокса "Раскат"

- Vodovoz/Reports/Payments/PaymentsFromTinkoffReport.rdl
- Vodovoz/ServiceDialogs/PaymentsFromTinkoffParser.cs
- VodovozBusiness/Domain/Payments/PaymentByCardOnline.cs
- VodovozBusiness/Domain/Payments/PaymentsFromYookassaParser.cs
- VodovozBusiness/HibernateMapping/Payments/PaymentByCardOnlineMap.cs
- VodovozBusinessTests/Domain/Payments/PaymentFromTinkoffTests.cs
Добавил в сущность новый энам
Изменил логику парсера
Поменял отчет для сопоставления платежей по трем полям в заказе
> 3368 3369 Изменение оплат по картам онлайн и отчета

- Vodovoz/Additions/AuthorizationService.cs
- Vodovoz/Additions/IAuthorizationService.cs
- Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
Как мне кажется, логичнее менять пароль в БД в методе ResetPassword только после того, как успешно отослан пароль на почту (метод SendCredentialsToEmail юзает emailService).
> 3432 Запрос на смену пароля при сбросе через журнал сотрудников

- Vodovoz/Reports/Logistic/OrdersByDistrictsAndDeliverySchedules.rdl
Изменены условия выборки на условия используемые в формировании МЛ
Изменено сопоставление с координат на идентификаторы районов
> 3476 - Хотфикс дублирования строк в отчете "Заказы по районам и интервалам"

- VodovozBusiness/Domain/Client/Counterparty.cs
Добавлено название полей для корректного отображения в истории изменений
> Хотфикс Аннотации к полям

- Vodovoz/Views/Client/SupplierPricesWidgetView.cs
- VodovozBusiness/Domain/Client/Counterparty.cs
Добавлен поиск по номеру номенклатуры
Исправлена проблема при которой после ввода в строку поиска исчезало содержимое таблицы
> Задача 3440 Поиск в ценах поставщика

- Vodovoz/Reports/Documents/Torg12.rdl
> Добавил округление суммы в документе Торг12

- Vodovoz/Reports/Logistic/OrdersByDistrictsAndDeliverySchedules.rdl
Убраны нули в столбцах с количеством бутылей после запятой
Исправлено описание условий выборки в конце отчета
Исправлены интервалы выборки заказов
> Хотфикс отчета "Заказы по районам и интервалам"

- VodovozBusiness/Domain/Cash/CashRequest.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/CashRequestJournalViewModel.cs
При наличии права "Заявки на выдачу Д/С.Доступ.Просмотр заявок своего подразделения"
теперь поиск производится по подразделению автора заявки.
> Хотфикс: исправлена фильтрация заявок 

- VodovozBusiness/Parameters/DeliveryScheduleParametersProvider.cs
- VodovozBusiness/Parameters/IParametersProvider.cs
- VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- VodovozBusiness/Parameters/NomenclaturePlanParametersProvider.cs
- VodovozBusiness/Parameters/OrderParametersProvider.cs
- VodovozBusiness/Parameters/OrderPaymentSettings.cs
- VodovozBusiness/Parameters/OrganizationParametersProvider.cs
- VodovozBusiness/Parameters/ParametersProvider.cs
- VodovozBusiness/Parameters/ReportDefaultsProvider.cs
- VodovozBusiness/Parameters/RouteListParametersProvider.cs
- VodovozBusiness/Parameters/TabsParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
Добавлен интерфейс IParametersProvider
Изменено использование ParametersProvider на IParametersProvider
> Техническое: Абстракция IParametersProvider

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
Установлен 30 минутный таймаут
> Хотфикс: увеличение ограничения времени на формирования отчета по изменениям при доставке

- Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Orders.NomenclaturePlanReport.cs
- VodovozViewModels/Journals/JournalViewModels/Orders/NomenclaturesPlanJournalViewModel.cs
В отчёте по мотивации КЦ добавлен фильтр по статусу сотрудника, возможность выбора нескольких номенклатур и сотрудников клавишами Shift и Control, дополнено описание.
В журнал План продаж для КЦ добавлено ограничение на редактирование.
> Улучшения и доработки журнала План продаж для КЦ и отчёта по мотивации КЦ

- Services/Application/VodovozSmsPaymentService/VodovozSmsPaymentService.csproj
Фикс версии пакета конфигурации
Удаление лишнего пакета Nini
> Техническое: Фикс SmsPaymentService

- prepare_source.sh
Отсортировал, как в Smart-Git, добавил отсутствующий репозиторий для стягивания
> Техническое: починка скрипта подготовки исходных кодов для разработки

- Prepare-Source.ps1
> Техническое: Prepare-Source для Windows

- Vodovoz/Reports/Complaints.rdl
В печатной форме отображался только 1 виновник, когда в ДВ их больше 1
> 3388-Отображение всех виновных в печатной форме рекламаций

- VodovozBusiness/Domain/BaseParameter.cs
- VodovozBusiness/HibernateMapping/BaseParameterMap.cs
- VodovozBusiness/Parameters/SingletonParametersProvider.cs
CachedTime проставляется извне, возможно стоит записывать её прямо в конструкторе
> Добавлена возможность кешировать параметры базы

- Vodovoz/gtk-gui/Vodovoz.CarsDlg.cs
> Часть задачи 3537: Добавления элемента GUI в карточку автомобиля

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
- VodovozBusiness/Domain/Logistic/Car.cs
- VodovozBusiness/HibernateMapping/Logistic/CarMap.cs
Маппинг поля и добавление отображения в карточку автомобиля
> Часть задачи 3537: подключение параметра

- Vodovoz/Reports/Logistic/CarsExploitationReport.rdl
Добавлена колонка с порядковым номером
> Часть задачи 3537: изменения отчета Аналитика Эксплуатации ТС

- Vodovoz/Reports/Logistic/OrdersByDistrictsAndDeliverySchedules.rdl
- Vodovoz/ReportsParameters/Logistic/OrdersByDistrictsAndDeliverySchedulesReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.OrdersByDistrictsAndDeliverySchedulesReport.cs
Добавлен фильтр по части города, выбор даты заменён на выбор периода дат, добавлена колонка с датой в отчёт
> 3538 - Хотфикс: Добавлены фильтры в отчёт Заказы по районам и интервалам доставки

- Vodovoz/Reports/Logistic/GeneralSalaryInfoReport.rdl
- Vodovoz/ReportsParameters/Logistic/GeneralSalaryInfoReport.cs
- Добавлен столбик с датой первого МЛ
- Переименование категории сотрудника в "КС"
- Переименование "Управляет" в "КТС" и использование сокращений + отображение раската
- Отчет формируется по предыдущий день, если месяц и год формирования совпадает с выбранным месяцем и годом
- Округление ячеек с ЗП до 0 знака
- Изменения в шапке таблицы и отчета - объединение ячеек, перемещение, размер и прочее
> 3536 Визуальные правки отчета и данных отчета

- .editorconfig
Табы, LF, кодировка - для всех файлов
Для C#:
обязательные скобки
скобки с новой строки
> Техническое: настройки редактора кода

- Vodovoz/Reports/Orders/OrderChangesReport.rdl
- VodovozBusiness/Domain/Logistic/RouteListItem.cs
Блокировка изменений TimeDelivered
Удаление shipping из запроса
> Добавление TimeDelivered из Order

- VodovozBusiness/Domain/Logistic/RouteListItem.cs
- VodovozBusiness/HibernateMapping/Logistic/RouteListItemMap.cs
Ограничена возможность изменения адреса МЛ из 2х разных мест одновременно
> Задача 3435: Ошибка при переносе и отмене адреса МЛ

- Vodovoz/Reports/Logistic/GeneralSalaryInfoReport.rdl
- Vodovoz/ReportsParameters/Logistic/GeneralSalaryInfoReport.cs
- Добавлен столбик с датой первого 
- Переименование категории сотрудника в "
- Переименование "Управляет" в "КТС" и использование сокращений + отображение 
- Отчет формируется по предыдущий день, если месяц и год формирования совпадает с выбранным месяцем и 
- Округление ячеек с ЗП до 0 
- Изменения в шапке таблицы и отчета - объединение ячеек, перемещение, размер и прочее
> Хотфикс 3536 Правки отчета по основной информации о ЗП 

- Vodovoz/Infrastructure/DatabaseInfo.cs
Добавлено отсутствующее свойство
> Техническое: Реализация интерфейса IDatabaseInfo

- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- Vodovoz/ViewModels/Logistic/RouteListAnalysisViewModel.cs
- Vodovoz/Views/Logistic/RouteListAnalysisView.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
> 3522 Предварительный расчет ЗП в МЛ

- Vodovoz/ErrorHandlers.cs
- Vodovoz/Program.cs
Добавлено окно ошибки при таймауте выполнения запроса приложением.
> Обработка таймаута

- Services/Library/EmailService/EmailManager.cs
- VodovozBusiness/Domain/StoredEmails/StoredEmail.cs
- VodovozBusiness/HibernateMapping/StoredEmails/StoredEmailMap.cs
Убраны не используемые свойства у StoredEmail
> Техническое: Задача 3450

- Vodovoz/Views/Logistic/DriversInfoExportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Logistic.DriversInfoExportView.cs
- VodovozViewModels/ViewModels/Logistic/DriversInfoExportViewModel.cs
> Добавлен спасательный круг в экспорт по водителям

- VodovozBusiness/HibernateMapping/Logistic/RouteListMap.cs
Вместо AsList теперь используется OrderBy
> Техническое: задача 3378 - изменен параметр маппинга списка адресов МЛ

- Vodovoz/Dialogs/Employees/EmployeeDlg.cs
- Vodovoz/gtk-gui/Vodovoz.EmployeeDlg.cs
- VodovozBusiness/Domain/Employees/Employee.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverDistrictPrioritySet.cs
- VodovozBusiness/HibernateMapping/Employees/PersonnelMap.cs
- VodovozBusiness/HibernateMapping/Logistic/Drivers/DriverDistrictPrioritySetMap.cs
- VodovozViewModels/Journals/JournalViewModels/Logistic/DistrictsSetJournalViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DistrictsSetActivationViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DriverDistrictPrioritySetViewModel.cs
Добавлены поля дата создания и последнего изменения для версий приоритетов районов доставки
Теперь активирование версии приоритетов районов происходит по отдельной кнопке
Теперь активирование версии приоритетов районов доставки могут активировать только те сотрудники у которых есть право "Возможность активировать версии приоритетов районов доставки"
> Задача 3542: Доступ к версиям приоритетов доставки водителей

- VodovozBusiness/Domain/WageCalculation/RatesLevelWageParameterItem.cs
при добавлении ставок сотруднику появлялась ошибка
> Исправление ошибки при сохранении добавленных ставок зп у сотрудника

- Vodovoz/MainWindow.cs
- Vodovoz/Reports/Logistic/DeliveryTime.rdl
- Vodovoz/ReportsParameters/Logistic/DeliveryTimeReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.DeliveryTimeReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.OrdersByDistrictsAndDeliverySchedulesReport.cs
Также исправил немного вью другого отчёта OrdersByDistrictsAndDeliverySchedulesReport
> Заменил виджет выбора частей города, добавил выбор принадлежности МЛ, заменил виджет выбора времени

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Complaints.ComplaintView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Complaints.CreateComplaintView.cs
Открытие сущностей заказа и клиента в рекламациях
> Добавление журнала рекламаций в журнал контрагентов

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
- Vodovoz/gtk-gui/Vodovoz.CarsDlg.cs
- VodovozBusiness/Domain/Logistic/Car.cs
- VodovozBusiness/HibernateMapping/Logistic/CarMap.cs
Добавил новое поле enum и маппинг к нему
Добавил новые элементы в карточу авто и бинды
> 3563 Тип раскатного авто

- VodovozBusiness/Domain/Employees/Employee.cs
В карточке сотрудника (водителя) переименованы пункты принадлежности ТС.
Пункт "Наш" соответствует "Компании ТС"
Пункт "Частник" соответствует "Личное ТС"
> Задача 3487: Переименование типов транспортных средств

- .editorconfig
Управляющие конструкции слитно с открывающей скобкой
Методы слитно с открывающей скобкой
Табы только для C#
Без пробелов между выражением и круглыми скобками
Унификация встроенных типов
Приватные поля с подчеркиванием
> Техническое: Актуализация принятых правил

- Vodovoz/Reports/Bottles/ExtraBottlesReport.rdl
Изменена формула подсчета фактической тары в отчете по лишней таре.
Теперь учитываются "Фактическое количество бутылей по акции"
> Задача 3485: Исправление выборки

- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentView.cs
Изменение алгоритма пересчета количества автоматически загружаемых товаров
> Хотфикс: Изменение формирования документов погрузки

- VodovozBusiness/Domain/Employees/Employee.cs
Заменены названия на следующие:
Компании ТС - Управляет ТС компании
Раскат - Управляет ТС в раскате
Личное ТС - Управляет ТС личным
> Задача 3487: Изменение названий принадлежностей водителей

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePayment.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForDebt.cs
- VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForPayment.cs
- VodovozBusiness/HibernateMapping/Order/OrderMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForDebtMap.cs
- VodovozBusiness/HibernateMapping/Order/OrdersWithoutShipment/OrderWithoutShipmentForPaymentMap.cs
Удален IsForRetail из заказов и маппинга
> Техническое: задача 3300

- Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
- Vodovoz/Reports/Cash/CashBookOrganisations.rdl
- VodovozViewModels/Journals/JournalNodes/OrganizationCashTransferDocumentJournalNode.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/OrganizationCashTransferDocumentJournalViewModel.cs
- VodovozViewModels/ViewModels/Cash/OrganizationCashTransferDocumentViewModel.cs
Добавлен вывод комментария в журнал, исправлено время операции, исправлен отчёт Кассовая книга (по организациям)
> Исправления к задаче 3379 - Документы перемещения дс по юр.лицам

- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentView.cs
- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
Теперь валидация учитывает все позиции документа погрузки для одной номенклатуры
> Хотфикс: исправлена валидация количества товара в документе погрузки

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- VodovozBusiness/Domain/Employees/PremiumRaskatGAZelle.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/HibernateMapping/Employees/PremiumBaseMap.cs
- VodovozBusiness/Models/PremiumRaskatGAZelleWageModel.cs
Добавлен расчет пересчитанного километража при закрытии МЛ с раскатным авто. RecountMileage() вынес в RouteList. Поправлена проверка необходимости автопремии (в том числе проверка на газели)
> Расчет пересчитанного километрожа при закрытии МЛ с раскатным авто

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
- VodovozBusiness/Parameters/OrganizationParametersProvider.cs
- VodovozBusiness/Services/IOrganizationParametersProvider.cs
Добавил принудительную инициализацию клиента и текущего договора при обновлении договора
> Для налички теперь выбирается новая организация

- VodovozBusiness/Domain/Orders/Order.cs
В Order было 2 проверки на дату доставки в валидации, оставил одну.
> Техническое: Убрана лишняя проверка даты доставки заказа

- Services/Application/VodovozDeliveryRulesService/DTO/WeekDayDeliveryInfoDTO.cs
- Services/Application/VodovozDeliveryRulesService/DeliveryRulesService.cs
- Vodovoz/Configuration/ApplicationConfigurator.cs
- Vodovoz/Dialogs/Sale/DeliveryPriceRuleDlg.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.Sale.DeliveryPriceRuleDlg.cs
- VodovozBusiness/Domain/Goods/Nomenclature.cs
- VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/Sale/DeliveryPriceRule.cs
- VodovozBusiness/Domain/Sale/District.cs
- VodovozBusiness/Domain/Sale/IDeliveryPriceRule.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/WageRate.cs
- VodovozBusiness/Domain/WageCalculation/WageRateTypes.cs
- VodovozBusiness/Tools/Orders/OrderStateKey.cs
- VodovozBusinessTests/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationServiceTests.cs
Внес его в правила платной доставки;
Добавил его в ставки;
Подкинул в тесты;
Задача должна пойти сразу в сборку, чтобы попасть в обновление
> Добавил новый объем тары 0.5л

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- Vodovoz/Views/Logistic/RouteListsOnDayView.cs
- VodovozViewModels/Journals/JournalViewModels/ComplaintsJournalViewModel.cs
Задача должна пойти в обновление также
> Исправление фильтра контрагента и сводки МЛ

- VodovozBusiness/Domain/Employees/PremiumRaskatGAZelle.cs
- VodovozBusiness/HibernateMapping/Employees/PremiumBaseMap.cs
- VodovozBusiness/Models/PremiumRaskatGAZelleWageModel.cs
Необходимо хранить и выводить номер МЛ, по которому выдана премия. Исправления в условиях проверки необходимости выдачи автопремии (поиск наличия премии не по дате МЛ, а по текущей дате)
> 3564 - Доработки по уточнениям задачи по автопремиям

- VodovozBusiness/Domain/Logistic/RouteListItem.cs
- VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListItemRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListItemRepository.cs
Перенёс запрос энамов из репозитория в сущность
> ЗП теперь не считается для недовезённых адресов

- VodovozBusiness/Tools/Orders/OrderStateKey.cs
Теперь берётся актуальная сумма строки заказа, а не планируемая
> Изменение проверки на нулевую сумму заказа для добавления документов

- Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
Фикс типа объединения строк запроса
> Хотфикс: журнал розницы

- Vodovoz/Reports/Employees/ForwarderWage.rdl
Переделал выборку пустых и полных бутылей, т.к. данные из операций не отображают полную картину
> Фикс отчета по ЗП экспедиторов

- Vodovoz/Additions/Printing/EntitiyDocumentsPrinter.cs
- Vodovoz/Dialogs/Logistic/PrintRouteDocumentsDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/HibernateMapping/Logistic/RouteListMap.cs
После принятия модели, принять этот
> Добавление времени печати МЛ

- VodovozViewModels/ViewModels/Complaints/ComplaintFilesViewModel.cs
- VodovozViewModels/ViewModels/FilesViewModel.cs
Дополнил сообщения при попытке прикрепить файл с большим именем в рекламациях
> Обновил сообщение в рекламациях

- Vodovoz/MainWindow.cs
- Vodovoz/Reports/Logistic/AddressesOverpaymentsReport.rdl
- Vodovoz/ReportsParameters/Logistic/AddressesOverpaymentsReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.AddressesOverpaymentsReport.cs
Добавил столбец с id заказа и ФИО логиста
Изменил ориентацию отчета на альбомную
Добавил энтри для логиста, в связи с чем переименовал то, что относится к водителю (в отчете не стал менять empl_name на driver_name etc)
Расширил описание
> 3543 Дополнительные фичи в отчет по переплатам

- Vodovoz/Reports/Sales/PlanImplementationByEmployeeReport.rdl
- Vodovoz/Reports/Sales/PlanImplementationFullReport.rdl
На отчет сотрудника добавил столбец "чистый забор" и "доп. продажи"
На общий отчет - только доп. продажи
> 3568 Дополнения к отчету по выполнению плана

- VodovozBusiness/Domain/Documents/InventoryDocument.cs
- VodovozBusiness/Domain/Documents/InventoryDocumentItem.cs
Добавил валидацию на длину комментария номенклатуры инвентаризации и самой инвентаризации
> 3491 Проверка на длину комментариев документа инвентаризации

- VodovozBusiness/Domain/Employees/Employee.cs
- VodovozBusiness/Domain/Employees/Personnel.cs
Если при создании сотрудника-водителя стоит галочка на Разовый:
- сделать обязательным поле Водительское удостоверение
- убрать обязательность главного документа
> 3587 - Для разовых водителей обязательное поле Водительское удостоверение, необязательное Главный документ

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
Поменял открытие журнала всех заказов клиента из его карточки, на открытие отдельной вкладки. Чтобы можно было открывать несколько разных журналов без переключения на уже открытый.
> Изменил открытие журнала заказов из диалога контрагента

- Vodovoz/SidePanel/InfoViews/UndeliveredOrdersPanelView.cs
Добавлено значение по умолчанию для отсутствующего виновного
> Хотфикс: исправлена боковая панель журнала недовозов

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Исправлена ошибка NullReference при отображении Заказа Контрагента
> Хотфикс: Исправлена ошибка в диалоге заказа

- Vodovoz/Reports/Logistic/GeneralSalaryInfoReport.rdl
- Vodovoz/ReportsParameters/Logistic/GeneralSalaryInfoReport.cs
В отчёте Основная информация по ЗП исправлен диапазон дат, добавлена планируемая зп экспедитора, для незакрытых МЛ добавлена планируемая пустая тара и кол-во бутылей с водой из заказа
> 3588 - Доработки и правки в отчёте Основная информация по ЗП

- VodovozViewModels/ViewModels/Employees/PremiumViewModel.cs
- VodovozViewModels/VodovozViewModels.csproj
Протестировал, VodovozViewModels больше не залетает в gui.stetic
> 3609 - в проекте VodovozViewModel убраны ссылки на QSProjectsLib, QSBusinessCommon

- Vodovoz/MainWindow.cs
- Vodovoz/ReportsParameters/Employees/EmployeesReport.cs
- Vodovoz/ReportsParameters/Logistic/AddressesOverpaymentsReport.cs
- Vodovoz/ReportsParameters/Logistic/GeneralSalaryInfoReport.cs
- Vodovoz/ReportsParameters/Orders/NomenclaturePlanReport.cs
Заменено создание окон информации в отчетах: заменено использование Gtk на InteractiveService.ShowMessage
> Техническое: Задача 3612 замена окон информации

- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
В ячейках данного показателя отображаются сокращенные названия событий по автомобилю согласно датам событий.
> 3585 - События ТС добавлены в аналитику ТС

- Vodovoz/Infrastructure/Mango/MangoManager.cs
Добавил выход из метода если текущий разговор null (возможно произошел разрыв связи)
> Попытка устранить nullRefException

- VodovozViewModels/ViewModels/Reports/DeliveryAnalyticsViewModel.cs
Завершение рабочей версии вкладки отчета "аналитика объёмов доставки". В рабочую был залит с косяками, т.к. нужно было его просто залить. Здесь уже всё исправлено
Фикс выборки бутылей, сортировки и работы фильтров
> 3580 - Фикс аналитики объемов доставки 

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Сменил событие для подписки, удалил старый код, который вообще имел неверную логику. Размер колонок становится актуальным только после SizeAllocated
Неверная подписка на событие также осталась в OrderEquipmentView, но там я не проверил, наезжает или нет.
> 3459 Ввод количества по номенклатуре не съезжает влево

- VodovozViewModels/ViewModels/Reports/DeliveryAnalytics/DeliveryAnalyticsReportNode.cs
- VodovozViewModels/ViewModels/Reports/DeliveryAnalyticsViewModel.cs
- VodovozViewModels/ViewModels/Reports/OrderAnalyticsReportViewModel.cs
3580 - Фикс аналитики объемов доставки
Исправление фильтрации, выборки и внутренних итогов отчёта
> 3580 Аналитика объемов доставки в мастер

- Vodovoz/Views/Reports/DeliveryAnalyticsReportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Reports.DeliveryAnalyticsReportView.cs
- VodovozViewModels/ViewModels/Reports/DeliveryAnalyticsViewModel.cs
Добавление строки прогресса. Изменение размеров фильтров
> 3580 Фикс размеров и добавление строки прогресса

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozBusiness/Domain/Documents/DriverTerminalTransferDocument.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- VodovozBusiness/EntityRepositories/Store/CarLoadDocumentRepository.cs
- VodovozBusiness/HibernateMapping/Documents/DriverTerminalTransferDocumentMap.cs
- VodovozBusiness/VodovozBusiness.csproj
Добавлен документ перемещения терминала
Изменен алгоритм подсчета терминалов
> Задача 3591: Добавлена обработка передачи терминала между адресами

- Vodovoz/Views/Reports/CarsExploitationReportView.cs
- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Добавлены запросы для предзагрузки необходимых данных
Изменены показатели, в которых была предварительная оптимизация
> Техническое: оптимизация отчета по эксплуатации ТС

- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Исправлен NullRef при не выставленном районе в точке доставки
> Фикс аналитики ТС

- Vodovoz/JournalViewModels/EmployeesJournalViewModel.cs
Проблема была в том, что UoW.GetById получал сущность без обновленного email, хотя в базе обновление происходило. Сначала просто сделал еще один вызов GetById через новый uowWithoutRoot, что сработало, но потом вспомнил про session.refresh
> 3387 Исправил сброс пароля при добавлении email

- Vodovoz/Reports/ServiceCenter/EquipmentReport.rdl
В отчёте по оборудованию убран уникальный номер в переделах дня и добавлены отступы
> 3615 - В отчёте по оборудованию убран уникальный номер в переделах дня

- Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
- Vodovoz/Dialogs/Logistic/PrintRouteDocumentsDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Переделал на запрос из репозитория
История печати добавляется, если в списке печати был указан МЛ, либо "Все"
> 3599 Доработки истории печати МЛ

- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Добавлена загрузка всех адресов МЛ (не загружались)
> Техническое: исправлен метод GetRouteListByOrder в репозитории МЛ

- Prepare-Source.ps1
- Vodovoz/Views/Reports/DeliveryAnalyticsReportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Reports.DeliveryAnalyticsReportView.cs
- VodovozViewModels/ViewModels/Reports/DeliveryAnalyticsViewModel.cs
Reverts VodovozOrganization/Vodovoz#670
> Revert "merge master to develop"

- Vodovoz/Reports/Documents/Bill.rdl
- Vodovoz/Reports/Documents/BillWithoutShipmentForAdvancePayment.rdl
- Vodovoz/Reports/Documents/BillWithoutShipmentForDebt.rdl
- Vodovoz/Reports/Documents/BillWithoutShipmentForPayment.rdl
Стока договора теперь длиннее в счетах
> Хотфикс: строка договора в счетах

- Vodovoz/JournalViewModels/PaymentsJournalViewModel.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Payments/Payment.cs
Удалил ненужное создание операции прихода при отмене оплаченного заказа по безналу;
Добавил в журнал платежей для конечной даты фильтра 23:59:59;
+ "косметика";
> Фикс возврата платежа при отмене оплаченного заказа по безналу 

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Не вырезали непроверенную задачу из develop, попала в сборку
> Вырезал задачу

- VodovozViewModels/ViewModels/Reports/DeliveryAnalyticsViewModel.cs
Изменил стетик, чтобы он собирался и также изменил вьюмодель, чтобы отображались сначала все галочки
> Фикс: изменение стетика и вьюмодели отчёта аналитики доставки

- Vodovoz/Reports/Documents/ShetFactura2017Edition.rdl
- Vodovoz/Reports/Documents/UPD2017Edition.rdl
- Vodovoz/Vodovoz.csproj
- VodovozBusiness/Domain/Orders/Documents/ShetFacturaDocument.cs
- VodovozBusiness/Domain/Orders/Documents/SpecialUPDDocument.cs
- VodovozBusiness/Domain/Orders/Documents/UPDDocument.cs
К старым версиям документов добавил приписку 2017Edition. Они будут использоваться в заказах с датой доставки меньше 01.07.2021
Почистил Vodovoz.csproj
> Изменил документы заказа: УПД (Также Особый УПД) и Счёт фактуру.

- VodovozBusiness/Domain/Orders/Order.cs
Добавил проверку на старую листовку при копировании строк оборудования из старого заказа
> Исправление добавления старой листовки в заказ

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- VodovozBusiness/Services/INomenclatureParametersProvider.cs
> dont add lucky pizza leaflet to order

- Vodovoz/ViewModels/AutoPaymentMatching.cs
- Vodovoz/ViewModels/PaymentLoaderViewModel.cs
- Vodovoz/Views/Payments/PaymentLoaderView.cs
- Перенес сохранение заказа из сопоставления платежей в метод по сохранению выгрузки;
- Добавил три попытки сохранения заказа;
- Добавил свойства для Sensitive трех кнопок, чтобы в различных состояниях они были не доступны;
> 3625 Решить проблему с выпиской. Сделано

- Vodovoz/Views/Reports/OrderAnalyticsReportView.cs
- VodovozViewModels/ViewModels/Reports/OrderAnalyticsReportViewModel.cs
Добавлены 3 столбика:
1. Общая сумма заказа
2. Сумма за бутыли 19 л
3. Средняя стоимость 19 л в заказе (сумма за 19л / кол-во 19л)
> 3652 - В аналитику заказов добавлены новые колонки

- Vodovoz/JournalViewers/Complaints/DriverComplaintReasonJournalFilterView.cs
> 3348: Фикс фильтра журнала причин рейтинга адреса МЛ водителями

- Services/Library/SmsPaymentService/SmsPaymentService.cs
Исправлено условие проверки количества оплаты для СМС оплаты
> Хотфикс: исправлена минимальная оплата по смс

- Services/Library/SmsPaymentService/DriverAPIHelper.cs
- Services/Library/SmsPaymentService/SmsPaymentService.cs
Сервис теперь отправляет оповещения и в WebAPI
> Включено оповещение нового сервиса водительского приложения

- Vodovoz/SidePanel/InfoViews/UndeliveredOrdersPanelView.cs
Периодически возникала ошибка при открытии журнала недовозов и панели недовозов
> 3176 - фикс коннекшена в недовозах

- Vodovoz/MainWindow.cs
- Vodovoz/Reports/Orders/FirstClients.rdl
- Vodovoz/ReportsParameters/Orders/FirstClientsReport.cs
Убрал открытие района из энтри
Фильтр показывает активные версии
Уменьшил шрифт, подвинул колонки, убрал лишний джойн (не по глазам был уже существовавший)
> 3638 Правки после теста

- VodovozBusiness/ConfigureDeletion.cs
Конфигурация удаления причин рекламаций водителей
> Техническое

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Комбо и дерево заполнялись отдельными запросами, переделал на один общий
> 2342 Основания для скидки в дереве товаров

- Vodovoz/gtk-gui/Vodovoz.Views.Reports.CarsExploitationReportView.cs
Изменена надпись чекбокса на "Сохранять с цветными ячейками (долго)"
> Переименование чекбокса

- VodovozBusiness/Domain/Orders/Order.cs
добавил проверку в валидацию на null уже внутри нового условия валидации
> 3183 Добавление проверки на null

- Vodovoz/Reports/Payments/PaymentsFromBankClientAllSubdivisionsReport.rdl
- Vodovoz/Reports/Payments/PaymentsFromBankClientBySubdivisionReport.rdl
слегка увеличена ширина и добавлен Paddin по бокам колонны
за счёт столбцов "№" "Распред. сумма на заказ" "Сумма заказа" "Статус оплаты"
> 3643 Доп. фикс разметки колонны "Клиент"

- Services/Application/VodovozDeliveryRulesService/DeliveryRulesInstanceProvider.cs
- Services/Application/VodovozDeliveryRulesService/DeliveryRulesService.cs
- Services/Application/VodovozDeliveryRulesService/Program.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozBusiness/Parameters/DeliveryRulesParametersProvider.cs
- VodovozBusiness/Services/IDeliveryRulesParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
- VodovozViewModels/Journals/JournalViewModels/Logistic/DistrictsSetJournalViewModel.cs
- Добавил параметр для остановки онлайнов;
- Добавил новые кнопки в журнал версий районов и новые права на них;
- Изменил код в службе под задачу, в двух запросах;
> 3660 Стоп онлайнов

- Services/WebApi/DriverAPI/Controllers/PushNotificationsController.cs
Добавлен номер заказа в PUSH сообщение
Добавлен лог для информации о том, что запущена отправка PUSH сообщения в эндпоинт
> Техническое (DriverAPI)

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- VodovozBusiness/EntityRepositories/Orders/OrderSingletonRepository.cs
- VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- VodovozBusiness/Services/INomenclatureParametersProvider.cs
Добавил текущую листовку(листовка магазина дочки-сыночки) в параметры, чтобы не добавлять их в новых заказах
> Обновление листовки к раздаче

- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Добавлен новый тип с полями OwnType и ExpirationDate
Добавлен новый запрос к базе (заполнение талона погрузки, поиск уже погруженных в других талонах), разделяющий номенклатуры по принадлежности и ExpirationDate
Добавлена логика заполнения списка номенклатур с делением из запроса
> 3600 Новый запрос в диалог талона погрузки

- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
Процедура UpdateAlreadyLoaded была до начала процедуры сохранения и меняла параметры энтити, из-за чего в валидацию поступали неверные данные и валидация выдавала ошибки, которые нельзя было поправить и сохранение не происходило
> 3600 Фикс процедуры сохранения

- Services/WebApi/DriverAPI.Library/Converters/OrderConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/DTOs/OrderDto.cs
- Services/WebApi/DriverAPI.Library/DTOs/RouteListAddressDto.cs
Исправлен подсчет бутылей на возврат в завершенном МЛ
Добавлено поле с планируемым к возврату количеством бутылей
> Правки DriverAPI

- Services/WebApi/DriverAPI.Library/Models/OrderModel.cs
Исправлено отсутствие доп. информации у заказа
> Хотфикс (DriverAPI)

- Services/WebApi/DriverAPI.Library/Models/IRouteListModel.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
- Services/WebApi/DriverAPI/Controllers/RouteListsController.cs
Добавлен эндпоинт возвращения в путь МЛ
> Правка DriverAPI

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
> Хотфикс: доступность виджетов ЗП в закрытии МЛ

- VodovozViewModels/ViewModels/Flyers/FlyerViewModel.cs
Делаем невозможным установку даты завершения раздачи листовки равной дате старта.
> Изменения по листовкам

- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/DTOs/CompletedRouteListDto.cs
- Services/WebApi/DriverAPI.Library/DTOs/OrdersReturnItemDto.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Добавлено оборудование на возврат в завершенный МЛ
> DriverAPI правки

- VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- VodovozBusiness/EntityRepositories/Orders/OrderSingletonRepository.cs
Переименовал пропущенные leaflet во flyer;
Добавил заказы в статусе Новый для выборки резерва по листовкам
> Доработки по листовкам

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/EntityRepositories/Counterparty/CounterpartyContractRepository.cs
- VodovozBusiness/EntityRepositories/Counterparty/ICounterpartyContractRepository.cs
В сеттеры DeliveryDate и PaymentByCardFrom добавлено обновление отображаемого контракта, если тот ещё не был создан.
Добавлен ErrorReporter в метод GetCounterpartyContract, если тот возвращает больше одного контракта (дубликат)
> 3366 Обновление даты договора при изменении даты доставки + ErrorReporter при возвращении нескольких договоров

- Services/Application/VodovozSmsPaymentService/Program.cs
- Services/Application/VodovozSmsPaymentService/SmsPaymentServiceInstanceProvider.cs
- Services/Library/SmsPaymentService/DTO/SmsPaymentDTO.cs
- Services/Library/SmsPaymentService/ISmsPaymentDTOFactory.cs
- Services/Library/SmsPaymentService/SmsPaymentDTOFactory.cs
- Services/Library/SmsPaymentService/SmsPaymentService.cs
- Services/Library/SmsPaymentService/SmsPaymentService.csproj
- VodovozBusiness/Models/IOrganizationProvider.cs
- VodovozBusiness/Models/OrderOrganizationProviderFactory.cs
- VodovozBusiness/Models/Stage1OrganizationProvider.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
- VodovozBusiness/Parameters/GeographicGroupParametersProvider.cs
- VodovozBusiness/Services/IGeographicGroupParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
- VodovozBusinessTests/SmsPaymentService/SmsPaymentItemDTOCalculateTests.cs
Код организации теперь отправляется в битрикс
Рефакторинг
> Если по смс оплачен самовывоз или заказ с точкой доставки на Севере или Востоке, то ставится организация Север.

- Vodovoz/Dialogs/CallTaskDlg.cs
- Vodovoz/Filters/GtkViews/DebtorsFilterView.cs
- Vodovoz/Filters/GtkViews/DeliveryPointJournalFilterView.cs
- Vodovoz/Filters/ViewModels/DebtorsJournalFilterViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
В коммитах все расписано вроде, поправил моменты после тестирования
> 3648 Доработки точки доставки

- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
Закэшировал получение права;
Убрал ненужное поле, которое есть в родительском классе
Подчистил юзинги
> Рефакторинг

- Services/UploadToServer.sh
Также вырезал устаревший OnlineStoreImport
> Исправил путь к манго в скрипте обновления сервисов

- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/DTOs/RouteListDto.cs
- Services/WebApi/DriverAPI.Library/Models/OrderModel.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
Фикс закрытия перенесенных адресов
Чистка кода
Добавлено поле с экспедитором
> Правки и фиксы DriverAPI

- Vodovoz/JournalViewers/Cash/UnclosedAdvancesView.cs
Форматирование кода
Пометка Obsolete (старый View)
> Техническое: рефакторинг UnclosedAdvancesView

- Vodovoz/Reports/Documents/UPD.rdl
Столбцы №п/п и "Код товара..." поменял местами и перенес №п/п по другую сторону от жирной границы, немного поменяв размеры других колонок. Уже протестировано и в рабочей
> Хотфикс: правки в УПД

- Vodovoz/Views/Employees/EmployeeView.cs
- VodovozViewModels/ViewModels/Employees/EmployeeViewModel.cs
- исправил получение хэша вкладки, чтобы в журнале открывалась новая по клику;
- добавил реализацию IEntityDialog во вью, для обновления поля национальность;
> 2792 Исправление недочетов

- Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
> Хотфикс: активные основания скидок в диалоге изменения заказа

- Vodovoz/ViewModels/Mango/Talks/CounterpartyTalkViewModel.cs
- Vodovoz/ViewModels/Mango/Talks/TalkViewModelBase.cs
- Vodovoz/ViewModels/Mango/Talks/UnknownTalkViewModel.cs
- Vodovoz/ViewModels/Mango/WidgetsModel/CounterpartyOrderViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Employees/EmployeesJournalViewModel.cs
Заменил дефолтные фабрики селекторов на именные;
Плюс избавился от ненужных зависимостей, которые будут резолвится автофаком
> Обновил CounterpartyOrderViewModel

- Prepare-Source.ps1
Данила случайно заревертил мой коммит, когда что то правил
> Вернул рекурсивное удаление папок

- Services/WebApi/DriverAPI.Library/Converters/ActionTypeConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/DeliveryPointConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/DriverComplaintReasonConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/OrderConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/PaymentTypeConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListAddressStatusConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListCompletionStatusConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/Models/DriverComplaintModel.cs
- Services/WebApi/DriverAPI.Library/Models/EmployeeModel.cs
- Services/WebApi/DriverAPI/Controllers/DriverComplaintsController.cs
- Services/WebApi/DriverAPI/Controllers/OrdersController.cs
- Services/WebApi/DriverAPI/Controllers/SmsPaymentsController.cs
- Services/WebApi/DriverAPI/Controllers/ValuesController.cs
Стиль кода
Добавил логгирование вызовов эндпоинтов для упрощения поиска по логу
> Рефакторинг DriverAPI

- VodovozBusiness/Domain/Payments/PaymentByCardOnline.cs
- VodovozBusiness/Domain/Payments/PaymentsFromYookassaParser.cs
Добавил новую строку для соответствия оплатам по смс из северной кассы
Изменил парсинг номера заказа для нее.
> Фикс парсинга оплат по карте из Юкассы

- Vodovoz/Reports/Logistic/OrderStatisticByWeek.rdl
В выборку недовозов добавлено подразделение "Логистический отдел Бокситогорская" (ЛО Бокс)
> Хотфикс: OrderStatisticByWeek.rdl

- Vodovoz/Dialogs/Logistic/CarsDlg.cs
> Исправление косяка в карточке авто

- VodovozViewModels/Infrastructure/Report/SelectableParametersFilter/SelectableParameterSet.cs
- VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
#	VodovozViewModels/ViewModels/Suppliers/WarehousesBalanceSummaryViewModel.cs
> merge master into dev

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Добавил проверку на нулл, падала при создании нового заказа
> 3694 Фикс нулл эксепшна в новом заказа

- Vodovoz/Dialogs/Client/DeliveryPointDlg.cs
- Vodovoz/Reports/Documents/Invoice.rdl
- Vodovoz/Reports/Documents/InvoiceBarter.rdl
- Vodovoz/Reports/Documents/InvoiceContractDoc.rdl
- Vodovoz/Reports/Logistic/RouteList.rdl
- Vodovoz/Views/Client/DeliveryPointView.cs
- Vodovoz/gtk-gui/Vodovoz.DeliveryPointDlg.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Client.DeliveryPointView.cs
- VodovozBusiness/Domain/Client/DeliveryPoint.cs
- VodovozBusiness/HibernateMapping/Counterparty/DeliveryPointMap.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
Добавлены дополнительные поля в диалоге точки доставки - "Обед" и "Доставка раньше интервала". 
Обед  - временной промежуток, 2 новых поля в точке доставки. Доставка раньше интервала - флажок.
Данная информация отражается в отчётах: Накладная (нал.), Накладная (безденежно), Накладная (Контрактная документация).
Также данная информация отражается в печатной форме МЛ (Только для печатной формы незакрытого МЛ).
> 3509 Дополнительные поля "Обед" и "Доставка раньше интервала" в диалоге точки доставки и отчётах.

- Vodovoz/Dialogs/CallTaskDlg.cs
- Vodovoz/Dialogs/Client/DeliveryPointDlg.cs
- Vodovoz/Filters/GtkViews/CallTaskFilterView.cs
- Vodovoz/Filters/ViewModels/CallTaskFilterViewModel.cs
- Vodovoz/JournalViewers/TasksView.cs
- Vodovoz/MainWindow.cs
- Vodovoz/ServiceDialogs/Database/MergeAddressesDlg.cs
- Vodovoz/SidePanel/InfoViews/DeliveryPointPanelView.cs
- Vodovoz/TempAdapters/DeliveryPointJournalFactory.cs
- Vodovoz/TempAdapters/FixedPricesDialogOpener.cs
- Vodovoz/ViewWidgets/DeliveryPointsManagementView.cs
- Vodovoz/gtk-gui/Vodovoz.Dialogs.CallTaskDlg.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozBusiness/EntityRepositories/Counterparties/DeliveryPointRepository.cs
- VodovozBusiness/EntityRepositories/Counterparties/IDeliveryPointRepository.cs
- VodovozViewModels/Journals/JournalViewModels/Client/DeliveryPointByClientJournalViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Client/DeliveryPointJournalViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
- Добавил виджеты для отображения коммента и сделал эту панель открытой изначально
- Также добавил метод получения DeliveryPointCategory в репозиторий, прокинул репозиторий
- Отформатировал callTaskDlg,  tasksView, callTaskFilterViewModel
> 3700 Комментарий про клиента в задаче обзвона

- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
Почистил диалог RouteListCreateDlg
> Чистка кода RouteListCreateDlg

- Vodovoz/MainWindow.cs
- Vodovoz/Reports/Bottles/ReturnedTareReport.rdl
- Vodovoz/ReportsParameters/Bottles/ReturnedTareReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.ReturnedTareReport.cs
В фильтр добавлен чекбокс "Закрытые заказы", при активации которого в отчет попадают только заказы со Статусом "Закрыт".
Добавлен спасательный круг (правила попадания данных в отчет) 
> 3702 - В отчёт по забору тары добавлен статус и спасательный круг

- VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
Для отлова ошибки ISessionIsClosed
> Добавил логер

- Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
- Vodovoz/Additions/Logistic/RouteListPrintableDocs.cs
- Vodovoz/Additions/Logistic/RouteListPrintableDocuments.cs
- Vodovoz/Vodovoz.csproj
Добавлена надпись "Приоритет!" перед комментарием к заказу в печатной форме МЛ
Почищен код
> Задача 3698: приоритетные адреса МЛ

- Vodovoz/ViewModels/ManualPaymentMatchingViewModel.cs
> Стиль кода

- Vodovoz/ViewModels/ManualPaymentMatchingViewModel.cs
Добавлено ограничение возможности сохранения платежей не в статусе "Нераспределен".
> 3562 - Ограничение распределения платежей

- Vodovoz/Reports/Logistic/DeliveriesLate.rdl
- Vodovoz/Reports/Logistic/RouteListOnClosing.rdl
- Vodovoz/ReportsParameters/Logistic/DeliveriesLateReport.cs
- Vodovoz/ReportsParameters/Logistic/RouteListsOnClosingReport.cs
- Vodovoz/gtk-gui/Vodovoz.Reports.Logistic.DeliveriesLateReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Logistic.RouteListsOnClosingReport.cs
Добавлен фильтр по части города в следующие отчёты: 
1. Отчет по незакрытым МЛ
2. Отчет по опозданиям
> 3704 Фильтры в отчеты ЛО по части города

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/gtk-gui/Vodovoz.OrderDlg.cs
- VodovozBusiness/Domain/Orders/OrderEnums.cs
Доработка по замечаниям после теста:
Для отображения текущего типа адреса доставки выделен отдельный лейбл
Кнопки перемещены в одну строку в хбокс
Изменение клиенте (isChainStore) теперь корректно отлавливается при открытии диалога клиента через диалог заказа
> 3694 Доработка замечаний после теста

- Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
> 3698 - фикс

- Vodovoz/Filters/GtkViews/OrderFilterView.cs
- Vodovoz/Filters/ViewModels/OrderJournalFilterViewModel.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.ComplaintFilterView.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.OrderFilterView.cs
Добавлен фильтр по дате создания заказа
Добавлен фильтр по части города
Дефолтное значение фильтра по дате - сегодня минус 2 месяца, плюс неделя
> 3553 Фильтры в журнал заказов (дата создания, часть города)

- Vodovoz/Reports/Complaints.rdl
- Vodovoz/SidePanel/InfoViews/ComplaintPanelView.cs
- VodovozBusiness/Domain/Complaints/ComplaintGuiltyItem.cs
- VodovozBusiness/Domain/Complaints/ComplaintGuiltyTypes.cs
- VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- VodovozViewModels/ViewModels/Complaints/GuiltyItemViewModel.cs
Добавил новый тип виновного
Внес необходимые изменения в журнал рекламаций, боковую панель
Удалил неиспользуемое свойство во вью модели виновных
> Добавление нового типа виновного - Поставщик

- Vodovoz/Filters/GtkViews/EmployeeFilterView.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.EmployeeFilterView.cs
- VodovozViewModels/Journals/FilterViewModels/Employees/EmployeeFilterViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Employees/EmployeesJournalViewModel.cs
Добавлены дополнительные фильтры:
- Подразделение - поле, которое заполняется из журнала подразделений 
- Управляет а\м - выпадающий список 
- Оформление - выпадающий список 
- Прием на работу - поля периода 
- Первый рабочий день - поля периода
- Дата увольнения - поля периода
- Дата расчета - поля периода
Галочки: 
- Выездной мастер
- Разовый водитель 
- Водитель для сетей
- Гражданство РФ
> Задача 3486 Новые параметры фильтра журнала сотрудников

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Перепроверил и изменил логику отображения и работы кнопок, переместил условие самовывоза
> 3694 Фикс логики отображения кнопок самовывоз

- Vodovoz/Filters/GtkViews/OrderFilterView.cs
- Vodovoz/Filters/ViewModels/OrderJournalFilterViewModel.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.OrderFilterView.cs
- Vodovoz/toolbars/ToolbarActions.cs
Добавил галочку для сортировки по дате доставки в журнал заказа.
Возможность сортировки появляется только при открытии через "контрагент-все заказы контрагента".
> 3697 Сортировка по дате доставки 

- Vodovoz/Dialogs/Employees/EmployeeDlg.cs
- Vodovoz/Dialogs/Employees/EmployeeDocDlg.cs
- Vodovoz/Dialogs/Employees/TraineeDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- Vodovoz/Views/Employees/EmployeeView.cs
- VodovozBusiness/Domain/Employees/EmployeeDocument.cs
- VodovozViewModels/ViewModels/Employees/EmployeeViewModel.cs
Теперь документы сотрудника закрыты правом документа "документ сотрудника"
> Задача 3732: хотфикс прав доступа к документам сотрудника

- VodovozBusiness/Domain/Documents/DriverTerminal/DriverAttachedTerminalDocumentBase.cs
- VodovozBusiness/Domain/Documents/DriverTerminal/DriverAttachedTerminalGiveoutDocument.cs
- VodovozBusiness/Domain/Documents/DriverTerminal/DriverAttachedTerminalReturnDocument.cs
- VodovozViewModels/ViewModels/Employees/TerminalManagementViewModel.cs
Также убрал мониторинг из базового класса
> 3735 Убрано формирование штрафа при выдаче терминала

- Jenkinsfile
This reverts commit aea0d7579268679b861cb83daabec7e70ad79bfd, reversing
changes made to 460f707737ae4b53b001497e07d0aa20ffc91892.
> Revert "Merge branch 'master' into develop"

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Сохранение и закрытие при принятии
> 3703: фикс

- Services/WebApi/DriverAPI.Library/Models/DriverMobileAppActionRecordModel.cs
- Services/WebApi/DriverAPI.Library/Models/IDriverMobileAppActionRecordModel.cs
- Services/WebApi/DriverAPI/Controllers/OrdersController.cs
- Services/WebApi/DriverAPI/Controllers/RegistrationsController.cs
- Services/WebApi/DriverAPI/Controllers/RouteListsController.cs
- Services/WebApi/DriverAPI/Controllers/SmsPaymentsController.cs
- Services/WebApi/DriverAPI/DTOs/RouteListAddressCoordinateDto.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverMobileAppActionRecord.cs
- VodovozBusiness/Domain/Logistic/Drivers/DriverMobileAppActionType.cs
- VodovozBusiness/HibernateMapping/Logistic/Drivers/DriverMobileAppActionRecordMap.cs
- VodovozBusiness/VodovozBusiness.csproj
Добавил новые действия для регистрации и результат выполнения
> Задача 3728: добавление новых записей о действиях пользователей

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Исправлена ошибка nullref
Исправлена точность цифр
> Фикс для 3703

- .editorconfig
Фиксит отображение в гитхабе
Изменяет отображение табов на 4 пробела в редакторах по умолчанию
> Изменяет настройки табов в отображении редактора

- .editorconfig
Добавлены следующие правила
- Возвращены табы для всего
- Табы в RDL отключены
- Добавлена новая строка в конец файла
- Убирать завершающие пробелы
> Фикс Editorconfig

- Vodovoz/Commons/FileChooser.cs
- Vodovoz/Dialogs/OnlineStore/ExportToSiteDlg.cs
- Vodovoz/Views/ExportImportNomenclatureCatalogView.cs
- Vodovoz/Views/Reports/CarsExploitationReportView.cs
- Vodovoz/Views/Reports/OrderAnalyticsReportView.cs
Добавил несколько свойств, задействующих окно на подтверждение сохранения файла (выгрузки), если такой файл уже существует в выбранной для сохранения директории
> 3551 Проверка на наличие файла с одинаковым названием

- Vodovoz/CreateProjectParam.cs
- Vodovoz/Dialogs/Cash/CashExpenseDlg.cs
- Vodovoz/Dialogs/OrderWidgets/GtkTabsOpener.cs
- Vodovoz/JournalViewModels/RouteListWorkingJournalViewModel.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Parameters/ExpenseParametersProvider.cs
- VodovozBusiness/Parameters/IExpenseParametersProvider.cs
- VodovozBusiness/VodovozBusiness.csproj
- VodovozViewModels/TempAdapters/IGtkTabsOpener.cs
Добавлен функционал открытия нового расходного ордера из журнала "Работа с МЛ" (Касса) для сдачи по МЛ
> 3747 - Сдача клиенту

- Vodovoz/JournalViewModels/PaymentsJournalViewModel.cs
- VodovozBusiness/ConfigureDeletion.cs
- VodovozBusiness/Domain/Payments/PaymentItem.cs
Добавил в конфиг удаления все что касается платежей по выписке
Включил кнопку удаления для админов в журнале платежей
> Изменения журнала платежей и обновления конфига удаления

- Vodovoz/Core/Permissions/SubdivisionForUserEntityPermissionWidget.cs
- Vodovoz/ViewWidgets/Permissions/PresetPermissionsView.cs
- Vodovoz/gtk-gui/Vodovoz.Core.Permissions.SubdivisionForUserEntityPermissionWidget.cs
- Vodovoz/gtk-gui/Vodovoz.ViewWidgets.Permissions.PresetPermissionsView.cs
- VodovozViewModels/ViewModels/Permissions/PresetPermissionsViewModelBase.cs
- VodovozViewModels/ViewModels/Permissions/PresetUserPermissionsViewModel.cs
Добавлен поиск в диалог пользователя:
-поиск по предустановленным правам;
-поиск в особые права на подразделения: 2 вида - поиск по подразделениям и поиск по документам идет отдельно.
Также по задаче необходим был поиск на документы, это идет в Qsolution.
По задаче просили небольшой рефакторинг под VM, будет сделано позже, так как сроки поджимают, функционал необходим сейчас.
> 3613 Поиск в диалоге пользователя (пред. права и особые права на подр.)

- Vodovoz/Core/Permissions/SubdivisionForUserEntityPermissionWidget.cs
Поправил ошибку, при которой программа вылетала
Сделал отображение подразделений всегда Expanded по запросу заказчика
> 3613 Фикс ошибки и подразделения всегда Expanded

- Vodovoz/Reports/Logistic/OrderStatisticByWeek.rdl
- Vodovoz/ReportsParameters/OrderStatisticByWeekReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.OrderStatisticByWeekReport.cs
Также добавил строку с выбранными фильтрами
> 3766 Фильтр по частям города в статистике заказов по дням недели

- Vodovoz/Reports/Logistic/DeliveriesLate.rdl
Раньше отчёт фильтровался по части города из МЛ, теперь по части города из района точки доставки заказа.
> 3754 Переделан фильтр по части города в отчёте по опозданиям водителей

- Jenkinsfile
Автоматическая публикация в папки E:\CD\DriverAPI\<ветка> для master, develop, release
> DriverAPI - CD

- Jenkinsfile
> DriverAPI - Фикс

- Jenkinsfile
> DriverAPI Исправление пути доставки артефакта

- Vodovoz/Views/Logistic/DriversInfoExportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Logistic.DriversInfoExportView.cs
- VodovozViewModels/ViewModels/Logistic/DriversInfoExportViewModel.cs
Хотфикс по пункту 1 задачи: добавлен тип выгрузки с группировкой по водителям и авто.
> Хотфикс 3782 В выгрузку по водителям добавлен вывод с группировкой по водителю и авто

- Services/Application/VodovozSalesReceiptsService/SalesReceiptsService.cs
- VodovozBusiness/Services/ISalesReceiptsServiceSettings.cs
Пока что использовал уже существующий для androidDriverService параметр
> VV-82,2513 Добавил кол-во uow в статус службы чеков

- Vodovoz/Views/Logistic/DriversInfoExportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Logistic.DriversInfoExportView.cs
- VodovozViewModels/ViewModels/Logistic/DriversInfoExportViewModel.cs
2. Добавлен фильтр по колонкам план/факт.
3. Столбики ЗП план и факт объединены в один столбик (для всех отборов). Для группировки по МЛ показывает либо факт, либо план, в зависимости от статуса МЛ. Для группировки по водителям и авто в столбце ЗП отображается сумма зп план + зп факт.
4. Для группировки по водителям и авто столбцы поменяны местами.
> Хотфикс 3782 (этап 2) Добавлен фильтр план/факт

- Services/Library/Android/AndroidDriverService.cs
- Services/WebApi/DriverAPI.Library/Models/OrderModel.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Vodovoz/ViewModels/Mango/WidgetsModel/CounterpartyOrderViewModel.cs
- Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Logistic/RouteListItem.cs
- VodovozBusiness/Domain/Orders/Order.cs
Изменение бизнес логики
Теперь смена статуса адреса МЛ должна происходить через вызов методов МЛ
> Хотфикс 3757

- VodovozBusiness/Tools/ErrorReporting/SingletonErrorReporter.cs
- VodovozBusinessTests/ErrorReporting/SingletonErrorReporterTest.cs
https://github.com/QualitySolution/QSProjects/pull/367
> VV-87,3778 Замена интерфейса отправки ошибок

- Services/Application/VodovozSalesReceiptsService/FiscalizationWorker.cs
- Services/Application/VodovozSalesReceiptsService/ReceiptServiceStarter.cs
- Services/Application/VodovozSalesReceiptsService/SalesReceiptsInstanceProvider.cs
- Services/Application/VodovozSalesReceiptsService/SalesReceiptsService.cs
- VodovozBusiness/EntityRepositories/Orders/ExtendedReceiptForOrderNode.cs
- VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
Удалены лишние параметры
Почищен код
> Изменена логика отправки чеков для заказов

- VodovozBusinessTests/Domain/Orders/OrderItemTests.cs
Восстановлена работоспособность тестов после выполнении задачи на изменения логики в работе акции "Бутыль".
> 3153 Тесты после изменения логики в работе акции "Бутыль"

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Dialogs/Client/DeliveryPointDlg.cs
- Vodovoz/Views/Contacts/PhonesView.cs
- VodovozBusiness/Domain/Contacts/Phone.cs
- VodovozBusiness/HibernateMapping/Counterparty/CounterpartyMap.cs
- VodovozBusiness/HibernateMapping/Counterparty/DeliveryPointMap.cs
- VodovozViewModels/ViewModels/Contacts/PhonesViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
Сохранять в историю добавление и удаление телефонов с названием Точки доставки / Контрагента
> 3683 доработка - сохранять в историю добавление и удаление телефонов

- Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Vodovoz/gtk-gui/Vodovoz.RouteListKeepingDlg.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
Добавлена кнопка вернуть в статус "Доставлен" в диалоге ведения МЛ.
> Кнопка вернуть в статус Доставлен в диалоге ведения МЛ

- Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Vodovoz/gtk-gui/Vodovoz.RouteListKeepingDlg.cs
Исправлен биндинг
Исправлено название кнопки
> Хотфикс VV-96 (правки)

- Vodovoz/Reports/Logistic/AnalyticsForUndelivery.rdl
- Vodovoz/Vodovoz.csproj
Подцепил файл отчета к проекту и внес небольшое исправление по запросу тестера (убрал разделительную линию)
> Include analytics for undelivery report

- Vodovoz/Reports/Logistic/AnalyticsForUndelivery.rdl
- Vodovoz/ReportsParameters/Logistic/AnalyticsForUndeliveryReport.cs
Поменял проверку в аналитике недовозов в запросе на адреса/бутыли на старое поле (согласовано) как в статистике по дням недели
Добавил дополнительных проверок
Поправил разметку
> Фикс проверки на сервисный заказ

- Vodovoz/Reports/Client/SummaryBottlesAndDeposits.rdl
Акте приёма передачи полной и пустой тары, оборудования
> Хотфикс ширины столбцов в Акте по бутылям-залогам

- Services/Application/VodovozSmsPaymentService/Program.cs
- Services/Application/VodovozSmsPaymentService/SmsPaymentServiceInstanceProvider.cs
- Services/Library/SmsPaymentService/ISmsPaymentValidator.cs
- Services/Library/SmsPaymentService/PaymentControllers/BitrixPaymentController.cs
- Services/Library/SmsPaymentService/PaymentControllers/IPaymentController.cs
- Services/Library/SmsPaymentService/PaymentControllers/TestPaymentController.cs
- Services/Library/SmsPaymentService/SmsPaymentDTOFactory.cs
- Services/Library/SmsPaymentService/SmsPaymentService.cs
- Services/Library/SmsPaymentService/SmsPaymentService.csproj
- Services/Library/SmsPaymentService/SmsPaymentValidator.cs
- Services/Library/SmsPaymentService/Workers/CachePaymentsWorker.cs
- Services/Library/SmsPaymentService/Workers/OverduePaymentsWorker.cs
- VodovozBusiness/Models/IOrganizationProvider.cs
- VodovozBusiness/Models/OrderOrganizationProviderFactory.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
- VodovozBusiness/Parameters/OrderParametersProvider.cs
К заказам, оплаченным По карте с источником СМС и с точкой доставки на Севере, теперь прикрепляется Южная организация
К заказам, оплаченным По карте с источником Терминал, теперь прикрепляется Северная организация
Добавил валидатор сущности смс оплат в сервис смс оплат
Косметические изменения
> Изменения в логике подбора организации

- Vodovoz/Configuration/ApplicationConfigurator.cs
- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
Подробнее здесь: https://github.com/QualitySolution/QSProjects/pull/371
> 3745 Печать погрузочного талона на разные принтеры

- Services/Library/SmsPaymentService/SmsPaymentService.cs
- Services/WebApi/DriverAPI.Library/Converters/OrderConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/Models/OrderModel.cs
- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/JournalViewModels/SelfDeliveriesJournalViewModel.cs
- Vodovoz/ServiceDialogs/ExportTo1c/ExportData.cs
- Vodovoz/ServiceDialogs/Old1612ExportTo1c/Old1612ExportData.cs
- Vodovoz/ServiceDialogs/OldExportTo1c/ExportData.cs
- Vodovoz/ViewModels/AutoPaymentMatching.cs
- Vodovoz/ViewModels/ManualPaymentMatchingViewModel.cs
- Vodovoz/ViewWidgets/DepositRefundItemsView.cs
- Vodovoz/ViewWidgets/Logistics/RouteListClosingItemsView.cs
- Vodovoz/ViewWidgets/UndeliveredOrderView.cs
- Vodovoz/Views/BusinessTasks/PaymentTaskView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.ManualPaymentMatchingView.cs
- VodovozBusiness/Domain/Cash/Expense.cs
- VodovozBusiness/Domain/Cash/Income.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrderDepositItem.cs
- VodovozBusiness/Domain/Orders/UndeliveredOrder.cs
- VodovozBusiness/Domain/Payments/Payment.cs
- VodovozBusinessTests/SmsPaymentService/SmsPaymentItemDTOCalculateTests.cs
Переименовал свойство в DepositItem (Total -> ActualSum)
> Почистил неактуальные суммы в заказе

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Views/Client/DeliveryPointView.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
3833 Добавил два права на добавление/изменение фиксы в карточке клиента и ТД
-перенес свойства ниже конструктора во вью модели ТД
> 3833 Добавление прав на редактирование фиксы

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> 3807 Убрал работу с observable, т.к. не было консистентного состояния самих Phones

- Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
- Vodovoz/Dialogs/Logistic/RoutesAtDayDlg.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- Vodovoz/Views/Logistic/RouteListsOnDayView.cs
- VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/ICarRepository.cs
- удалил ненужный метод из репозитория автомобилей;
- Переделал вызов журнала из соответсвующих диалогов;
> 3836 Исправить открытие диалога авто

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
Фикс переноса терминала в направлении "Вернуть" в диалоге переноса адресов
> Хотфикс переноса терминала

- Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
- исправил ошибку при открытии диалога сотрудника;
- поправил активность кнопки очистки списка водителей;
> Поправил ошибки

- Vodovoz/ViewModels/ManualPaymentMatchingViewModel.cs
- VodovozBusiness/Domain/Payments/Payment.cs
Убрал удаление операции прихода при отмене распределения на заказ
Скорректировал условие подсчета суммы распределения
> Фикс ручного распределения платежей

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Можно создать дубликат заказа, только если он создан из недовоза (нельзя через "Повторить заказ")
> Хотфикс: запрет создания дубликата заказа через "Повторить заказ"

- Vodovoz/Views/Complaints/ComplaintView.cs
- VodovozBusiness/ConfigureDeletion.cs
- VodovozBusiness/Domain/Complaints/Complaint.cs
- VodovozBusiness/EntityRepositories/Complaints/ComplaintResults/ComplaintResultsRepository.cs
- VodovozBusiness/EntityRepositories/Complaints/ComplaintResults/IComplaintResultsRepository.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
- добавил конфиг удаления результатов рекламации;
- переделал вызов закрытия рекламации;
- если в рекламации стоят результаты, которые уже заархивированы, грузим список всех результатов, иначе только активные;
> 3843 Исправления после теста

- Vodovoz/Dialogs/Sale/DeliveryPriceDlg.cs
- Vodovoz/TempAdapters/FixedPricesDialogOpener.cs
- Vodovoz/Views/Client/DeliveryPointView.cs
- VodovozBusiness/Domain/Client/DeliveryPoint.cs
- VodovozBusiness/HibernateMapping/Counterparty/DeliveryPointMap.cs
- VodovozFiasWidgets/CityEntry.cs
- VodovozFiasWidgets/HouseEntry.cs
- VodovozFiasWidgets/StreetEntry.cs
Правки после ревью, добавил сохранение полного названия типа населённого пункта
> Хотфикс: правки после ревью, сохранение типа населённого пункта

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Открываем диалог добавления документов в подчиненной вкладке, т.к. туда передается uow карточки заказа
> Фикс закрытой сессии

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusinessTests/Domain/Orders/OrderTests.cs
Исправил запись телефона в коллекцию с неверным индексом
> Исправил формат подбираемого номера телефона для службы отправки чеков (Добавил +7)

- Vodovoz/Views/Employees/EmployeeView.cs
добавил пропущенный биндинг под комментарий
и обернул код вкладок вьюхи в "регионы"
> 3862 Исправление карточки сотрудника

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- VodovozBusiness/Controllers/IOrderDiscountsController.cs
- VodovozBusiness/Controllers/OrderDiscountsController.cs
- установка скидки на фиксу или промо-набор доступна для людей с правами;
- если у пользователя нет прав, то при попытке установки основания на промо-набор или фиксу будет выводиться сообщение;
> 3802 Обновление логики установки скидок

- Vodovoz/MainWindow.cs
- Vodovoz/Reports/Bottles/ReturnedTareReport.rdl
- Vodovoz/Reports/Sales/PlanImplementationByEmployeeReport.rdl
- Vodovoz/Reports/Sales/PlanImplementationFullReport.rdl
- Vodovoz/ReportsParameters/Bottles/ReturnedTareReport.cs
- Vodovoz/ReportsParameters/Sales/PlanImplementationReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.Bottles.ReturnedTareReport.cs
- Vodovoz/gtk-gui/Vodovoz.ReportsParameters.PlanImplementationReport.cs
- добавлены фильтры по подразделению и авторам заказа в эти отчеты;
- в отчете по выполнению плана если не выбран конкретный сотрудник, то открываем общий отчет, иначе подробный по выбранным авторам;
- в отчете по забору бутылей все стандартно, данные формируются исходя из установленных фильтров;
> Добавление мульти-фильтра в отчеты по забору бутылей и выполнению плана

- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- Vodovoz/Reports/Logistic/AddressesOverpaymentsReport.rdl
- Vodovoz/Reports/Sales/SalaryRatesReport.rdl
- Vodovoz/Views/Settings/GeneralSettingsView.cs
- Vodovoz/Views/WageCalculation/EmployeeWageParametersView.cs
- Vodovoz/Views/WageCalculation/RatesLevelWageParameterView.cs
- Vodovoz/Views/WageCalculation/WageDistrictLevelRatesView.cs
- Vodovoz/Views/WageCalculation/WageParameterView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Settings.GeneralSettingsView.cs
- VodovozBusiness/Domain/Logistic/Car.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/Logistic/RouteListWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/WageDistrictLevelRate.cs
- VodovozBusiness/Domain/WageCalculation/WageDistrictLevelRates.cs
- VodovozBusiness/HibernateMapping/WageCalculation/WageDistrictLevelRateMap.cs
- VodovozBusiness/Parameters/GeneralSettingsParametersProvider.cs
- VodovozBusiness/Parameters/IGeneralSettingsParametersProvider.cs
- VodovozBusiness/Parameters/ParametersProvider.cs
- VodovozViewModels/ViewModels/Settings/GeneralSettingsViewModel.cs
- VodovozViewModels/ViewModels/WageCalculation/EmployeeWageParameterNode.cs
- VodovozViewModels/ViewModels/WageCalculation/EmployeeWageParameterViewModel.cs
- VodovozViewModels/ViewModels/WageCalculation/RatesLevelWageParameterItemViewModel.cs
- VodovozViewModels/ViewModels/WageCalculation/WageDistrictLevelRatesViewModel.cs
Добавлена возможность заблокировать добавление экспедиторов к ларгусам
> Добавлено разделение ставок на Ларгусы и Газели, обновлены отчёты

- Services/Library/SmsPaymentService/SmsPaymentService.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
- Services/WebApi/DriverAPI/Controllers/PushNotificationsController.cs
Фикс эксепшена при отправке Push уведомления для водительского приложения,
убран вызов старого сервиса.
> Фикс эксепшена при отправке Push уведомления для водительского приложения

- Services/WebApi/DriverAPI.Library/Models/IOrderModel.cs
- Services/WebApi/DriverAPI.Library/Models/OrderModel.cs
- Services/WebApi/DriverAPI/Controllers/OrdersController.cs
- Services/WebApi/DriverAPI/DTOs/CompletedOrderRequestDto.cs
- VodovozBusiness/Domain/Orders/OrderEnums.cs
Добавлен комментарий и отзвон водителя при кол-ве сданных бутылей, отличающихся от планируемых.
> 3875 В DriverApi добавлен комментарий и отзвон водителя при кол-ве сданных бутылей, отличающихся от планируемых.

- Vodovoz/Views/Logistic/DistrictsSetActivationView.cs
- VodovozBusiness/Domain/Client/DeliveryPoint.cs
- VodovozBusiness/Domain/Logistic/DistrictsSet.cs
- VodovozBusiness/EntityRepositories/Delivery/DeliveryRepository.cs
- VodovozBusiness/EntityRepositories/Delivery/IDeliveryRepository.cs
- VodovozViewModels/Journals/JournalViewModels/Logistic/DistrictsSetJournalViewModel.cs
- VodovozViewModels/ViewModels/Logistic/DistrictsSetActivationViewModel.cs
Убрал Batch коммиты
Теперь в таске активации используется собственный UoW
Теперь ошибки при активации будут появляться в стандартном окне ошибок
> Добавил открытие транзакции при активации версии районов

- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
- Vodovoz/gtk-gui/Vodovoz.RouteListCreateDlg.cs
- VodovozViewModels/Journals/JournalNodes/Employees/EmployeeJournalNode.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/SalaryByEmployeeJournalViewModel.cs
- добавлены комментарии по водителю и экспедитору в диалог создания МЛ;
- добавлен последним столбцом комментарий по сотруднику в журнал выдач зп;
> Добавление комментариев по водителю и экспедитору в создание МЛ

- VodovozBusiness/Models/Orders/CopyingOrder.cs
удалил расчет доставки при копировании строк заказа, расчет произойдет при смене даты доставки
> Фикс nullRefExc при расчете цены доставки из копирования самовывоза

- Vodovoz/Dialogs/Cash/CashRequestView.cs
- Vodovoz/Views/Cash/CashlessRequestView.cs
- Vodovoz/toolbars/accounting.xml
- VodovozBusiness/Domain/Cash/CashRequest/PayoutRequestBase.cs
- VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
Владелец права может смотреть заявки на ДС со всех подразделений в справочнике
и открывать сами заявки в режиме просмотра, если не он их автор
> 3884 добавил новую роль Служба безопасности

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Models/Orders/CopyingOrder.cs
При копировании заказа и переносе через недовоз, копируем скидки для промо-наборов
Также при переносе через недовоз копируем все скидки из прошлого заказа
> Поправил копирование промо-наборов и убрал дублирование платной доставки

- Vodovoz/Dialogs/Employees/FineDlg.cs
- Vodovoz/JournalColumnsConfigs/JournalsColumnsConfigs.cs
- Vodovoz/Representations/FinesVM.cs
- Vodovoz/Views/Employees/FineView.cs
- Vodovoz/gtk-gui/Vodovoz.FineDlg.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozViewModels/Journals/JournalViewModels/Employees/FinesJournalViewModel.cs
- VodovozViewModels/ViewModels/Employees/FineViewModel.cs
- переработал диалоги штрафов под права(теперь у кого нет прав на создание и редактирование, но есть просмотр смогут их открывать в режиме чтения)
- также переделал кнопку Изменить в журналах по штрафам на право по чтению сущности;
> 3864 Изменения диалогов под права

- VodovozBusiness/EntityRepositories/Payments/IPaymentItemsRepository.cs
- VodovozBusiness/EntityRepositories/Payments/PaymentItemsRepository.cs
- VodovozViewModels/ViewModels/Payments/ManualPaymentMatchingViewModel.cs
Исправил неправильную логику установки статуса оплаты заказа при отмене распределения и самом распределении, после сохранения
> Исправление установки статуса оплаты заказа

- Vodovoz/Views/Reports/CarsExploitationReportView.cs
- Vodovoz/gtk-gui/Vodovoz.Views.Reports.CarsExploitationReportView.cs
- VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Если она стоит, то теперь в отчёт выгружаются все автомобили по всем выбранным показателям вне зависимости от того, есть ли данные для этих авто по этим показателям
> Добавлена галочка "показывать авто без движений" в отчёт эксплуатации ТС.

- Vodovoz/Reports/Payments/PaymentsFromBankClientFinDepartmentReport.rdl
is_manual_created -> is_manually_created
crlf -> lf
> 3859 поправил имя переименованной колонки

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
вызываем метод добавления коммента из ТД, если у клиента 1 ТД и она выбрана
> 3880 Фикс добавления комментария из ТД

- Vodovoz/Views/Employees/EmployeeView.cs
- VodovozViewModels/ViewModels/Employees/EmployeeViewModel.cs
Даем доступ на вкладку Документы в карточке сотрудника у кого есть права на его просмотр, вместо редактирования
> Фикс вьюхи сотрудника

- Vodovoz/Dialogs/Employees/EmployeeDocDlg.cs
- Vodovoz/Dialogs/Employees/TraineeDlg.cs
- Vodovoz/Views/Employees/EmployeeView.cs
- VodovozViewModels/ViewModels/Employees/EmployeeViewModel.cs
- открыл доступ к карточке документа сотрудника если есть права на просмотр сотрудника и его документов;
- при наличии только прав на просмотр делаем недоступной кнопку сохранить и пару элементов для изменения, все остальные элементы открыты, чтобы можно было копировать информацию с них;
> Фикс карточки сотрудника

- Vodovoz/Dialogs/Cash/AdvanceReportDlg.cs
- Vodovoz/Dialogs/Cash/CashExpenseDlg.cs
- Vodovoz/Dialogs/Cash/CashExpenseSelfDeliveryDlg.cs
- Vodovoz/Dialogs/Cash/CashIncomeDlg.cs
- Vodovoz/Dialogs/Cash/CashIncomeSelfDeliveryDlg.cs
- Vodovoz/Dialogs/Cash/TransferExpenseDlg.cs
- Vodovoz/Dialogs/Cash/TransferIncomeDlg.cs
- Vodovoz/Dialogs/Logistic/FuelDocumentView.cs
- Vodovoz/Dialogs/OrderWidgets/GtkTabsOpener.cs
- Vodovoz/JournalViewModels/RouteListWorkingJournalViewModel.cs
- Vodovoz/JournalViewModels/SelfDeliveriesJournalViewModel.cs
- Vodovoz/JournalViewers/Cash/AccountableDebts.cs
- Vodovoz/JournalViewers/Cash/UnclosedAdvancesView.cs
- Vodovoz/Representations/CashMultipleDocumentVM.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/SalaryByEmployeeJournalViewModel.cs
- VodovozViewModels/TempAdapters/IGtkTabsOpener.cs
- починил открытие/изменение диалогов приходного/расходного ордеров из старого журнала;
- до кучи поправил остальные диалоги кассовых документов;
> Фикс открытия диалогов приходника/расходника

- Vodovoz/Dialogs/UndeliveryOnOrderCloseDlg.cs
Вызываем событие dlgSaved, если уже есть недовоз по этому заказу и создан коммент к нему;
> Фикс повторной смены статуса адреса/заказа на Доставка отменена или Недовоз

- Vodovoz/CreateProjectParam.cs
- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentView.cs
- Vodovoz/Dialogs/Logistic/RouteListControlDlg.cs
- Vodovoz/Dialogs/OrderWidgets/GtkTabsOpener.cs
- Vodovoz/JournalViewModels/RouteListJournalViewModel.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- VodovozViewModels/TempAdapters/IGtkTabsOpener.cs
> Реализована Автоматическая распечатка погрузочных талонов

- Services/WebApi/MailjetEventsDistributorAPI/Controllers/MailjetEventsDistributeController.cs
Фикс эндпоинта и фикс обновления статуса
> Фиксы MailjetEventsDistributorAPI

- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Dialogs/DocumentDialogs/IncomingWaterDlg.cs
- Vodovoz/Dialogs/DocumentDialogs/RegradingOfGoodsDocumentItemsView.cs
- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/Filters/ViewModels/DebtorsJournalFilterViewModel.cs
- Vodovoz/JournalFilters/ClientBalanceFilter.cs
- Vodovoz/JournalSelector/NomenclatureAutoCompleteSelectorFactory.cs
- Vodovoz/JournalSelector/NomenclatureSelectorFactory.cs
- Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Vodovoz/JournalViewModels/PromotionalSetsJournalViewModel.cs
- Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Vodovoz/JournalViewModels/Suppliers/RequestsToSuppliersJournalViewModel.cs
- Vodovoz/JournalViewModels/WaterJournalViewModel.cs
- Vodovoz/MainWindow.cs
- Vodovoz/TempAdapters/NomenclatureSelectorFactory.cs
- Vodovoz/TempAdapters/WaterJournalFactory.cs
- Vodovoz/ViewModels/Client/SupplierPricesWidgetViewModel.cs
- Vodovoz/ViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentViewModel.cs
- Vodovoz/ViewModels/Orders/PromotionalSetActionWidgetResolver.cs
- Vodovoz/ViewModels/Orders/PromotionalSetViewModel.cs
- Vodovoz/ViewModels/Suppliers/RequestToSupplierViewModel.cs
- Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozViewModels/Dialogs/Goods/NomenclatureViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Goods/NomenclaturesJournalViewModel.cs
- VodovozViewModels/TempAdapters/INomenclatureSelectorFactory.cs
Заменил IEntityAutocompleteSelectorFactory контрагентов на ICounterpartyJournalFactory в журнале и сущности номенклатуры
> Заменил IEntityAutocompleteSelectorFactory

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Автоматическая отправка счета клиенту при нажатии на кнопку "Ожидание оплаты" и сохранении заказа.
Протестировано.
> Хотфикс: Отправка счета клиенту при переводе заказа в статус "Ожидание оплаты"

- Vodovoz/CreateProjectParam.cs
- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Factories/AttachmentsViewModelFactory.cs
- Vodovoz/MainWindow.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashlessRequestFilesViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionsViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintFilesViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
- VodovozViewModels/ViewModels/Complaints/CreateComplaintViewModel.cs
- VodovozViewModels/ViewModels/Complaints/CreateInnerComplaintViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/CounterpartyFilesViewModel.cs
- VodovozViewModels/ViewModels/FilesViewModel.cs
- VodovozViewModels/ViewModels/Reports/NomenclaturePlanReportViewModel.cs
- VodovozViewModels/ViewModels/Reports/ProductionWarehouseMovementReport/ProductionWarehouseMovementReport.cs
- VodovozViewModels/ViewModels/Reports/ProductionWarehouseMovementReportViewModel.cs
> Revert "Замена вызовов диалогов работы с файлами на вызовы через новый сервис"

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
> Хотфикс вопроса продолжения сохранения для физ. лиц (не безнал)

- Vodovoz/Views/Logistic/CarVersionsView.cs
- VodovozBusiness/Domain/Logistic/Cars/Car.cs
- VodovozBusiness/Domain/Logistic/Cars/CarVersion.cs
- VodovozViewModels/ViewModels/Logistic/CarViewModel.cs
- VodovozViewModels/Widgets/Cars/CarVersionsViewModel.cs
Удалено использование права can_change_car_is_raskat
> Добавлены права на документы для версий

- Services/Application/VodovozDeliveryRulesService/DTO/DeliveryRulesRequest.cs
- Services/Application/VodovozDeliveryRulesService/DeliveryRulesService.cs
- Services/Application/VodovozDeliveryRulesService/IDeliveryRulesService.cs
- Services/Application/VodovozDeliveryRulesService/Program.cs
- Services/Application/VodovozDeliveryRulesService/VodovozDeliveryRulesService.csproj
- Vodovoz/gtk-gui/Vodovoz.Views.Logistic.CarView.cs
- VodovozBusiness/EntityRepositories/Delivery/DeliveryRepository.cs
- VodovozBusiness/EntityRepositories/Delivery/IDeliveryRepository.cs
- VodovozBusiness/EntityRepositories/Goods/NomenclatureRepository.cs
- VodovozBusiness/Parameters/DeliveryRulesParametersProvider.cs
- VodovozBusiness/Services/IDeliveryRulesParametersProvider.cs
Пока что просто возвращает данные из GetRulesByDistrict
Запрос возможности доставки за час тоже не финальный
Также вырезал OSRM из сервиса
> Новый эндпоинт в сервисе правил доставки

- Services/Workers/EmailPrepareWorker/EmailPrepareWorker.cs
При отмене доставки из заказа удаляются документы. Добавлена обработка этой ситуации в воркере.
> Хотфикс Email Prepare Worker (отменённые доставки)

- Vodovoz/MainWindow.cs
- Vodovoz/gtk-gui/MainWindow.cs
- Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.CarFilterView.cs
Добавил открытие журнала Моделей авто из главного окна
> Положил фильтр авто в scrollWindow

- Jenkinsfile
- Vodovoz/CreateProjectParam.cs
- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Factories/AttachmentsViewModelFactory.cs
- Vodovoz/MainWindow.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
- VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashlessRequestFilesViewModel.cs
- VodovozViewModels/ViewModels/Cash/CashlessRequestViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionsViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintFilesViewModel.cs
- VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
- VodovozViewModels/ViewModels/Complaints/CreateComplaintViewModel.cs
- VodovozViewModels/ViewModels/Complaints/CreateInnerComplaintViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/CounterpartyFilesViewModel.cs
- VodovozViewModels/ViewModels/FilesViewModel.cs
- VodovozViewModels/ViewModels/Reports/NomenclaturePlanReportViewModel.cs
- VodovozViewModels/ViewModels/Reports/ProductionWarehouseMovementReport/ProductionWarehouseMovementReport.cs
- VodovozViewModels/ViewModels/Reports/ProductionWarehouseMovementReportViewModel.cs
Reverts VodovozOrganization/Vodovoz#1256
> Замена вызовов диалогов работы с файлами на вызовы через новый сервис

- Services/Application/VodovozDeliveryRulesService/DeliveryRulesService.cs
Исправил косяк с отправкой неверных интервалов при заказе с воскресения на понедельник
> Фикс службы правил доставки

- Vodovoz/Dialogs/CallTaskDlg.cs
- Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Vodovoz/Dialogs/Phones/PhonesView.cs
- VodovozViewModels/ViewModels/Contacts/PhonesViewModel.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
Добавил конструктор в PhonesViewModel для диалогов, где не нужны сущности имён и отчеств RoboAts
> Доработка по RoboAts в PhonesViewModel

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
- Vodovoz/Views/Logistic/RouteListAnalysisView.cs
- VodovozViewModels/Dialogs/Goods/AdditionalLoadingSettingsViewModel.cs
- VodovozViewModels/VodovozViewModels.csproj
Мелкие исправления в диалогах МЛ в столбике отображение доставки за час
Исправлена логика сохранения в настройках запаса
> Откатил версию ClosedXML, вызывала ошибки

- Services/Application/VodovozSmsPaymentService/Program.cs
- Services/Library/SmsPaymentService/SmsPaymentService.cs
Добавлен таймаут и переработана логика синхронизации платежей
> Фикс службы смс оплат

- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- Vodovoz/Views/Logistic/RouteListsOnDayView.cs
Добавлено право на создание МЛ в прошлом периоде в диалоге создания и диалоге формирования МЛ
> Хотфикс 3919 Право на создание МЛ в прошлом периоде

- Vodovoz/Views/Logistic/DistrictsSetView.cs
- VodovozViewModels/ViewModels/Logistic/DistrictsSetViewModel.cs
Добавлено отдельное право на изменение условий доставки в активной версии районов
> Хотфикс 3918 - Изменение условий доставки в активной версии районов

- Services/WebApi/DriverAPI.Library/Models/ITrackPointsModel.cs
- Services/WebApi/DriverAPI.Library/Models/TrackPointsModel.cs
- Services/WebApi/DriverAPI/Controllers/OrdersController.cs
- Services/WebApi/DriverAPI/Controllers/PushNotificationsController.cs
- Services/WebApi/DriverAPI/Controllers/RegistrationsController.cs
- Services/WebApi/DriverAPI/Controllers/RouteListsController.cs
- Services/WebApi/DriverAPI/Controllers/SmsPaymentsController.cs
Добавил группировку похожих координат трека в регистрации
> Добавил логгирование токена для неанонимных запросов

- Services/Library/SmsPaymentService/DriverAPIHelper.cs
- Vodovoz/Dialogs/Logistic/RouteListTrackDlg.cs
- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/Representations/DriverRouteListAddressesVM.cs
- Vodovoz/toolbars/ToolbarActions.cs
Заказ за час в пути теперь показывается отдельным маркером
Для заказов за час добавлен отсчёт оставшегося времени
Очищаем DriverAPIHelper при закрытии диалога заказа
> Изменения в OrderDlg и RouteListTrackDlg

- Vodovoz/Representations/DebtorsJournalViewModel.cs
Поправил условие для выборки клиентов с последним заказом в указанную дату
> Правка запроса в журнале задолженностей

- Vodovoz/ReportsParameters/DriversWageBalanceReport.cs
- VodovozReports/Reports/Cash/DayOfSalaryGiveout.rdl
Пробуем поменять условие в отчетах по кассе: баланс водителей и дата зп у водителей
> Фикс кассовых отчетов

- Vodovoz/MainWindow.cs
закрыл кассовые отчеты По приходу нал д/с и Кассовая книга спецправами Касса
> 3926 Закрытие доступа к кассовым отчетам

- VodovozReports/Reports/Documents/InvoiceContractDoc.rdl
Убрал картинку акции "Лимонад в подарок" в накладной контрактной документации
> Хотфикс 3929 - Удалена картинка акции "Лимонад в подарок"

- VodovozBusiness/Tools/Orders/OrderRules.cs
Разграничение правил формирования обычных и особых счетов и УПД.
> 3922 Правила формирования в заказе обычных и специальных счетов и УПД

- Vodovoz/Dialogs/Logistic/RouteListMileageCheckDlg.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
Добавил вывод информации о ТД без координат, чтобы не летела ошибка при пересчете километража
Если есть в МЛ такая ТД, то не открываем диалог Проверки километража
> 3932 Обновление метода пересчета километража

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Открываем диалог документов прошлых заказов в подчиненной вкладке
> Правка ошибки при закрытии диалога документов после закрытия диалога заказа

- VodovozReports/Reports/RouteList/CarLoadDocument.rdl
- VodovozReports/Reports/Store/CarLoadDocument.rdl
Убрано дублирование разделов в талоне погрузки, убрана фраза "нет отгрузки товара интернет магазина"
> Хотфикс 3940: Убрано дублирование разделов в талоне погрузки

- VodovozReports/Reports/Client/BottleDebtorsJournal.rdl
В печатную форму журнала задолженностей добавлена колонка "Кол-во отгруженных в последнюю реализацию бутылей"
> Хотфикс 3942: В печатную форму журнала задолженностей добавлена колонка

- Vodovoz/Representations/CallTasksVM.cs
Берем количество из списка элементов, чтобы оно всегда корректно отображалось
> Фикс подсчета количества задач в одноименном журнале

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrderItem.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/IRouteListItemWageCalculationSource.cs
- VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- VodovozBusiness/Domain/WageCalculation/WageRate.cs
- VodovozBusiness/Domain/WageCalculation/WageRateTypes.cs
- VodovozBusiness/Models/Orders/CopyingOrder.cs
- VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- VodovozBusiness/Services/INomenclatureParametersProvider.cs
- VodovozReports/Reports/Sales/SalaryRatesReport.rdl
Добавлена новая ставка и расчёт зп для экспресс доставки.
В заказе добавляется/удаляется номенклатура "Экспресс доставка" в зависимости от флага "Доставки за час"
> 3961 Монетизация проекта "Доставка за час"

- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
- VodovozReports/Reports/RouteList/CarLoadDocument.rdl
Учёт тмц из документа запаса в ожидаемом количестве возврата талона разгрузки
> 3968 Дополнения в талон разгрузки

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
Скрыты заказы с доставкой за час в диалоге переноса адресов
> Запрет переноса заказов с доставкой за час

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
добавил проверку наличия в заказе 19л воды для запуска проверки быстрой доставки
> 3974 детализация быстрой доставки

- Services/WebApi/DriverAPI.Library/Converters/OrderConverter.cs
- Services/WebApi/DriverAPI.Library/Converters/RouteListConverter.cs
- Services/WebApi/DriverAPI.Library/Models/RouteListModel.cs
- VodovozBusiness/Domain/Logistic/Discrepancy.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
В мобильном приложении по завершении рейса в резюмировании МЛ нужно учитывать догрузку на борт для сдачи на склад
> 3958 Сдача на склад запаса в DriverApi

- Vodovoz/ReportsParameters/DriversWageBalanceReport.cs
- VodovozReports/Reports/Cash/DayOfSalaryGiveout.rdl
Фикс даты зарплаты в отчёте по балансу водителей и отчёте "Дата ЗП у водителей/экспедиторов"
> Фикс даты зарплаты в отчётах

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrderItem.cs
- VodovozBusiness/HibernateMapping/Order/OrderMap.cs
- VodovozBusiness/Models/Orders/CopyingOrder.cs
- добавил метод переноса акции бутыль в модель копирования заказа;
- при переносе из недовоза ставим ценам флаг ручного исправления, чтобы они были неизменны;
- копируем доставку вместе со скидками;
- изменение цены закрыты правами на редактирование скидки;
> 3949 Добавления по переносу заказа

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
- Vodovoz/toolbars/ToolbarActions.cs
- VodovozBusiness/Domain/Logistic/RouteList.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListItemRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListItemRepository.cs
- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
В диалоге переноса заказов для заказов с признаком "Доставка за час" убран выбор с дозагрузкой или без. Перед переносом заказа происходит проверка наличия остатков для этого заказа на борту второго МЛ.
> 3981 Переносы заказов с доставкой за час

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Детальная информация в случае отсутствия подходящего МЛ для доставки за час при подтверждении заказа
> 3994 Детальная информация при отсутствии МЛ для доставки за час

- Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
Контрол с текстом не скрывается, а очищается, чтобы было что залить цветом при закрашивании строки.
> 3981 Скрыт выбор загрузки в диалоге переноса адресов для доставки за час

- Vodovoz/MainWindow.cs
- VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
- VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
- добавил кнопку;
- поставил множественный выбор для журнала;
- добавил параметр чтобы управлять состоянием журнала (для выбора или обычный режим с множественным выделением позиций);
> 4004 Добавить кнопку Согласовать в журнал заявок дс

- VodovozReports/Reports/Payments/PaymentsFromAvangardReport.rdl
- VodovozReports/Reports/Payments/PaymentsFromTinkoffReport.rdl
Ограничил отчеты по оплатам: в старом отчете смотрим все, кроме Авангарда, в отчете по Авангарду - только его оплаты
> Обновил отчеты оплатам

- Vodovoz/Dialogs/DocumentDialogs/CarLoadDocumentDlg.cs
- да, удаляем 0 позиции и продолжаем сохранение;
- нет, не удаляем и продолжаем сохранение;
- отмена и закрытие на крестик, не сохраняем;
не открываем печатный талон, если не прошло сохранение или отказались сохранять талон
> 4027 при вопросе по удалению 0 позиций выводим окно с тремя кнопками:

- Services/WebApi/FastPaymentsAPI.Library/Managers/FastPaymentManager.cs
- VodovozBusiness/Parameters/OrderParametersProvider.cs
- VodovozBusiness/Services/IOrderParametersProvider.cs
Добавлено новое значение откуда оплата: Авангард по карте
выставляем это значение если была оплата по карте через авангард
> 4030 Обновил логику установки откуда оплата при работе через СБП

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/FastPayments/FastPayment.cs
- VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
Оставляем прежнюю логику для нового значения: отправляем чеки и выставляем ВВ Север
> 4030 убрал возможность выставления нового значения при создании заказа

- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
Откатил учёт неиспользованных тмц от обычных заказов для экспресс-доставки в талоне погрузки
> Revert returns reception view fix

- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Domain/Orders/OrderItem.cs
- VodovozBusiness/HibernateMapping/Order/OrderItemMap.cs
- VodovozBusiness/Models/Orders/CopyingOrder.cs
сделал ссылку на копируемый товар, чтобы правильно валидировать цены
> Починил валидацию перенесенного заказа

- VodovozBusiness/EntityRepositories/Logistic/RouteListItemRepository.cs
Добавил те же изменения в сам диалог переноса адресов. (В прошлый раз подправили и проверили метод побора МЛ для доставки за час, колонку Остатки запаса в мониторинге и кол-во полных бутылей на возврат в водительском приложении).
> Фикс проверки остатков для переноса заказа

- Vodovoz/Views/Logistic/RouteListsOnDayView.cs
Убрано отображение на карте заказов, которые уже добавлены в какой-либо МЛ.
> Фикс отображения маркеров заказов на карте в формировании МЛ

- VodovozBusiness/EntityRepositories/Orders/PromotionalSetRepository.cs
- VodovozViewModels/ViewModels/Counterparty/DeliveryPointViewModel.cs
> 3970 Обновил условие предупреждения дп

- VodovozBusiness/Domain/Orders/Order.cs
- VodovozBusiness/Models/Stage2OrganizationProvider.cs
- VodovozBusiness/Parameters/OrderParametersProvider.cs
- выставил валидацию на заказ с терминалом и доставкой 20.07;
- в метод подбора организации добавил проверку на дату доставки и сменил логику подбора для терминала, как типа оплаты и источника оплаты;
> 4062 Смена подбора организации для Терминала

- VodovozBusiness/Domain/Documents/CarLoadDocument.cs
- VodovozBusiness/Domain/Documents/CarUnloadDocument.cs
добавил валидацию на длину комментария для талонов погрузки/разгрузки
> Валидация длины комментария

- Jenkinsfile
- Services/Workers/EmailPrepareWorker/EmailPrepareWorker.csproj
- Services/Workers/EmailSendWorker/EmailSendWorker.csproj
- Services/Workers/EmailStatusUpdateWorker/EmailStatusUpdateWorker.csproj
Потому что версия 6.0.0 не поддерживается в unix
> System.Drawing.Common downgrade

- VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- VodovozReports/Reports/Store/NotFullyLoadedRouteLists.rdl
Фикс подсчёта количества для погрузки в отчёте по неполностью погруженным МЛ и в репозитории
> 4073 Фикс подсчёта количества для погрузки

- Vodovoz/ReportsParameters/Sales/SalesReport.cs
- Vodovoz/gtk-gui/Vodovoz.Reports.SalesReport.cs
- VodovozReports/Reports/Sales/SalesReportDetail.rdl
Подробный отчёт по продажам:
- добавлен чекбокс "С телефонами" с доступность при наличии соответствующего права;
- скрытие/отображение колонки "Телефоны" в подробном отчёте по продажам в зависимости от чекбокса.
> 4080 Скрытие/отображение колонки "Телефоны" в подробном отчёте по продажам

- VodovozBusiness/Domain/Client/DeliveryPoint.cs
- VodovozReports/Reports/Documents/Bill.rdl
> Поменял "бизнесс центр" на "бизнес-центр"

- Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Vodovoz/ViewWidgets/OrderEquipmentItemsView.cs
- VodovozBusiness/EntityRepositories/Flyers/FlyerRepository.cs
- VodovozBusiness/EntityRepositories/Flyers/IFlyerRepository.cs
- VodovozBusiness/Models/AdditionalLoadingModel.cs
- VodovozBusiness/Models/IAdditionalLoadingModel.cs
- VodovozBusiness/Tools/Orders/OrderStateKey.cs
- VodovozViewModels/ViewModels/Flyers/FlyerViewModel.cs
- смотрим активные листовки по дате доставки(заказа или МЛ);
- вызываем добавление листовок в заказ не только присмене точки доставки, но и при смене даты доставки с удалением предыдущих листовок;
- блокируем активацию листовок на сегодняшний день;
> 4096 изменения в логику добавления листовок

- VodovozBusiness/EntityRepositories/HistoryChanges/ArchivedHistoryChangesRepository.cs
игнорим дубли id пачки изменений
> Изменения скрипта архивации мониторинга

- Vodovoz/Views/Employees/FineView.cs
- VodovozViewModels/ViewModels/Employees/FineViewModel.cs
Автоматический расчёт суммы штрафа при вводе кол-ва литров перерасхода для штрафа сотрудника
> Расчёт суммы штрафа при вводе кол-ва литров

- Vodovoz/ViewWidgets/Store/ReturnsReceptionView.cs
Приведение unsigned к signed, чтобы можно было получать из БД отрицательные результат вычитания
> Приведение unsigned к signed для запроса в БД из талона разгрузки

- VodovozBusiness/Domain/Orders/Documents/SpecialUPDDocument.cs
- VodovozReports/Reports/Documents/UPD.rdl
- вернул скрытие печати и подписей по параметру и саму печать в УПД;
- в спец УПД всегда скрываем печать и подписи;
> Изменения по УПД

- Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
- Vodovoz/JournalViewModels/RetailCounterpartyJournalViewModel.cs
Добавил кастомную функцию подсчета общего количества строк в журналы контрагентов
> Кастомная функция подсчета кол-ва строк журнала контрагентов

- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- VodovozViewModels/Dialogs/Logistic/DeliveryShiftNode.cs
1. По умолчанию выделены все в столбце со временем.
2. Если в одном из фильтров - чекбокс-листов не отмечено ни одного значения, то в результатах пусто
> Фикс фильтров в Формировании МЛ

- Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- VodovozViewModels/Dialogs/Logistic/DeliveryShiftNode.cs
This reverts commit 784b218a795789646a392b39321666e1688a4d59.
> Revert "Фикс фильтров в ФОрмировании МЛ"

- Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
Если последний обрабатываемый платеж, без qr кода, то отменяем его и получаем свежий иначе скидываем какой есть
> Исправление СБП

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
Убран запрет на выбор типа оплаты "Контрактная документация" после 01.11.22
> Убран запрет на выбор типа оплаты "Контрактная документация"

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
Не выводим из оборота в ЧЗ заказы с формой оплаты Контрактная документация
> 4140 TrueMarkApi - исключение контрактной документации

- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
Изменен диалог контрагента
Теперь редактируемость поля "Количество дней отсрочки:" зависит от права на установку галочки "Сеть".
Посе "Количество дней отсрочки:" теперь видимо всегда
> 4168 Задержка платежа

- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.CounterpartyDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Counterparty/CounterpartyMap.cs
- добавлен новый признак "Не смешивать в одном заказе маркированные и немаркированные товары" клиенту;
- добавлена валидация заказа и запрет создания заказа у которого есть маркированные и немаркированные позиции для клиента с новым параметром;
> 4140 Добавление нового параметра для контрагента

- Source/Applications/Desktop/Vodovoz/Dialogs/Cash/CashExpenseDlg.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.CashExpenseDlg.cs
Изменен диалог расходного ордера
Изменено расположение надписи Текущий баланс сотрудника
Увеличен шрифт текста
> 4157 - Баланс Сотрудника

- Source/Libraries/Core/Business/VodovozBusiness/Models/Orders/CopyingOrder.cs
убираем установку пользовательской цены, если копируем заказ через журнал
> Исправление повтора заказа из журнала

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Employees/FineViewModel.cs
Исправление FineViewModel
Добавлена подписка на изменение FineReasonString, для оповещения об изменении FineViewModel.FineReasonString
> 4149 - Исправить отображение причины штрафа

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/FastPaymentsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/OrdersController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/PushNotificationsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RegistrationsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RouteListsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/SmsPaymentsController.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/DriverComplaintModel.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/DriverMobileAppActionRecordModel.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/IDriverMobileAppActionRecordModel.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/OrderModel.cs
Добавлена асинхронность для вызова GetUser
Методы использующие GetUser преобразованы в асинхронные
Частично почищен стиль кода
Частично логирование преобразовано к объектному
> Оптимизация и стиль кода

- Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/UndeliveredOrdersPanelView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/UndeliveredOrdersJournalViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/AnalyticsForUndelivery.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Orders/UndeliveriesWithComments.rdl
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/GuiltyInUndelivery.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Undeliveries/UndeliveredOrdersRepository.cs
По аналогии с задачей 4058
Добавлен ответственный Директор ЛО (Доставка в тот же день)
> 4156 Добавлен новый ответственный в рекламации

- Source/Applications/Backend/WebAPI/DeliveryRulesService/Controllers/DeliveryRulesController.cs
- Source/Applications/Backend/WebAPI/DeliveryRulesService/DeliveryRulesService.csproj
- Source/Applications/Backend/WebAPI/DeliveryRulesService/Properties/launchSettings.json
Изменена сортировка интервалов доставки в ответе API
> 4175 Сортировка интервалов

- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/OrderFilterView.cs
- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/OrderJournalFilterViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/MainWindow.cs
- Source/Applications/Desktop/Vodovoz/TempAdapters/OrderSelectorFactory.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/UndeliveredOrderView.cs
- Source/Applications/Desktop/Vodovoz/Views/Complaints/ComplaintView.cs
- Source/Applications/Desktop/Vodovoz/Views/Complaints/CreateComplaintView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.OrderFilterView.cs
- Source/Applications/Desktop/Vodovoz/toolbars/ToolbarActions.cs
Убрана строка поиска в заказе.
Добавлены 2 поля фильтра:
- Номер онлайн заказа
- Автор заказа
> 4152 Переработка поиска в журнале заказов

- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/OrderFilterView.cs
- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/OrderJournalFilterViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/OrderJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.OrderFilterView.cs
Изменение вида фильтра заказов
Изменение поиска заказов в журналах для новых полей
> 4152 Хотфикс поиска по журналам заказов

- Source/Applications/Desktop/Vodovoz/ReportsParameters/Logistic/DeliveriesLateReport.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Reports.Logistic.DeliveriesLateReport.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/DeliveriesLate.rdl
Добавлена возможность расчёта интервала от времени попадания заказа в первый МЛ
> 4188 Новый фильтр в отчёте по опозданиям

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/Complaint.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/ComplaintDiscussion.cs
Изменены:
- Complaint
- ComplaintDiscussion
> Чистка кода

- Source/Applications/Backend/WebAPI/TaxcomEdoApi/Converters/ParticipantDocFlowConverter.cs
> если стоит грузополучател из ТД берем shortAddress

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
В валидацию заказа добавлена проверка на дату доставки, теперь она не может быть более текущей даты плюс 30 дней
> 4192 - Валидация даты доставки заказов

- Source/Applications/Backend/WebAPI/DriverAPI/Middleware/JsonExceptionMiddleware.cs
Теперь на ошибки внутренней логики назначен код ответа 200 Ок
> 4197 - Временное решение по избавлению от флуда от мобильных приложений

- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/ComplaintFilterView.cs
- Source/Applications/Desktop/Vodovoz/Views/Complaints/ComplaintDiscussionView.cs
- Source/Applications/Desktop/Vodovoz/Views/Complaints/ComplaintDiscussionsView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Complaints/ComplaintFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Complaints/ComplaintDiscussionViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Complaints/Complaints.rdl
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/Complaint.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/ComplaintDiscussion.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/ComplaintDiscussionStatuses.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Complaints/ComplaintStatuses.cs
- Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Complaints/ComplaintDiscussionMap.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/ISubdivisionParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/SubdivisionParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
- Добавлен новый статус "Ожидает реакции"
- Статус автоматически изменяется следующим образом:
- Если статус одной из вкладок сменился на "На проверке" хотя бы у одного отдела, вовлеченного в рекламацию, то общий статус рекламации становится "Ожидает реакции"
- Если статусы по всем отделам "Закрыт", то общий статус "На проверке" 
- Иначе статус "В работе"
- Новый статус добавлен в отчеты, где используется статус рекламации
> 4190 - Изменения в обработке рекламаций

- Source/Applications/Desktop/Vodovoz/Dialogs/Cash/CashTransfer/CommonCashTransferDocumentViewModel.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Cash/CashTransfer/IncomeCashTransferDocumentViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Cash/OrganizationCashTransferDocumentViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/CashTransfer/CashTransferDocumentBase.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/Expense.cs
В РКО/ПКО теперь копируется как основание комментарий из документа перемещения ДС, а так же кассир в поле сотрудника
> 4194 - Комментарий из перемещений ДС

- Source/Libraries/Core/Backend/FastPaymentsAPI.Library/Models/FastPaymentModel.cs
обновляем сущность быстрого платежа, пришедшего с коллбэка перед обновлением статуса
> Обновление СБП

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Client/SummaryBottlesAndDeposits.rdl
Добавлено условие для отображения отсутствующего значения
> 4205 - Правка акта по бутылям и залогам

- Source/Applications/Desktop/Vodovoz/Additions/AuthorizationService.cs
- Source/Applications/Desktop/Vodovoz/Factories/AuthorizationServiceFactory.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/ISubdivisionParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/SubdivisionParametersProvider.cs
добавил новый параметр для HR подразделения
выдаем роль с админскими опциями для HR'ов и ОРСУ при создании нового пользователя
> Доработал выдачу роли при создании нового пользователя

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Payments/PaymentsFromTinkoffReport.rdl
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Payments/PaymentByCardOnline.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Payments/PaymentsFromYookassaParser.cs
добавлен новый параметр для парсинга выписки с нового магазина
> Обновление парсера по Юкассе

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
Добавлена валидация длины:
- комментария ОП/ОСК
- комментария ОДЗ
> Добавлена валидация при сохранении заказа

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/CarsExploitationReportViewModel.cs
Переименование в спасательном круге отчёта по аналитике эксплуатации ТС
> Переименование в спасательном круге

- Source/Applications/Desktop/Vodovoz/Representations/CallTasksVM.cs
добавил фильтр, чтобы автоматически проставлялось расширение, если пользователь его не ввел
> Исправление экспорта журнала задач

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Payments/UnallocatedBalancesJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Payments/ManualPaymentMatchingViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.Report.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/NHibernateProjections/Goods/ProductGroupProjections.cs
- Source/Libraries/Core/Business/VodovozBusiness/NHibernateProjections/Orders/OrderProjections.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
- Source/Libraries/External/DateTime/DateTimeHelpers/DateTimeExtensions.cs
Оптимизирован отчет по продажам с динамикой
> 4237 - Оптимизация отчета по продажам с динамикой

- Source/Libraries/External/DateTime/DateTimeHelpers/DateTimeSliceFactory.cs
Исправлено формирование слайса недель на год
> Фикс слайсов недель

- Source/Applications/Desktop/Vodovoz/JournalViewers/ProductGroupView.cs
- Source/Applications/Desktop/Vodovoz/Representations/ProductGroups/NomenclatureNode.cs
- Source/Applications/Desktop/Vodovoz/Representations/ProductGroups/ProductGroupVM.cs
- Source/Applications/Desktop/Vodovoz/Representations/ProductGroups/ProductGroupVMNode.cs
- добавил валидацию на циклическую ссылку при переносе в другую группу товаров;
- убрал виртуальную папку номенклатур группы;
> 4234 Обновление журнала групп товаров

- Source/.editorconfig
Убирает обработку варнингов для генерированных файлов
> EditorConfig Generated Code

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.Report.cs
Убрано заполнение даты последней продажи, если нет строк для отображения в отчете
> Фикс отчета по продажам с динамикой

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/CommonIncomeBalance.rdl
> Повышен таймаут для отчета

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.cs
> Хотфикс - отчет по оборачиваемости с динамикой

- Source/Applications/Desktop/Vodovoz/CreateProjectParam.cs
> Регистрация ILogger<> в Autofac

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/CounterpartyRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/ICounterpartyRepository.cs
Для создаваемого контрагента выполняется проверка на наличие не архивного контрагента с таким же номером телефона.
> 4252 Проверка дублирования контактного телефона у новых контрагентов

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/DeliveriesLate.rdl
поменял условие: отсекаем всех водителей фур, вместо фур компании при выбранном фильтре
> Исправление отчета по опозданиям

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
Увеличен таймаут детализированного отчета по продажам
> Хотфикс - отчет по продажам (детализированный)

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
Увеличение таймаута отчета по продажам
> SalesReport Timeout

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/RouteList/CarLoadDocument.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Store/CarLoadDocument.rdl
в печатной форме погрузочника в таблице оборудования выводим нименование номенклатуры, вместо оф названия
> Фикс печатной формы погрузочного талона

- Source/Applications/Desktop/Vodovoz/TempAdapters/OrderSelectorFactory.cs
> Фикс автоселектора

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
открываем диалоги в новых вкладках вместо слайдера
> Исправление журнала рекламаций

- Source/Applications/Backend/WebAPI/TaxcomEdoApi/Services/AutoSendReceiveService.cs
- Source/Applications/Backend/WebAPI/TaxcomEdoApi/Services/ContactsUpdaterService.cs
- Source/Applications/Backend/WebAPI/TaxcomEdoApi/Services/DocumentFlowService.cs
обновил логику смены статуса согласия по ЭДО и сдвинул вправо на три месяца дату выборки доков с ноября, плюс мелкие правки по логированию
> Обновление ТакскомЭдо апи

- Source/Applications/Desktop/Vodovoz/Views/Logistic/RouteListsOnDayView.cs
Доп.маркер наличия нескольких заказов рядом в формировании МЛ, разведение друг от друга близких по координатам адресов на карте
> 4278 Доп.маркер наличия нескольких заказов рядом в формировании МЛ

- Source/Applications/Backend/WebAPI/VodovozMangoService/Extensions/DapperExtensions.cs
- Source/Applications/Backend/WebAPI/VodovozMangoService/HostedServices/NotificationHostedService.cs
- Source/Applications/Backend/WebAPI/VodovozMangoService/Services/CallerService.cs
- Source/Applications/Backend/WebAPI/VodovozMangoService/Services/ICallerService.cs
- Source/Applications/Backend/WebAPI/VodovozMangoService/Startup.cs
- Source/Applications/Backend/WebAPI/VodovozMangoService/VodovozMangoService.csproj
Заменен контейнер входящих звонящих
Добавлена логика переотправки запроса
> Хотфикс - Манго

- Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
- Source/Applications/Desktop/Vodovoz/CreateProjectParam.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/ClosedRouteList.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/RouteList.rdl
Комментарий перенесён из колонки в строку и другие исправления внешнего вида печатной формы МЛ.
> 4269 Изменения внешнего вида МЛ

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Сделал отдельный метод валидации быстрой доставки, чтобы при подтверждении заказа выдавалось нормальное сообщение вместо ошибки
> Обновление валидации быстрой доставки

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/NomenclatureParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/INomenclatureParametersProvider.cs
Добавлено открытие диалога заказа на забор из посуточной аренды
> 4260 - Новый диалог заказа для забора из посуточной аренды

- Source/Applications/Backend/WebAPI/TaxcomEdoApi/Factories/EdoUpdFactory.cs
хардкодим данные подписанта, т.к. не всегда эта инфа есть в сертификате
> Обновление формирования УПД по ЭДО

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
вызываем добавление комментариев из ТД при создании нового заказа из Манго
> Правка диалога заказа

- Source/Applications/Backend/WebAPI/VodovozMangoService/Services/CallerService.cs
> Фикс манго

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/CounterpartyRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/ICounterpartyRepository.cs
При валидации номера телефона при сохранении карточки контрагента, при нахождения дубля в точке доставки будет отображаться номер точки доставки
> Hotfix Отображение адреса точки доставки при валидации номера телефона

- Source/Applications/Backend/WebAPI/DriverAPI/Startup.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Goods/TransferGoodsBetweenRLDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListKeepingDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/UndeliveryOnOrderCloseDlg.cs
- Source/Applications/Desktop/Vodovoz/ViewModels/Mango/WidgetsModel/CounterpartyOrderViewModel.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListClosingItemsView.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/OrderModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/AddressTransferDocumentController.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/IRouteListAddressKeepingDocumentController.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/RouteListAddressKeepingDocumentController.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/DeliveryFreeBalanceTransferItem.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteList.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteListItem.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrderItem.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Правка для операции для МЛ без погрузки (с переносом в новый из рук в руки)
Редактирование заказов на кассе, перенос разгрузки, перенос создания операций свободных остатков в смены статусов, Переделка операций перемещения товаров, рефакторинг
Свободные остатки в диалоге переноса разгрузки
Операции свободных остатков в диалогах работы кассы с заказами
Исправлены ошибки после тестирвания
> 4072 Доработки

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Complaints/ComplaintViewModel.cs
> Хотфикс - исправление закрытия рекламации без итога работы по сотруднику

- Jenkinsfile
Убрано использование powershell
> Хотфикс - исправление пайплайна сборки

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseDocumentsItemsJournalViewModel.cs
Исправлено количество в документе перемещения при принятии расхождения
> Хотфикс - исправление журнала строк складских документов

- Jenkinsfile
> Хотфикс - Jenkins Pipeline замена слешей

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Store/WarehouseDocumentsItemsJournalViewModel.cs
Исправлена сортировка в выгрузке журнала
> Хотфикс - Журнал строк складских документов (сортировка выгрузки)

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
добавил смену типа адреса при повторе заказа из Манго и сделал обновление только UI без  значения при загрузке заказа
> скорректировал обновление типа адреса в карточке заказа

- Source/Applications/Desktop/VodovozViewModels/Dialogs/Complaints/ComplaintsJournalsViewModel.cs
Исправлено подключение инфо-панели  к новому журналу
> Хотфикс - исправление подключение инфо-панели к журналу рекламаций

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteList.cs
Фикс отображения тары, отличной от пустых бутылей по-умолчанию, в расхождеиях МЛ
> Фикс отображения остальной тары

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/FastPaymentsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/OrdersController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RegistrationsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RouteListsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/SmsPaymentsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/ChangeOrderPaymentTypeRequestDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/CompletedOrderRequestDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/OrderQRPaymentStatusResponseDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/OrderScannedItemDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/PayByQRRequestDTO.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/PayBySmsRequestDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/RollbackRouteListAddressStatusEnRouteRequestDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/DTOs/RouteListAddressCoordinateDto.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Middleware/RequestResponseLoggingMiddleware.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/DriverActionDto.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/IActionTimeTrackable.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/OrderDto.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/TrackCoordinateDto.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Helpers/ActionTimeHelper.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Helpers/IActionTimeHelper.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/TrackPointsModel.cs
Добавлен обработчик времени из запроса:
- принимает время в формате Utc и локальное
> 4334.1 - Подготовка к переходу на время Utc в запросах

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/CounterpartyRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/ICounterpartyRepository.cs
Изменен запрос поиска дублей телефонных номеров.
> Hotfix/4338 Ускорение поиска дублей телефонных номеров

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/AccountController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/DriverComplaintsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/FastPaymentsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/OrdersController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/PushNotificationsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RegistrationsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/RouteListsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/SmsPaymentsController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/TokenController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/ValuesController.cs
> 4337.1 - Версии api, часть 1

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrderItem.cs
Фикс ошибки индекс вне диапазона
Фикс не обновления цен при изменении способа доставки
> Фиксы по 4317

- Source/Applications/Desktop/Vodovoz/MainWindow.cs
- Source/Applications/Desktop/Vodovoz/Properties/AssemblyInfo.cs
Теперь при сборке будут добавлены 3 и 4я цифра версии автоматически
Добавлен механизм вычисления даты сборки в заголовок окна на базе версии сборки
> Хотфикс - исправление версии сборки

- Source/Applications/Desktop/Vodovoz/gtk-gui/MainWindow.cs
> Хотфикс - ширина основного окна

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V1/AccountController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V1/PushNotificationsController.cs
Скрыты технические эндпоинты из документации Swagger
> Хотфикс DriverAPI

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Проверка контактного номера телефона в диалоге заказа при его изменении из другого диалога
> Очистка контактного номера телефона при изменении

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/ProductionWarehouseMovementReport/ProductionWarehouseMovementReport.cs
Значения из перемещений из столбца принято, а не отправлено.
> 4343 Изменение отчета по ЗБН

- Source/Applications/Desktop/Vodovoz/Additions/Logistic/PrintRouteListHelper.cs
- Source/Applications/Desktop/Vodovoz/Additions/Logistic/RouteListPrintableDocs.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/PrintRouteDocumentsDlg.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Dialogs.Logistic.PrintRouteDocumentsDlg.cs
- Source/Applications/Desktop/VodovozViewModels/Infrastructure/Print/RouteListPrintableDocuments.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/ForwarderReceipt.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Vodovoz.Reports.projitems
Добавлен новый тип документа "Экспедиторская расписка"
В расписку автоматически добавляются данные МЛ - номер и дата, а также данные водителя - ФИО и номер телефона.
Расписку можно распечатать из диалога создания МЛ и из диалога групповой печати МЛ (только для МЛ с быстрой доставкой)
> 4355 Печать экспедиторской расписки вместе с МЛ

- Source/Applications/Desktop/VodovozViewModels/Dialogs/Counterparty/DeliveryPointViewModel.cs
Добавлена запятая после названия района города
> 4369 Хотфикс Правка определения координат по адресу

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/WayBillReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/WayBillReportOneDayGroupPrint.rdl
В шаблоне отчета одиночной печати путевых листов адрес изменен.
В шаблоне групповой печати путевых листов адрес первой точки берется из адреса подразделения водителя в БД. Но шаблон тоже немного поправлен, чтобы результат выглядел аналогично одиночной печтати.
> 4370 Хотфикс. Смена адреса в путевом листе

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
Обернул в try finally для создания операций при неудачной попытке сохранения истории изменений или другой ошибке
> Фикс подтверждения МЛ

- Source/Applications/Desktop/Vodovoz/JournalViewers/TasksView.cs
- Source/Applications/Desktop/Vodovoz/Representations/CallTasksVM.cs
Оптимизация изменений в журнале и убрано лишнее чтение нод журнала
> Оптимизация изменений в журнале задач

- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/CounterpartyJournalFilterViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
Добавлена обработка конфигурации фильтра снаружи
Реализован интерфейс у фильтра
> Техническое - журнал Контрагентов

- Jenkinsfile
Сборка jenkins sms infromer, sms payment, mango.
> 4331 Jenkins

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Cash/CashReceiptRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Cash/ICashReceiptRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/CounterpartyContractRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/ICounterpartyContractRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/Stage2OrganizationProvider.cs
Обнуляем не нужные чеки если сменился договор
Не меняем договор если есть нужные чеки
> Новая логика подбора договора с чеками

- Source/Applications/Desktop/Vodovoz/MainWindow.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/MainWindow.cs
Ссылка добавлена в верхнее меню: "Отчеты - Склад - Остатки"
> Хотфикс. 4392 Добавлена ссылка на отчет "Остатки" в верхнее меню

- Source/Libraries/Core/Backend/DriverAPI.Library/Deprecated/Models/OrderModel.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/Models/OrderModel.cs
Исправлена логика для формирования списка возможных для смены типов оплаты
> Хотфикс - DriverAPI - неучтенные типы оплаты

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/ISelfDeliveryCashOrganisationDistributor.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/Income.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/SelfDeliveryCashOrganisationDistributor.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Исправлены заголовки методов принимающие CallTaskWorker
Создан интерфейс для SelfDeliveryCashOrganizationDistributor
> Техническое - исправления

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/IRouteListAddressKeepingDocumentController.cs
- Source/Libraries/Core/Business/VodovozBusiness/Controllers/RouteListAddressKeepingDocumentController.cs
Добавлен параметр необходимости обновления МЛ при создании операций по свободным остаткам.
> Добавлен параметр необходимости обновления МЛ

- Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/CarsMonitoringInfoPanelView.cs
Заказы, время на доставку которых >= 50 мин выделяются зеленым в боковой панели мониторинга.
> 4412 Выделение новых заказов в мониторинге зеленым цветом

- Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/PaymentsFromJournalRegistrar.cs
- Source/Applications/Desktop/Vodovoz/Views/Orders/PaymentFromView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Views.Orders.PaymentFromView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/PaymentsFromJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Orders/PaymentFromViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Payments/PaymentsFromAvangardReport.rdl
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/PaymentFrom.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Cash/CashReceiptRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Organizations/OrganizationRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Order/PaymentFromMap.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/Stage2OrganizationProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/OrderParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/IOrderParametersProvider.cs
- добавлен новый источник оплаты Кулер Сэйл
- обновлена логик использования организации в источнике оплат, теперь она доступна для всех позиций, а не только для Авангарда. И организация подбирается исходя из этой установки
> 4415 добавление нового источника Кулер Сэйл

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReportDetail.rdl
Таймаут запросов в отчете по продажам с рентабельностью установлен 120 сек.
Таймаут запросов в детализированном отчете по продажам с рентабельностью установлен 180 сек.
> Хотфикс. Изменен таймаут выполнения запросов отчетов по продажам с рентабельностью

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/WayBillReportOneDayGroupPrint.rdl
Добавлено ограничение для версии авто, соответствующей дате путевого листа и сортировка по фамилии водителя
> Хотфикс. Дублирование водителей в групповой печати путевого листа

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/CostCarExploitationReportViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/CarEventRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/ICarEventRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Убрана зависимость от галочки "не отражать в эксплуатации ТС"
> Хотфикс отчета Затраты при эксплуатации ТС

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/RouteListOnClosing.rdl
При расчете нала по МЛ суммируется выданная под отчет сумма наличных
> Хотфикс. Исправлен расчет нала по МЛ в отчете

- Source/Applications/Desktop/Vodovoz/Views/Users/UserView.cs
Исправлена подписка в случае выбора пользователя без сотрудника
> Хотфикс - UserViewModel

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
Обновление подразделения при открытии вкладки
> Хотфикс - заявка на выдачу ДС

- Source/Applications/Desktop/VodovozViewModels/Cash/DocumentsJournal/DocumentsJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseViewModel.cs
Исправлено получение РКО при копировании
> Хотфикс - копирование РКО

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
Добавлена возможность ручной переотправки УПД для заказов с доставкой более месяца назад
> Хотфикс.  Ручная переотправка УПД

- Source/Applications/Desktop/VodovozViewModels/Infrastructure/Report/SelectableParametersFilter/SelectableParameter.cs
- Source/Applications/Desktop/VodovozViewModels/Infrastructure/Report/SelectableParametersFilter/SelectableParameterSet.cs
This reverts commit b5d44d19886044f708e92abb86796978cf399b9a.
> Revert "Исправлен порядок фильтрации потомков"

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Cash/CashFlowDetail.rdl
CashFlowDetail
Исправлено используемое поле для определения категории
> Хотфикс - отчет доходы и расходы детализированный

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Counterparties/CounterpartyContractRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/Stage2OrganizationProvider.cs
Исправлено получение контракта для:
- МП водителя
- Sms QR
> Хотфикс подбора договора

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/PrintRouteDocumentsDlg.cs
- Source/Applications/Desktop/Vodovoz/Views/Logistic/RouteListsOnDayView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Dialogs.Logistic.PrintRouteDocumentsDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/IRouteListRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
так же добавлен фильтр в массовой печати: только не распечатанные мл
> 4428 Исправлена подсказка в формировании мл

- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/DebtorsFilterView.cs
- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/DebtorsJournalFilterViewModel.cs
- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/DebtorsTaskStatus.cs
- Source/Applications/Desktop/Vodovoz/Representations/DebtorsJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/DeliveryPointsManagementView.cs
- Source/Applications/Desktop/Vodovoz/Vodovoz.csproj
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.DebtorsFilterView.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/DeliveryPoint.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/EntranceType.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/RoomType.cs
- Source/Libraries/Core/Business/VodovozBusiness/HibernateMapping/Counterparty/DeliveryPointMap.cs
- Source/Libraries/Core/Business/VodovozBusiness/Permissions/Email.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Добавлен фильтр
Добавлен подзапрос
Добавлено свойство для точки доставки и его отображение
> 4382 - Новый фильтр в журнал задолженности

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.RouteListActions.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.RouteListPrintDocuments.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListCreateDlg.cs
- Source/Applications/Desktop/Vodovoz/JournalFilters/RouteListsFilter.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RouteListWorkingJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/MainWindow.cs
- Source/Applications/Desktop/Vodovoz/Vodovoz.csproj
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Cash/PayoutRequestJournalFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Employees/EmployeeFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Logistic/RouteListJournalFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Cash/PayoutRequestsJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Employees/TerminalManagementViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Permissions/Cash.cs
Заблокировано редактирование МЛ в диалоге закрытия, если МЛ был уже подтвержден кассой и находится не в статусе (Доставлен, Сдается)
> 4383 - Хотфикс - Блокировка изменения в диалоге закрытия

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/DeliveriesLate.rdl
Добавлена таблица выше основной с требуемыми показателями
> 4429 - Дополнение в отчет по опозданиям

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/Orders/Order.cs
Добавлено возвращение в статус доступный для редактирования при провале подтверждения
> Хотфикс - возврат статуса заказа при неудачной операции

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Employees/Employee.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Goods/Nomenclature.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Goods/NomenclatureCategory.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/DiscountReason.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/PromotionalSet.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Organizations/Organization.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Sale/GeoGroup.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Subdivisions/Subdivision.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Добавлены недостающие интерфейсы у ряда сущностей
> Интерфейсы для сущностей

- Source/Applications/Backend/WebAPI/FastPaymentsAPI/Startup.cs
- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/EmailPrepareWorker.cs
- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/Program.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Client/ContactDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Applications/Desktop/Vodovoz/Views/Contacts/EmailsView.cs
- Source/Applications/Desktop/Vodovoz/toolbars/ToolbarActions.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForDebtViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForPaymentViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Contacts/EmailsViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/VodovozViewModels.csproj
- Source/Applications/Frontend/UnsubscribePage/Startup.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Contact.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/Counterparty.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Cash/CashRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/EmailParametersProvider.cs
- Source/Libraries/Core/Business/VodovozBusiness/Parameters/IEmailParametersProvider.cs
- добавил вью модель под виджет электронной почты
- добавил логику установки первой почты для физиков Для чеков
- перевел EmailsParametersProvider на SettingsController
> 4456 добавил вьюмодель для виджета электронки + логика по задаче

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/RouteListRepository.cs
Фикс отправки МЛ в путь после погрузки с перенесённым в него заказом с доставкой за час с допогрузкой на складе
> Фикс отправки МЛ в путь после погрузки

- Source/Applications/Desktop/Vodovoz/Cash/Reports/CashFlowAnalysisView.ReportLine.cs
- Source/Applications/Desktop/Vodovoz/Cash/Reports/CashFlowAnalysisView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Cash.Reports.CashFlowAnalysisView.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/Reports/CashFlowAnalysisViewModel.CashFlowDdsReport.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/Reports/CashFlowAnalysisViewModel.cs
Доработан отчет ДДС
- добавлена галочка "Не отображать статьи без документов за период"
- при указании добавленной галочки - в отчете скрываются статьи и группы без документов за заданный период
> 4465 - Скрывать пустые статьи в ДДС

- Source/Applications/Desktop/Vodovoz/Views/Logistic/DriversStopListsView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Views.Logistic.DriversStopListsView.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/DriversStopLists/DriversStopListsViewModel.DriverNode.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/DriversStopLists/DriversStopListsViewModel.DriversSortOrder.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/DriversStopLists/DriversStopListsViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/VodovozViewModels.csproj
Добавлена возможность выбора сортировки водителей в таблице "Текущее состояние" в диалоге снятия стоп-листа
> 4475 Хотфикс Сортировка водителей в диалоге снятия стоп-листа

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/FastDelivery/FastDeliveryAdditionalLoadingReportViewModel.FastDeliveryRemainingBottlesReport.cs
Отчет переименован в
Отчёт по остатку бутылей от доставки за час
> Переименование отчета

- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/CounterpartyFilterView.cs
- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/DeliveryPointJournalFilterView.cs
- Source/Applications/Desktop/Vodovoz/Filters/ViewModels/CounterpartyJournalFilterViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailCounterpartyJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.CounterpartyFilterView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.DeliveryPointJournalFilterView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/DeliveryPointJournalFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Client/DeliveryPointByClientJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Client/DeliveryPointJournalViewModel.cs
В фильтры журналов контрагентов и точек доставки добавлены новые поля для фильтрации списка
> 4487 Переработка поиска в журнале контрагентов и журнале точек доставки

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReportDetail.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
фикс выборки для отчетов по типам оплаты
> Хотфикс - отчеты по продажам

- Source/Applications/Backend/Workers/Docker/PushNotificationsWorker/Properties/PublishProfiles/FolderProfile.pubxml
> Смена папки публикации

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Исправлена автоматическая отправка счета, теперь отправляется счет для текущего заказа.
> Хотфикс - исправление отправки счета

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/AtWorksDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/AtWorkBase.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/AtWorkDriver.cs
- исправлена подписка при выборе водителей
- доблено окно подтверждения пере добавлением всех работающих водителей
- восстановлена работа кнопки снять (не заполнялись данные в ноде, кнопка отрабатывала корректно)
> Хотфикс диалог Логистика-На работе

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.cs
Фильтр для продаж без остатков по архивным номенклатурам
> Хотфикс - отчет по продажам с динамикой

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/Bill.rdl
Изменены z-индексы подписей и печати
> Хотфикс. Фикс перекрытия подписей и печати в шаблоне счета

- Source/Applications/Desktop/VodovozViewModels/Cash/AdvanceReportViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseSelfDeliveryViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/IncomeSelfDeliveryViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Cash/IncomeViewModel.cs
> Хотфикс - ошибки кассовых документов

- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Common/IncludeExcludeEntityFilter.cs
> Хотфикс - Фильтр выбора/исключения

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
Оптимизирован отчет по продажам, отчет по продажам детализированный
> Хотфикс - Оптимизация запросов отчетов по продажам

- Source/Applications/Desktop/Vodovoz/PricesView.cs
исправил виджет цен номенклатуры:
- поставил минимальное количество 1;
- включил числовой режи, чтобы количество корректно отображалось в виджете
> ставим минимум 1 в количестве и включаем числовой режим

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/TrueMark/ProductCodesScanningReport.Row.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/TrueMark/ProductCodesScanningReport.ScannedCodeInfo.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/TrueMark/ProductCodesScanningReport.cs
В отчет о сканировании маркировки добавлены данные о принадлежности ТС и площадка (юг/север)
> 4538 Изменение отчета о сканировании маркировки

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Subdivisions/Subdivision.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Subdivisions/SubdivisionType.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
- Source/Vodovoz.Data.NHibernate/HibernateMapping/Subdivisions/SubdivisionMap.cs
Приведен к единому стилю кода
Исправлены устаревшие вызовы на новые
Рефакторинг методов
Вынесен класс типов
Добавлены аннотации к типу
> Техническое - рефакторинг класса подразделений

- Source/Applications/Backend/WebAPI/TrueMarkApi/Controllers/TrueMarkApiController.cs
- Source/Libraries/Core/Backend/TrueMarkApi.Library/Dto/ProductInstanceStatus.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/TrueMark/TrueMarkWaterCodeParser.cs
Исключение кода \u001d из serialNumber, gtin, check.
Исправлена проблема пакетной обработки.
> 4519 Проблемный код честного знака

- Source/Applications/Desktop/VodovozViewModels/ReportsParameters/SalesReportViewModel.cs
> Хотфикс - Оптимизация отчета по продажам

- Source/Applications/Desktop/Vodovoz/Views/Client/ExternalCounterpartyMatchingView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Views.Client.ExternalCounterpartyMatchingView.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Counterparty/ExternalCounterpartyMatchingViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/ExternalCounterpartyMatching.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Client/ExternalCounterpartyMatchingStatus.cs
- добавил кнопку Юр лицо в сопоставление пользователей из внешних источников;
> добавил кнопку Юр лицо с соответствующим статусом

- Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Profitability/ProfitabilitySalesReportViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports.Editing/ModifierActions/NewTableGroupWithCellsFromDetails.cs
- Source/Libraries/Core/Business/Vodovoz.Reports.Editing/ModifierActions/SetColumnWidth.cs
- Source/Libraries/Core/Business/Vodovoz.Reports.Editing/Modifiers/ProfitabilityReportModifier.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReport.rdl
- Source/Libraries/Core/Infrastructure/Vodovoz.RDL/Elements/SortBy.cs
- Source/Libraries/Core/Infrastructure/Vodovoz.RDL/SortExpression.cs
В отчете по продажам с рентабельностью при выборе группировки по маршрутному листу отображается также тип и принадлежность авто.
> 4512 Доработка отчета по продажам с рентабельностью

- Source/Applications/Desktop/Vodovoz/Views/Client/DeliveryPointView.cs
Если точка доставки не новая - спрашивать о смене координат
> Хотфикс - смена координат на карте

- Source/Applications/Desktop/VodovozViewModels/Widgets/Cars/CarModelSelection/CarModelSelectionFilterViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Settings.Database/Car/CarSettings.cs
- Source/Libraries/Core/Business/Vodovoz.Settings/Car/ICarSettings.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Cars/CarModel.cs
Также атрибут Display name "Грузовой (газель)" енума типа авто был изменен на "Грузовой"
> 4582 Добавить модель авто Газель 3 в начало списка в фильтре выбора моделей

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Users/UserSettingsViewModel.cs
Предустановленное право IsCashier
> Хотфикс - настройки пользователя

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
> Хотфикс - отчеты по продажам (финансовый формат)

- Source/Applications/Desktop/Vodovoz/Infrastructure/GdkColors.cs
- Source/Applications/Desktop/Vodovoz/MainWindow.View.cs
Возвращение меню
Переключение на другую тему, теперь используется модифицированная Mint-Y-Yltra-Dark
> 4489 - Темная тема (правки)

- Source/Applications/Desktop/VodovozViewModels/Factories/LeftRightListViewModelFactory.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.Report.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.TurnoverWithDynamicsReport.OrderItemNode.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReportDetail.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
Изменена группировка тип контрагента в отчетах:
- Продаж
- Продаж с детализацией
- Рентабильности
- Рентабильности с детализацией
- Оборачиваемости с динамикой
> 4592 - Дополнения к отчетам по продажам

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
Возврат скидок до отмены и сброс актуального кол-ва
> 4597 Хотфикс - возврат отменённого заказа

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListAddressesTransferringDlg.cs
- Source/Applications/Desktop/Vodovoz/toolbars/ToolbarActions.cs
> 4598 - Хотфикс (смена статуса заказа при добавлении в МЛ через диалог переноса)

- Source/Applications/Backend/WebAPI/DeliveryRulesService/DeliveryRulesService.csproj
Без неё ломалось в некоторых методах
> Хотфикс - Добавил зависимость в службу правил доставки

- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailOrderJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrderJournalViewModel.cs
скорее всего ошибка вызвана повторным вызовом Повторить заказ из-за дребезга контактов мыши, поэтому проверяем на нулл
> проверяем на null выбранную ноду

- Source/Libraries/Core/Backend/DriverAPI.Library/Converters/OrderConverter.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/OrderSaleItemDto.cs
> 4617 - Объем тары

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Orders/OrderChangesReport.rdl
Добавлены отсутствующие типы оплаты
> 4577 - Обновление отчета по изменениям заказа при доставке

- Source/Libraries/Core/Backend/DriverAPI.Library/Converters/OrderConverter.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/OrderSaleItemDto.cs
> 4626 - цвет пробки

- Source/Applications/Desktop/Vodovoz/Views/Complaints/GuiltyItemView.cs
Исправлена видимость при показе виджета
> Хотфикс - добавление виновного (видимость поля подразделений)

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Вернул реверт 4584, исправление проблемы трекинга событий, когда в двух последовательных транзакциях меняется одна и та же сущность, добавил трекинг изменений.
> 4584 Подтверждение заказа

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/UPD.rdl
Исправлен запрос для нескольких платежей
> Хотфикс - УПД

- Source/Applications/Desktop/Vodovoz/Core/PromosetDuplicateFinder.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/PromotionalSetRepository.cs
- ищем только в заказах отличных от текущего;
- разделил поиск по телефонам отдельно по клиентам и ТД, чтобы запрос отрабатывал быстрее;
> исправил проверку халявщиков

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/UPD.rdl
Добавлено отсечение платежей по дате доставки заказа (дата УПД)
> 4656 - Подгрузка номера платежки

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Не отображать ошибку, если заказа просто не прошёл валидацию. Окно валидации и так отображается.
> 4678 Хотфикс отображения ошибки при валидации

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
Если пользователь создает новую точку доставки из диалога создания заказа, то при сохранении заказа появляется ошибка валидации - "Выбранная точка доставки у данного контрагента не найдена"
> Хотфикс. Фикс ошибка при валидации точки доставки в заказе

- Jenkinsfile
Подключена проверка серверов в сети
> Нестабильные сборки

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/Bill.rdl
поправил отображение подписей и печати
> исправление счета

- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Common/IncludeExcludeBoolParamsFilter.cs
- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Common/IncludeExludeFiltersViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Factories/IncludeExcludeSalesFilterFactory.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/Sales/TurnoverWithDynamicsReportViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/ProfitabilitySalesReportDetail.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReport.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Sales/SalesReportDetail.rdl
Доработан виджет множественного выбора для поддержки булевых свойств.
В отчёты добавлен фильтр самовывоза
> 4700 Фильтр самовывоза в отчётах

- Source/Applications/Desktop/Vodovoz/Views/Orders/DiscountReasonView.cs
Добавлено отображение идентификаторов
> Хотфикс - карточка основания скидки

- Source/Libraries/Core/Backend/DriverAPI.Library/Converters/OrderConverter.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DTOs/OrderDto.cs
Добавлено поле BottlesByStockActualCount в OrderDto
> DriverApi - BottlesByStockActualCount

- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListCreateItemsView.cs
Исправлено добавление дубликатов заказов
Исправлены подписки
> Фикс RouteListCreateItemsView

- Source/Applications/Backend/WebAPI/FastPaymentsAPI/Controllers/FastPaymentsController.cs
- Source/Applications/Backend/WebAPI/FastPaymentsAPI/Properties/PublishProfiles/FolderProfile.pubxml
Исправлен файл публикации
Исправлено не обновление QR при обновлении цены заказа
Заменены теги на сокращенные варианты
> Исправления FastPaymentApi

- Source/Libraries/Core/Backend/CustomerAppsApi.Library/Dto/PromotionalSetDto.cs
- Source/Libraries/Core/Backend/CustomerAppsApi.Library/Factories/PromotionalSetFactory.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/PromotionalSetRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Nodes/PromotionalSetOnlineParametersNode.cs
добавил новое поле для расчета доставки в выдачу для ИПЗ
> 4723 обновление CustomersApi

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Complaints/ComplaintsJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/ComplaintsJournalReport/ComplaintClassificationSummaryReport.cs
> Хотфикс - дополнения к 4639

- Source/Applications/Backend/WebAPI/DriverAPI/Options/ConfigureSwaggerOptions.cs
Исправлен отображение TimeSpan в документации Swagger
> Исправлено отображение SwaggerGen

- Source/Applications/Desktop/Vodovoz/Views/Goods/NomenclatureView.cs
- Source/Applications/Desktop/VodovozViewModels/Dialogs/Goods/NomenclatureViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Application/DependencyInjection.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Goods/INomenclatureService.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Goods/NomenclatureService.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/GenericRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/IGenericRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/Goods/Nomenclature.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
Добавлена проверка остатков номенклатуры перед ее архивацией
> 4735 - Проверка остатков перед архивацией номенклатуры

- Source/Libraries/Core/Business/Vodovoz.Application/Logistics/RouteListService.cs
- Source/Libraries/Core/Business/Vodovoz.Settings.Database/Nomenclature/NomenclatureSettings.cs
- Source/Libraries/Core/Business/Vodovoz.Settings/Nomenclature/INomenclatureSettings.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteListSpecialConditionType.cs
Добавлено 5е специальное условие
> 4761 - Новое поле в запрос GetRouteList (Хотфикс)

- Source/Applications/Desktop/Vodovoz/Dialogs/UndeliveryOnOrderCloseDlg.cs
- Source/Applications/Desktop/Vodovoz/ViewModels/Logistic/RouteListsOnDayViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListCreateViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Logistics/RouteListService.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/Logistics/RouteList.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/Logistics/IRouteListService.cs
Фикс проблем с отменёнными заказами в формировании МЛ
> 4770 Проблемы с отменёнными заказами при формировании МЛ

- Source/Applications/Desktop/Vodovoz/Views/Client/DeliveryPointView.cs
- Source/Applications/Desktop/VodovozViewModels/Dialogs/Counterparty/DeliveryPointViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Delivery/DeliveryRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Delivery/IDeliveryRepository.cs
Добавлено отображение районов в диалоге точки доставки, подсвечивание текущего точного района (по координатам, не ближайший), добавлено отображение называния района под курсором мыши, добавлено предупреждение, что подобран ближайший район при сохранении ТД.
> 4748 Районы в ТД

- Source/Applications/Backend/WebAPI/DriverAPI/DriverAPI.csproj
- Source/Applications/Backend/WebAPI/DriverAPI/Startup.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/BuildVersion/BuildVersionController.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/BuildVersion/GetVersionResponse.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Vodovoz.Presentation.WebApi.csproj
- Source/Vodovoz.sln
Добавлен проект Vodovoz.Presentation.WebApi
Подключен эндпоинт отображения версии и времени сборки в DriverApi
Добавлены параметры в csproj DriverApi для генерации версии сборки в зависимости от времени
> Версия и время сборки WebApi

- Source/Applications/Desktop/Vodovoz/Dialogs/UndeliveryOnOrderCloseDlg.cs
Была проблема, когда меняют много раз статус адреса не сохраняя
> 4770 Фикс свободных остатков в диалоге ведения

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/OrderStatisticByWeek.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/OrderStatisticByWeekWithPotentialOrders.rdl
сделал более длинным поле с отображением выбранных фильтров
> исправление отчета статистика по дням недели

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Logistic/FuelReportSummaryBasic.rdl
В суммарном отчете по выдаче топлива изменен запрос актуальной стоимости топлива
> 4787 Отчет по выдаче топлива

- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Common/ApiControllerBase.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/ErrorHandling/ErrorHandlingFilterAttribute.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/ErrorHandling/ErrorHandlingMiddleware.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Vodovoz.Presentation.WebApi.csproj
Добавлены обработчики ошибок
Добавлен базовый контроллер адаптирующий Result в ответ сервера
> 4739 - Техническое

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V4/DriverWarehouseEventsController.cs
- Source/Applications/Backend/WebAPI/LogisticsEventsApi/Controllers/WarehouseEventsController.cs
- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/CompletedDriversWarehousesEventsJournalFilterView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.CompletedDriversWarehousesEventsJournalFilterView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Logistic/CompletedDriversWarehousesEventsJournalFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Logistic/ComletedDriversWarehousesEventsJournalViewModel.cs
- Source/Libraries/Core/Backend/EventsApi.Library/Dtos/CompletedDriverWarehouseEventDto.cs
- Source/Libraries/Core/Backend/EventsApi.Library/Models/ILogisticsEventsService.cs
- Source/Libraries/Core/Backend/EventsApi.Library/Models/LogisticsEventsService.cs
- добавлен параметр фильтрации по расстоянию сканирования(меньше либо равно, больше либо равно)
- в апи передаем расстояние только при превышении значения в теле ответа, в параметре детали
> Доработки по событиям

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Т.к. при настройке биндинга срабатывает событие и дата доставки обнуляется
> Хотфикс - реверт перенесённого(объединённого) кода по самовывозу в диалоге заказа

- Source/Libraries/Core/Backend/DriverAPI.Library/AssemblyFinder.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/DependencyInjection.cs
- Source/Libraries/Core/Business/VodovozBusiness/DependencyInjection.cs
> Хотфикс - пропущенная регистрация

- Source/Applications/Desktop/Vodovoz/Cores/ViewModelWidgetResolver.cs
> Хотфикс - Исправление утечки памяти

- Source/Applications/Desktop/VodovozViewModels/Infrastructure/Report/SelectableParametersFilter/SelectableParameter.cs
> ХФ - при выделении всех нижних уровней верхний уровень выделялся, но вы выборку не попадал

- Source/Applications/Desktop/Vodovoz/ViewWidgets/DeliveryPriceView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/DeliveryRuleRowView.cs
> Хотфикс - Вывод интервалов доставки в инфопанели

- Source/Applications/Backend/WebAPI/RoboAtsService/Controllers/RoboATSController.cs
- Source/Applications/Backend/WebAPI/RoboAtsService/Requests/RequestDto.cs
> Робоатс - рефакторинг

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Cars/ArchivingReason.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Cars/Car.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Cars/CarModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/Cars/CarTypeOfUse.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteListItemWageCalculationSource.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/WageCalculation/CalculationServices/RouteList/RouteListRatesLevelWageCalculationService.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
- Source/Vodovoz.Data.NHibernate/HibernateMapping/Logistic/Cars/CarModelMap.cs
- Source/Vodovoz.Data.NHibernate/HibernateMapping/WageCalculation/WageDistrictLevelRateMap.cs
почистил классы связанные с автомобилями
> Техническое - чистка

- Source/Applications/Desktop/Vodovoz/Logistic/RouteListAddressesTransferringView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Logistic/RouteListJournalFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListTransferringViewModel.cs
- Произведен рефакторинг старого кода
- Исправлена ошибка открытия МЛ в энтри
> Рефакторинг и исправление диалога переноса адресов МЛ

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Store/ProductSpecification.cs
Почистил код и добавил историю
> Хотфикс - Спецификация продукции - история

- Source/Applications/Desktop/Vodovoz/Logistic/RouteListKeepingView.cs
- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListKeepingViewModel.cs
обновляем заказ в сессии, если его изменили в диалоге
сбрасываем параметр если при сохранении вылезла ошибка
> правка диалога ведения МЛ

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Logistic/RouteList.cs
исключаем из проверки на дубли онлайн оплат перенесенные терминалы
> обновил валидацию МЛ

- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListClosingItemsView.cs
Исправлен цвет в виджете отображения адресов используемом в закрытии МЛ
Почистил код
Убрал ненужное создание объектов по новой
> Хотфикс - исправление отображения диалога закрытия МЛ

- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Pacs/PacsDashboardViewModel.cs
- Source/Applications/Desktop/Vodovoz/MainWindow.Closing.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Pacs/OperatorService.cs
Исправлен Nullref в дешборде СКУД
Добавлена возможность выхода без завершения смены
> Хотфикс - СКУД исправление закрытия программы

- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/SendEmailMessageBuilders/SendEmailMessageBuilder.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/BillDocument.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/SpecialBill.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/SpecialUPDDocument.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/UPDDocument.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePayment.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForDebt.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrdersWithoutShipment/OrderWithoutShipmentForPayment.cs
Исправлен nullref на connectionString
Исправлено условие
> Хотфикс - автоматическая отправка документов

- Source/Applications/Backend/WebAPI/TrueMarkApi/DependencyInjection.cs
- Source/Applications/Backend/WebAPI/TrueMarkApi/Options/TrueMarkOptions.cs
- Source/Applications/Backend/WebAPI/TrueMarkApi/Program.cs
- Source/Applications/Backend/WebAPI/TrueMarkApi/Services/TrueMarkDocumentService.cs
- Source/Applications/Backend/WebAPI/TrueMarkApi/Startup.cs
- Source/Applications/Backend/WebAPI/TrueMarkApi/TrueMarkApi.csproj
Вынес в настройки интервал воркера
> ХФ Рефакторинг TrueMarkApi

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IOrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/EmailService.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/IEmailService.cs
теперь отправляем УПД по закрытию/доставки заказа, только если нет подписанных доков по ЭДО и прошло не больше трех месяцев
> Обновление логики отправки УПД по электронке

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Client/DeliveryPointByClientJournalViewModel.cs
- убрал ненужную проверку на несколько конфигураций, т.к. это сингл журнал
- кнопке Добавить внес доп условие по клиенту
> блокируем кнопку Добавить, если в фильтре сбросили клиента

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Pacs/OperatorsJournalViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Pacs/PacsDashboardModel.cs
Исправлен поиск в журнале операторов, добавлен поиск по идентификатору
Исправлена ошибка с дублями в перерывах
> Хотфикс - исправление дублей в перерывах

- Source/Applications/Desktop/Vodovoz/Views/Pacs/OperatorDetailsView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Views.Pacs.OperatorDetailsView.cs
> Хотфикс - СКУД - UI для завершения смены администратором

- Source/Applications/Backend/WebAPI/DeliveryRulesService/Controllers/DeliveryRulesController.cs
> исправил ошибку

- Source/Applications/Backend/WebAPI/LogisticsEventsApi/Properties/PublishProfiles/prod-LogisticsEventsApi.pubxml
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Security/AuthenticationController.cs
Исправлена ошибка при аутентификации
> Хотфикс - служба логистических событий

- Source/Applications/Desktop/Vodovoz/MainWindow.cs
- Source/Applications/Desktop/Vodovoz/Views/Employees/EmployeeView.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Employees/EmployeeViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/WageCalculation/EmployeeWageParametersViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Employees/Employee.cs
- Source/Libraries/Core/Business/VodovozBusiness/Permissions/Employee.cs
- Source/Libraries/Core/Business/VodovozBusiness/VodovozBusiness.csproj
перенес права по сотруднику в спец класс
добавил новое право для установки клиента в сотруднике, пользователи с этим право и правами на чтение могут проставлять клиента в карточке сотрудника
> создал новое право для установки клиента в сотруднике

- Source/Libraries/Core/Business/VodovozBusiness/Controllers/PaymentFromBankClientController.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Payments/IPaymentsRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Payments/PaymentsRepository.cs
теперь выбираем список платежей с возвратами по заказу и отменяем их при возврате заказа в работу
> исправил логику отмены возвратов оплат отмененных заказов

- Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/EdoLightsMatrixPanelView.cs
открываем карточку клиента, только если он выбран
> Исправление виджета "светофора"

- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/IOperatorAgentFactory.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/IOperatorControllerFactory.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/OperatorAgentFactory.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/OperatorControllerFactory.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/OperatorControllerProvider.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/OperatorServerAgent.cs
Упрощение зависимости от оператора
> Хотфикс - СКУД - исправление получения информации о смене

- Source/Applications/Desktop/VodovozViewModels/Cash/ExpenseViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/Expense.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/RouteListCashOrganisationDistributor.cs
Исправлен баг с МЛ при статье расхода, когда требуется МЛ
Исправлена ссылка на InteractiveService
Убрано дублирование кода
> Хотфикс - РКО - исправлена ошибка сохранения при статье, при которой требуется указание МЛ

- Source/Libraries/Core/Business/Vodovoz.Settings.Database/SettingsController.cs
> обновляем параметры не удаляя их из словаря

- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderFromOnlineOrderCreator.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/OrderItem.cs
- Source/Libraries/Core/Business/VodovozBusiness/Extensions/OrderItemExtensions.cs
вызываем полный пересчет, только после добавления товара в заказ
> Изменение пересчета стоимости воды в заказе

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Logistic/CarJournalViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/CarRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Logistic/ICarRepository.cs
Автомобили из списка исключенных из отчетов и погрузчики - исключены из отчетов (журнал автомобилей):
- Отчет по ТС
- Отчет по страховкам
В журнале автомобилей отключена подсветка (розовым) если автомобиль - погрузчик или в списке исключаемых в отчетах
> Хотфикс - исключение автомобилей

- Source/Applications/Backend/Workers/FastPaymentsNotificationWorker/NotificationHandler.cs
Замена получения репозитория на получение через Scope
> Техническое - FastPaymentsNotificationWorker - получение сервисов через Scope 

- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/EmailPrepareWorker.cs
- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/Program.cs
Исправлено на реализацию через создание скоупа
> Техническое - EmailPrepareWorker - получение сервисов через Scope

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/CarRentalContract.cs
Открытие документа вместо печати PDF
> Хотфикс - договор аренды автомобиля

- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Pacs/PacsReportsViewModel.cs
- Source/Applications/Desktop/Vodovoz.Presentation.ViewModels/Pacs/Reports/PacsMissingCallsReportViewModel.cs
- Source/Applications/Desktop/Vodovoz/ReportsParameters/PACS/PacsMissingCallsReport.cs
Переместил отчет по месту где он должен быть
> Техническое - Исправление местоположения отчета

- Source/Applications/Desktop/Vodovoz/Views/Payments/PaymentsDiscrepanciesAnalysisView.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Payments/PaymentsDiscrepanciesAnalysis/PaymentsDiscrepanciesAnalysisViewModel.OrderDiscrepanciesNode.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Payments/PaymentsDiscrepanciesAnalysis/PaymentsDiscrepanciesAnalysisViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OrderWithAllocation.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/OrderRepository.cs
Добавлено отображение и изменение цвета информации по клиенту
> 4917 Доработка сверки по КА

- Source/Applications/Desktop/Vodovoz/Dialogs/HistoryView.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Documents/OrderDocument.cs
плюс корректировка отображаемых имен полей
> исправление падения в журнале изменений

- Source/Applications/Backend/WebAPI/LogisticsEventsApi/Controllers/PushNotificationsController.cs
- Source/Applications/Backend/WebAPI/LogisticsEventsApi/LogisticsEventsApi.csproj
- Source/Applications/Backend/WebAPI/LogisticsEventsApi/Startup.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Security/AuthenticationController.cs
- Source/Libraries/Core/Backend/LogisticsEventsApi.Contracts/DriverWarehouseEventQrData.cs
- Source/Libraries/Core/Backend/LogisticsEventsApi.Contracts/EnablePushNotificationsRequest.cs
- Source/Libraries/Core/Backend/LogisticsEventsApi.Contracts/LogisticsEventsApi.Contracts.csproj
- Source/Libraries/Core/Business/Vodovoz.Core.Data/Employees/ExternalApplicationUserForApi.cs
> LogisticsEvents-PushNotifications

- Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Factories/OnlineOrderFactory.cs
если пришло без нее, но со временем от быстрой доставки
> ставим быструю доставку в онлайн заказе

- Source/Applications/Desktop/Vodovoz/Dialogs/Goods/ProductGroupDlg.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Dialogs.Goods.ProductGroupDlg.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Store/CarLoadDocument.rdl
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Goods/ProductGroup.cs
- Source/Vodovoz.Data.NHibernate/HibernateMapping/Goods/ProductGroupMap.cs
В группы товаров добавлен новый атрибут "Выделять в талонах погрузки"
В талоне погрузки товары из группы с отмеченным атрибутом выделяются жирным шрифтом
> 4977 Доработка печатной формы талона погрузки

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Payments/ManualPaymentMatchingViewModel.cs
> правка ручного распределения

- Source/Applications/Desktop/VodovozViewModels/Logistic/RouteListJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Print/PrintDocumentsSelectablePrinterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Print/Store/ContorlCarLoadDocumentRdl.cs
- Source/Applications/Desktop/VodovozViewModels/Print/Store/WaterCarLoadDocumentRdl.cs
- Source/Applications/Desktop/VodovozViewModels/VodovozViewModels.csproj
- Source/Libraries/Core/Business/Vodovoz.Reports.Editing/Modifiers/CarLoadDocuments/ControlCarLoadDocumentModifier.cs
- Source/Libraries/Core/Business/Vodovoz.Reports.Editing/Modifiers/CarLoadDocuments/WaterCarLoadDocumentModifier.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Store/CarLoadDocumentControl.rdl
- Source/Libraries/Core/Business/Vodovoz.Reports/Vodovoz.Reports.projitems
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/CarLoadDocument.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Employees/UserSettings.cs
- Source/Libraries/Core/Business/VodovozBusiness/PrintableDocuments/CustomPrintDocumentType.cs
Из талона погрузки воды выделена часть для контролера
> 4985 Доработка печатной формы талона погрузки.

- Source/Libraries/Core/Backend/Pacs/Pacs.Core/Messages/Events/OperatorStateEvent.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Operators/OperatorStateService.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Pacs/OperatorService.cs
Добавлено логирование в серверную часть, для получения более точной информации о передающихся значениях с сервера
Исправлен баг - падение при логировании номера манго
Исправлено логирование предыдущего состояния доступности звонка
> Хотфикс - логирование СКУД

- Source/Libraries/Core/Backend/Pacs/Pacs.MangoCalls/Services/CallEventRegistrar.cs
Убраны ненужные переменные
Добавлен лог количества обработанных событий манго
> Хотфикс - СКУД -Логирование обработки количества событий звонков

- Source/Applications/Desktop/Vodovoz/JournalViewModels/CounterpartyJournalViewModel.cs
- Source/Applications/Desktop/Vodovoz/JournalViewModels/RetailCounterpartyJournalViewModel.cs
сделал поиск только по коду и наименованию в виджетах фильтрации по клиенту
> правка поиска в журналах клиентов

- Source/Applications/Backend/WebAPI/CustomerOrdersApi/Controllers/OrdersController.cs
- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- переделал подписку на выбираемый контейнер в биндинг, т.к. при закрытии падало на отписке(скорее всего дребезг контактов мыши)
- поправил инфу в логе по созданию заказа;
> фикс диалога заказа

- Source/Applications/Desktop/Vodovoz/Views/Orders/OnlineOrderView.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Orders/OnlineOrderViewModel.cs
возможно тоже дребезг контактов
> попытка понять падение с закрытой сессией

- Source/Applications/Desktop/Vodovoz/SidePanel/InfoViews/CarsMonitoringInfoPanelView.cs
Ограничение выборки и форматирование запроса
> Хотфикс - панель мониторинга автомобилей

- Source/Applications/Desktop/VodovozViewModels/Widgets/UndeliveredOrderViewModel.cs
Возвращенные бутыли сбрасываются только для отмененных и недовозов
> Хотфикс. Фикс сброса возвращенных бутылей

- Source/Libraries/Core/Backend/Pacs/Pacs.MangoCalls/Services/CallEventRegistrar.cs
Фикс конкурентных заданий по публикации
> Хотфикс - СКУД - исправление отправки сообщений из регистратора событий звонков

- Source/Applications/Desktop/Vodovoz/JournalFilters/ReadyForReceptionFilter.cs
- Source/Applications/Desktop/Vodovoz/JournalFilters/ReadyForShipmentFilter.cs
- Source/Applications/Desktop/Vodovoz/Representations/ReadyForReceptionVM.cs
- Source/Applications/Desktop/Vodovoz/Representations/ReadyForShipmentVM.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReadyForReceptionFilter.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReadyForShipmentFilter.cs
> Правка Готовых к погрузке/разгрузке

- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReadyForReceptionFilter.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReadyForShipmentFilter.cs
из-за кривой логики в виджете выбора даты при потере фокуса, поменял фильтры местами, чтобы первым был фильтр по складу
> Правка фильтров Готовых к погрузке/разгрузке

- Source/Libraries/Core/Backend/Infrastructure/RabbitMQ.Infrastructure/RabbitMQConnectionFactory.cs
Добавление настроек игнорирования хост-имени сертификата для внутренних сетей dcoker
> Хотфикс подключения RabbitMQ

- Source/Applications/Desktop/Vodovoz/Views/Warehouse/MovementDocumentView.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Warehouses/MovementDocumentViewModel.cs
Исправлена проверка прав на изменение склада получателя в перемещении ТМЦ
> Хотфикс - права перемещения ТМЦ

- Source/Applications/Backend/WebAPI/CustomerOrdersApi/Startup.cs
- Source/Applications/Backend/WebAPI/Mango.Service/Program.cs
- Source/Libraries/Core/Backend/CustomerOrdersApi.Library/CustomerOrdersApiExtensions.cs
- Source/Libraries/Core/Backend/Infrastructure/MessageTransport/TransportSettings.cs
- Source/Libraries/Core/Backend/Mango/Mango.CallsPublishing/DependencyInjection.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Core/TransportConfiguration.cs
- Source/Libraries/Core/Business/Vodovoz.Settings.Database/Pacs/MessageTransportSettings.cs
- Source/Libraries/Core/Business/Vodovoz.Settings/Pacs/IMessageTransportSettings.cs
Настройка для возможности подключения через внутреннюю сеть
> 4989 - настройки для подключения MassTransit

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
Исправлено время блокирования кнопки
> Хотфикс - Исправление блокирования кнопок в диалоге заказа

- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailPrepareWorker/EmailPrepareWorker.cs
Временное решение по завершению работы воркера
> Хотфикс - EmailPrepareWorker выключение сервиса по лимиту обработанных сообщений

- Source/Applications/Desktop/Vodovoz/Views/Goods/NomenclatureView.cs
- Source/Applications/Desktop/VodovozViewModels/Dialogs/Goods/NomenclatureViewModel.cs
если у номенклатуры стоит учет состояния, то запрещаем менять этот параметр
> убираем возможность снятия учета состояния

- Source/Applications/Desktop/Vodovoz/Dialogs/Logistic/RouteListClosingDlg.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/RouteListClosingItemsView.cs
исправил контекстное меню и добавил обработку, если адрес не выбран
> правка закрытия МЛ

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Wages/DriverWage.rdl
т.к. операции по перемещению бутылей не создаются на одноразовую тару, то переделал расчет полных бутылей на заказ
> переделал расчет полных бутылей

- Source/Applications/Backend/WebAPI/DriverAPI/DriverAPI.csproj
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/DependencyInjection.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Options/ConfigureSwaggerOptions.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/SwaggerGen/EnumTypesDocumentFilter.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/SwaggerGen/EnumTypesSchemaFilter.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Vodovoz.Presentation.WebApi.csproj
Добавление функционала для Swagger в общую библиотеку
> Техническое - общие методы для Swagger

- Jenkinsfile
добавил в сборку новые воркеры по ЭДО
> Обновление сборки Дженкинса

- Source/Libraries/Core/Business/Vodovoz.Application/Services/CounterpartyService.cs
- Source/Libraries/Core/Business/VodovozBusiness/Services/ICounterpartyService.cs
Добавлен метод получения по нормализованному телефону
> Техническое - дополнения сервиса контрагента

- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Operations/IBottlesRepository.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Operations/BottlesRepository.cs
Изменены методы получения долга бутылей по точке доставки и клиенту, устаревшие помечены Obsolete
> Техническое - Рефакторинг BottlesRepository

- .pre-commit-config.yaml
- .secrets.baseline
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/DependencyInjection.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/FeatureFlags.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Security/ServiceApiKeyController.cs
- Source/Applications/Backend/WebAPI/Vodovoz.Presentation.WebApi/Vodovoz.Presentation.WebApi.csproj
Добавлен контроллер получения Jwt-токенов для сервисов
Добавлены Feature flags
Обновлен .secrets.baseline
> Техническое - Контроллер получения Jwt-токенов для сервисов

- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.S3/DependencyInjection.cs
> Техническое - исправление конфига S3

- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailStatusUpdateWorker/EmailStatusUpdateWorker.cs
- Source/Applications/Backend/Workers/Docker/EmailWorkers/EmailStatusUpdateWorker/Extensions/MailEventTypeExtensions.cs
Рефакторинг
Фиксы
Фиксы логирования
> Хотфикс - исправления в EmailStatusUpdateWorker

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
- Source/Libraries/Core/Backend/TaxcomEdo/TaxcomEdo.Contracts/Orders/OrderItemInfoForEdo.cs
пофиксил деление на ноль и пытаемся сохранить контейнер в состоянии ошибки, если при отправке в очередь возникла проблема
> Правка деления на ноль

- Source/Libraries/Core/Business/Vodovoz.Core.Domain/README.txt
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Vodovoz.Core.Domain.csproj
Добавлены ссылки на пакеты для разрешения внутренних конфликтов версий пакетов
> Техническое - исправление внутренних конфликтов версий пакетов

- Jenkinsfile
Добавлено копирования файла настроек
> Хотфикс - Пайплайн Jenkins

- Source/Applications/Backend/Services/Pacs.Admin.Service/Pacs.Admin.Service.csproj
- Source/Applications/Backend/Services/Pacs.Admin.Service/Properties/PublishProfiles/registry-dev.pubxml
- Source/Applications/Backend/Services/Pacs.Admin.Service/Properties/PublishProfiles/registry-prod.pubxml
- Source/Applications/Backend/Services/Pacs.Calls.Service/Pacs.Calls.Service.csproj
- Source/Applications/Backend/Services/Pacs.Calls.Service/Properties/PublishProfiles/registry-prod.pubxml
- Source/Applications/Backend/Services/Pacs.Operator.Service/Pacs.Operator.Service.csproj
- Source/Applications/Backend/Services/Pacs.Operator.Service/Program.cs
- Source/Applications/Backend/Services/Pacs.Operator.Service/Properties/PublishProfiles/registry-dev.pubxml
- Source/Applications/Backend/Services/Pacs.Operator.Service/Properties/PublishProfiles/registry-prod.pubxml
- Source/Applications/Backend/Services/Pacs.Operator.Service/Startup.cs
- Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/CustomerOnlineOrdersRegistrar.csproj
- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparer.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Admin.Client/Pacs.Admin.Client.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Admin.Server/Pacs.Admin.Server.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Admin.Server/SettingsController.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Admin.Server/SettingsNotifier.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Calls/Pacs.Calls.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Core/Pacs.Core.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.MangoCalls/Pacs.MangoCalls.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Operator.Client/Pacs.Operator.Client.csproj
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Pacs.Server.csproj
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Pacs/DomainSettings.cs
Убраны транзитивные зависимости
Добавлены докблоки
Поправлено форматирование
Исправлены профили публикации
> Техническое - Чистка СКУД

- Source/Applications/Backend/WebAPI/TaxcomEdoApi/TaxcomEdoApiExtensions.cs
- Source/Applications/Backend/WebAPI/TaxcomEdoApi/appsettings.json
- Source/Libraries/Core/Backend/TaxcomEdo/TaxcomEdoApi.Library/Config/TaxcomEdoApiOptions.cs
добавлена возможность установки параметров подписания для апи
> обновил настройку такском апи

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
перед отправкой документа по ЭДО, делаем проверку на корректность данных у клиента(кабинет и согласие по ЭДО)
> проверяем на согласие по ЭДО и заполненный номер кабинета

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Documents/Bill.rdl
расширил поля под счета организации, чтобы значения не наезжали на границы
> правка шаблона счета

- Source/Applications/Desktop/Vodovoz/ViewWidgets/ContactsView.cs
убрал возможность добавление контактных лиц при новом контрагенте. Во-первых этот виджет не используется и будет убран в интеграции юриков, а во-вторых, возникают ошибки при сохранении нового контрагента при попытке добавления контактного лица, полагаю по ошибке вместо добавления телефона
> не даем добавлять контакт для новой сущности

- Source/Applications/Desktop/Vodovoz/Dialogs/Client/CounterpartyDlg.cs
удаляем незаполненные телефоны и электронки перед проверкой на корректность данных
> чистим незаполненные телефоны и электронки

- Source/Libraries/Core/Backend/Mango/Mango.Api/DependencyInjection.cs
- Source/Libraries/Core/Backend/Mango/Mango.Core/Dto/MangoSummaryEvent.cs
- Source/Libraries/Core/Backend/Pacs/Pacs.Server/Consumers/Definitions/PacsServerCallEventConsumerDefinition.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Pacs/OperatorService.cs
Подчищена часть файлов
Улучшена читаемость одной из проверок
Перенесен метод в секцию после свойств
Заменено пересоздание строк на StringBuilder
Убрано добавление строк, если они пустые
> Хотфикс - СКУД - итерация чистки

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Store/RegradingOfGoodsTemplate.cs
> Техническое - чистка в шаблоне пересортицы

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/UndeliveredOrder.cs
Исправлена проблема с кодированием спецсимволов в поле информация Недовоза
Обновлен код, убраны string.Format
> Хотфикс - отображение спецсимволов в информации о недовозе

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
- Source/Libraries/Core/Backend/TaxcomEdo/TaxcomEdoApi.Library/Factories/EdoUpdFactory.cs
- сократил время работы подготовщика документов, чтобы перезагружался чаще;
- если нет маркированных товаров, ставим простое имя УПД без доп параметров
> обновил работу по ЭДО

- Source/Applications/Backend/Workers/Docker/DatabaseServiceWorker/PowerBiWorker/PowerBiExportWorker.Queries.cs
- Source/Applications/Backend/Workers/Docker/DatabaseServiceWorker/PowerBiWorker/PowerBiExportWorker.Reports.cs
> ХФ Выгружаем отчёт о доступности доставки за час за один день в PowerBI

- Source/Applications/Desktop/Vodovoz/Views/Client/EdoLightsMatrixView.cs
- Source/Applications/Desktop/VodovozViewModels/VodovozViewModels.csproj
- Source/Applications/Desktop/VodovozViewModels/Widgets/EdoLightsMatrix/EdoLightsColorizeType.cs
- Source/Applications/Desktop/VodovozViewModels/Widgets/EdoLightsMatrix/EdoLightsMatrixColumn.cs
- Source/Applications/Desktop/VodovozViewModels/Widgets/EdoLightsMatrix/EdoLightsMatrixPaymentType.cs
- Source/Applications/Desktop/VodovozViewModels/Widgets/EdoLightsMatrix/EdoLightsMatrixRow.cs
- Source/Applications/Desktop/VodovozViewModels/Widgets/EdoLightsMatrix/EdoLightsMatrixViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Clients/ReasonForLeaving.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Common/PossibleAccessState.cs
Заменен EdoLightsColorizeType на PossibleAccessState
Добавлены докблоки к енамам
Заменены ссылки
> Техническое - перенос типа

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Applications/Desktop/Vodovoz/Filters/GtkViews/NomenclaturesFilterView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- Source/Applications/Desktop/Vodovoz/ViewWidgets/OrderEquipmentItemsView.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.Filters.GtkViews.NomenclaturesFilterView.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/FilterViewModels/Goods/NomenclatureFilterViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Goods/NomenclaturesJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Orders/OrdersWithoutShipment/OrderWithoutShipmentForAdvancePaymentViewModel.cs
добавлен новый фильтр в журнал номенклатур, для отображения только номенклатур отправляемых в ИПЗ(сайт, приложение)
> Добавление фильтра только по онлайн номенклатурам

- Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/GtinJournalRegistrar.cs
- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Goods/GtinJournalViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Goods/GtinViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/ViewModels/Reports/EdoUpdReport/EdoUpdReportViewModel.cs
- Source/Applications/Desktop/VodovozViewModels/VodovozViewModels.csproj
- Source/Libraries/Core/Business/Vodovoz.Core.Data.NHibernate/Mapping/TrueMark/TrueMarkTransportCodeMap.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Data.NHibernate/Mapping/TrueMark/TrueMarkWaterGroupCodeMap.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Data.NHibernate/Mapping/TrueMark/TrueMarkWaterIdentificationCodeMap.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Goods/Gtin.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Goods/NomenclatureEntity.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/TrueMark/TrueMarkAnyCode.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/TrueMark/TrueMarkTransportCode.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/TrueMark/TrueMarkWaterGroupCode.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/TrueMark/TrueMarkWaterIdentificationCode.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Vodovoz.Core.Domain.csproj
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Goods/Nomenclature.cs
- Source/Vodovoz.Data.NHibernate/HibernateMapping/Goods/GtinMap.cs
Сущности
Базовая логика сущностей
Маппинг
> 4992 - Сущности и маппинг

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
формируем доки по старому, пока не обновим водительское
> вернул старое формирование

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V6/OrdersController.cs
- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V6/TrueMarkController.cs
Вынесен код для контроллера маркировки Честного знака в отдельный класс
> Техническое - Рефакторинг DriverApi

- Source/Applications/Backend/Workers/Docker/EdoServices/EdoDocumentsPreparer/EdoDocumentsPreparerWorker.cs
сначала обрабатываем таски, затем остальные заказы по объемному учету, если они есть
> обновил подготовщик доков по ЭДО

- Source/Applications/Backend/WebAPI/DriverAPI/Controllers/V6/TrueMarkController.cs
- Source/Libraries/Core/Backend/DriverAPI.Library/V6/Services/OrderService.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/RequestProcessingResult.cs
- Source/Libraries/Core/Business/VodovozBusiness/Errors/RequestProcessingResultT.cs
Исправлены ошибки с логировании в DriverApi
RequestProcessingResult - отмечен Obsolete
RequestProcessingResultT - отмечен Obsolete
> Хотфикс - исправление логирования DriverApi

- Source/Applications/Desktop/Vodovoz/ReportsParameters/MastersReport.cs
- Source/Applications/Desktop/Vodovoz/gtk-gui/Vodovoz.ReportsParameters.MastersReport.cs
- Source/Applications/Desktop/VodovozViewModels/ReportsParameters/Service/MastersReportViewModel.cs
- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/ServiceCenter/MastersReport.rdl
добавил возможность отображения частичных недовозов в отчете
> Изменение отчета по выездным мастерам

- Jenkinsfile
Добавлена проверка ноды онлайн
> Хотфикс - Jenkins

- Source/Libraries/Core/Backend/Edo/Edo.Documents/Consumers/TransferCompleteConsumer.cs
- Source/Libraries/Core/Backend/Edo/Edo.Documents/ForOwnNeedDocumentEdoTaskHandler.cs
- Source/Libraries/Core/Backend/Edo/Edo.Documents/ForResaleDocumentEdoTaskHandler.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/AnyOrderItemHavePositivePriceValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Scheduler/OrderTaskScheduler.cs
при формировании таски исключаем позиции с нулевой ценой и если это маркированная продукция, то кидаем код в пул при его наличии;
> 5224 отправляем только позиции с положительной ценой в УПД для ЭДО

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Documents/SelfDeliveryCodesScan/CodesScanViewModel.cs
> ХФ Убрал автоматическое закрытие формы сканирования для возможности скопировать коды

- Source/Applications/Desktop/VodovozViewModels/Journals/JournalViewModels/Edo/EdoProcessJournalViewModel.cs
- Source/Libraries/Core/Backend/TrueMark/TrueMark.Codes.Pool/TrueMarkCodesPool.cs
добавлена кнопка по отправке чеков, если по заказу есть только задачи с сохранением кодов в пул
> добавил кнопку по отправке чеков

- Source/Libraries/Core/Backend/Edo/Edo.Documents/ForOwnNeedDocumentEdoTaskHandler.cs
- Source/Libraries/Core/Backend/Edo/Edo.Receipt.Dispatcher/ForOwnNeedsReceiptEdoTaskHandler.cs
т.к. у нескольких номенклатур могут быть одинаковый gtin, то берем первый из списка
> берем первый gtinEntity

- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/OrderSelfdeliveryPaidEdoValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/OrderStatusEdoValidator.cs
убрал проверки оплаты и по статусу для самовывозов с перепродажей, чтобы коды не провисли
> обновил проверки для самовывозов

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Cash/CashRequest/CashRequest.cs
Временное возвращение перехода
> Хотфикс - заявки на выдачу наличных денежных средств

- Source/Applications/Desktop/VodovozViewModels/ViewModels/Cash/CashRequestViewModel.cs
> Хотфикс - Заявка на выдачу наличных ДС

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
убрал проверку валидности контакта на создание заказа и исправил косяк
> поправил валидацию заказа

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderFromOnlineOrderValidator.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Orders/OrderEntity.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Orders/Order.cs
- Source/Libraries/Core/Business/VodovozBusiness/Models/Stage2OrganizationProvider.cs
начинаем принимать оплаты с Терминалом и теперь они на Юг
> Отмена блокировки терминала

- Source/Libraries/Core/Backend/TaxcomEdo/TaxcomEdoApi.Library/Converters/Format5_03/UpdProductConverter5_03.cs
отдельно прописываем групповые и экземплярные коды в УПД xml
> разделяем групповые и экземплярные коды

- Source/Applications/Backend/WebAPI/RobotMiaApi/Controllers/V1/OrderController.cs
- Source/Applications/Backend/WebAPI/RobotMiaApi/Errors/RobotMiaErrors.OrderErrors.cs
- Source/Applications/Backend/WebAPI/RobotMiaApi/Errors/RobotMiaErrors.cs
- Source/Applications/Backend/WebAPI/RobotMiaApi/Services/IOrderService.cs
- Source/Applications/Backend/WebAPI/RobotMiaApi/Services/OrderService.cs
Быстрое исправление кода ошибки (требует дальнейшего рефакторинга)
Создает технический долг, см TODO, добавленный в этом ПР
> Фикс - RobotMia

- Source/Applications/Desktop/VodovozViewModels/Dialogs/Goods/NomenclatureViewModel.cs
- Source/Libraries/Core/Business/VodovozBusiness/Domain/Goods/NomenclaturesOnlineParameters/RobotMiaParameters.cs
Добавлена история 
Исправление сохранения параметров номенклатуры для робота Мия
> Исправление для номенклатур

- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Contacts/EmailEntity.cs
допускаем ноль или много соответствий после разделителя
> правка шаблона проверки электронной почты

- Source/Libraries/Core/Backend/Edo/Edo.Receipt.Dispatcher/ForOwnNeedsReceiptEdoTaskHandler.cs
правильно обрабатываем позиции
> фикс заполнения чека для собственных нужд

- Source/Libraries/Core/Backend/Edo/Edo.Docflow/DependencyInjection.cs
- Source/Libraries/Core/Backend/Edo/Edo.Docflow/DocflowHandler.cs
- Source/Libraries/Core/Backend/Edo/Edo.Docflow/Edo.Docflow.csproj
- Source/Libraries/Core/Backend/Edo/Edo.Docflow/Factories/TransferOrderUpdInfoFactory.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/EdoTaskValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/OrderEdoValidatorBase.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderCustomerIsNullValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderDateIsNotSetValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderIsNotNewValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderIsNullValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderSellerIsNullValidator.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/Validation/Sources/TransferOrderValidatorBase.cs
Добавлены валидаторы
Добавлена валидация
Добавлено подключение новой валидации
Убраны проверки из фабрики
> 5231 - Маркировка. Валидация трансфер заказа

- Source/Applications/Backend/WebAPI/RobotMiaApi/Services/OrderService.cs
исправление логики создания заказа
> Хотфикс - Робот Мия

- Source/Applications/Backend/WebAPI/Mango.Api.Service/Program.cs
- Source/Applications/Backend/WebAPI/Mango.Api.Service/Startup.cs
- Source/Libraries/Core/Backend/Mango/Mango.Api/Controllers/CallEventsController.cs
- Source/Libraries/Core/Backend/Mango/Mango.Api/DependencyInjection.cs
- Source/Libraries/Core/Backend/Mango/Mango.Api/Mango.Api.csproj
Добавлена телеметрия и исправлено логирование
> Хотфикс - MangoApi

- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderFromOnlineOrderCreator.cs
если телефон не принадлежит клиенту и это заказ с сайта - пишем его в комментарии
> обновление переноса контакта в заказ

- Source/Applications/Desktop/Vodovoz/JournalColumnsConfigs/WarehouseDocumentsItemsJournalRegistrar.cs
- Source/Applications/Desktop/Vodovoz/Store/RegradingOfGoodsDocumentItemsView.cs
вызываем правку значения количества пересортицы, только при изменении пользователем, а не постоянно при отрисовке И если значение на складе отрицательное, не приводим количество пересортицы к нему
> исправление изменений пересортицы

- Source/Libraries/Core/Business/Vodovoz.Application/Orders/Services/OrderService.cs
при установке типа оплаты терминал, по дефолту проставится источник по карте, если другого значения не установлено
> не вкидываем ошибку если в параметрах нет источника оплаты по терминалу

- Source/Libraries/Core/Backend/CustomerOrdersApi.Library/Services/CustomerOrdersService.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/Orders/OrderRepository.cs
если из онлайна создали один заказ, то отсылаем без Order.Id
если была разбивка на несколько, то отсылаем только order.id, как будто это заказы через оператора, чтобы не ломать историю
> правильно выбираем информацию по оформленным заказам с онлайна

- Source/Libraries/Core/Backend/Edo/Edo.Documents/ForOwnNeedDocumentEdoTaskHandler.cs
- Source/Libraries/Core/Backend/Edo/Edo.Problems/EdoProblemRegistrar.cs
- Source/Libraries/Core/Backend/Edo/Edo.Receipt.Dispatcher/ForOwnNeedsReceiptEdoTaskHandler.cs
- Source/Libraries/Infrastructure/Vodovoz.Infrastructure.Persistance/TrueMark/TrueMarkRepository.cs
Оптимизация загрузки кодов из пула в диалоге пула кодов
> Исправление ошибки отображения лишних кодов из пула

- Source/Applications/Desktop/Vodovoz/ViewWidgets/Logistics/OrderReturnsView.cs
- Source/Libraries/Core/Business/Vodovoz.Core.Domain/Permissions/Order.cs
Ещё нужно поменять имя в БД permissions_settings "can_edit_price_discount_from_route_list" на "can_edit_price_discount_from_route_list_and_self_delivery"
> Feature/5307 Редактирование самовывоза, изменение права

- Source/Applications/Desktop/Vodovoz/Dialogs/DocumentDialogs/IncomingWaterDlg.cs
если пользователю выдано право только доступ к складу и рекламациям, то не блокируем выбор склада, а закрываем его изменение через карандаш
> правка диалога документа производства

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Libraries/Core/Business/VodovozBusiness/Tools/Orders/OrderRules.cs
Поправил логику формирования УПД и удалил изменения ПР 4629
> Хотфикс Поправил логику формирования УПД

- Source/Libraries/Core/Business/VodovozBusiness/Domain/Documents/SelfDeliveryDocument.cs
Добавил валидацию для запрета частичного отпуска номенклатур
> 5376 - валидация для частичного отпуска номенклатур

- Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Consumers/OnlineOrderConsumer.cs
- Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Consumers/OnlineOrderRegisterFaultConsumer.cs
- Source/Applications/Backend/Workers/Docker/CustomerOnlineOrdersRegistrar/Consumers/OnlineOrderRegisteredConsumer.cs
- Source/Libraries/Core/Business/Vodovoz.Settings.Database/OnlineOrders/OnlineOrderCancellationReasonSettings.cs
- Source/Libraries/Core/Business/Vodovoz.Settings/OnlineOrders/IOnlineOrderCancellationReasonSettings.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/IOnlineOrderRepository.cs
- Source/Libraries/Core/Business/VodovozBusiness/EntityRepositories/Orders/OnlineOrderRepository.cs
Проверяем на возможные дубли и сразу отменяем с причиной дубль если есть совпадения
> обновление обработчика онлайн заказов

- Source/Applications/Desktop/Vodovoz/Dialogs/OrderWidgets/OrderDlg.cs
- Source/Applications/Desktop/Vodovoz/Logistic/RouteListKeepingView.cs
- Source/Applications/Desktop/Vodovoz/Views/Logistic/RouteListsOnDayView.cs
Добавил столбцы Клиент, Телефон, Отзвон за в ведение МЛ + добавил статусы заказов, в которых можно редактировать поле Ожидает До
> Хотфикс 5429 Доработка "Диалога ведения для логистов мониторинга" и предоставления доступа к вкладке "Время ожидания"

- Source/Applications/Desktop/Vodovoz/Additions/Accounting/WayBillDocumentGenerator.cs
> query edit for new car type

- Jenkinsfile
Не хватает места на диске c. Очистка файлов старше недели при сборки релиза
> Поправил кол-во дней хранения последних файлов дженкинс

- Source/Libraries/Core/Business/Vodovoz.Reports/Reports/Orders/SelfDeliveryReport.rdl
- правильно рассчитываем сумму заказа
- убираем все производства, а не только Псков
- убрал дубли отображений складов
> исправление отчета по самовывозу
